// Diperbarui: 13 Sep 2026 22:02 WIB
window.FK_DATA = {
  "generated": "13 Sep 2026 22:02 WIB",
  "kalender": {
    "generated": "13 Sep 2026 22:02 WIB",
    "events": []
  },
  "sentimen": {
    "generated": "13 Sep 2026 22:02 WIB",
    "summary": {
      "total": 57,
      "bullish": 21,
      "bearish": 31,
      "netral": 5,
      "avg_score": -0.1485,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "USD",
          "sentiment": "Bullish",
          "score": 0.116,
          "count": 5
        },
        {
          "currency": "EUR",
          "sentiment": "Bullish",
          "score": 0.095,
          "count": 2
        }
      ]
    },
    "items": [
      {
        "source": "Investing.com Forex",
        "title": "Saham Arab Saudi melemah pada penutupan perdagangan; Tadawul Semua Saham turun 1,30%",
        "url": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-lower-at-close-of-trade-tadawul-all-share-down-130-4898732",
        "summary": "",
        "published": "13 Sep 2026 19:45 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "ETF ekuitas AS melihat arus keluar sebesar $4,5 miliar karena para pedagang memperkirakan kenaikan suku bunga Fed",
        "url": "https://www.investing.com/news/stock-market-news/us-equity-etfs-see-outflows-of-45-billion-as-traders-price-in-fed-rate-hike-4898731",
        "summary": "",
        "published": "13 Sep 2026 19:37 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Panggilan jalan minggu ini: 7–11 September 2026",
        "url": "https://www.investing.com/news/stock-market-news/street-calls-of-the-week-sept-711-2026-93CH-4898686",
        "summary": "",
        "published": "13 Sep 2026 17:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Booming AI di Perancis mengungkap kesenjangan pendanaan di Eropa seiring dengan beralihnya startup ke AS",
        "url": "https://www.investing.com/news/stock-market-news/french-ai-boom-exposes-europes-funding-gap-as-startups-turn-to-us-4898724",
        "summary": "",
        "published": "13 Sep 2026 16:50 WIB",
        "sentiment": "Bearish",
        "score": -0.128,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Korea Selatan memperpanjang jam perdagangan saham untuk mendorong investor global",
        "url": "https://www.investing.com/news/stock-market-news/south-korea-extends-stock-trading-hours-in-push-for-global-investors-4898722",
        "summary": "",
        "published": "13 Sep 2026 16:07 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "5 kekhawatiran pasar yang tidak dapat diabaikan oleh investor, menurut Citi",
        "url": "https://www.investing.com/news/stock-market-news/the-5-market-worries-investors-cant-ignore-according-to-citi-4898719",
        "summary": "",
        "published": "13 Sep 2026 15:41 WIB",
        "sentiment": "Bearish",
        "score": -0.649,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "5 gerakan AI analis besar: JPMorgan meningkatkan Meta, menyebutkan stok peralatan chip teratas KLA",
        "url": "https://www.investing.com/news/stock-market-news/5-big-analyst-ai-moves-jpmorgan-upgrades-meta-names-kla-top-chip-equipment-stock-4898673",
        "summary": "",
        "published": "13 Sep 2026 15:31 WIB",
        "sentiment": "Bullish",
        "score": 0.202,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Perwakilan AS Tom Tiffany mengatakan dia menderita luka ringan setelah pesawat melakukan pendaratan darurat",
        "url": "https://www.investing.com/news/stock-market-news/us-rep-tom-tiffany-says-he-sustained-minor-injuries-after-plane-makes-emergency-landing-4898717",
        "summary": "",
        "published": "13 Sep 2026 15:30 WIB",
        "sentiment": "Bearish",
        "score": -0.382,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Perusahaan-perusahaan Jerman meningkatkan investasi Tiongkok sebesar sepertiganya karena pengeluaran AS merosot - kata IW",
        "url": "https://www.investing.com/news/stock-market-news/german-firms-raise-china-investment-by-a-third-as-us-outlays-slump--iw-says-4898713",
        "summary": "",
        "published": "13 Sep 2026 14:23 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Hyundai Motor akan meluncurkan sistem bantuan pengemudi internal pada tahun 2029",
        "url": "https://www.investing.com/news/stock-market-news/hyundai-motor-to-roll-out-inhouse-driverassist-system-in-2029-4898697",
        "summary": "",
        "published": "13 Sep 2026 07:18 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Economy",
        "title": "Meloni melihat pertumbuhan Italia pada tahun 2026 sebesar 1%, menyamai zona euro",
        "url": "https://www.investing.com/news/economic-indicators/meloni-sees-italy-2026-growth-at-1-matching-euro-zone-4898632",
        "summary": "",
        "published": "12 Sep 2026 14:30 WIB",
        "sentiment": "Bullish",
        "score": 0.462,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Bagaimana Silicon Valley Akan Mempersenjatai Kembali Amerika?",
        "url": "https://www.bloomberg.com/news/videos/2026-09-13/how-will-silicon-valley-rearm-america-video",
        "summary": "War in Ukraine, conflict in the Middle East and the rise of China have pushed national security back to the center of US economic and industrial strategy. Former Defense Secretary Mark Esper says the country needs to spend more on defense and better use cutting-edge weapons coming out of places like",
        "published": "13 Sep 2026 21:04 WIB",
        "sentiment": "Bullish",
        "score": 0.257,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Jalan LIV Golf Menuju Kebangkrutan senilai $5 Miliar",
        "url": "https://www.bloomberg.com/news/videos/2026-09-13/liv-golf-s-5-billion-path-to-bankruptcy",
        "summary": "LIV shook professional golf with flashy tournaments and big payouts, thanks to billions of dollars in backing from the Saudi sovereign wealth fund. On today’s Big Take podcast, David Gura and Golf.com senior writer Sean Zak look at why LIV Golf couldn’t make the cut — and how it changed pro golf. Li",
        "published": "13 Sep 2026 21:00 WIB",
        "sentiment": "Bullish",
        "score": 0.572,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Wall Street Mengatakan Tetap Mempertahankan Saham Meskipun Ada Suasana Dot-Com di Akhir Tahun 90-an",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/wall-street-says-stay-with-stocks-despite-late-90s-dot-com-vibe",
        "summary": "Rising bond yields and soaring oil prices have many Wall Street pros looking back a few decades to the volatile period before the dot-com crash. But that doesn’t mean they’re encouraging investors to dump their stocks.",
        "published": "13 Sep 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.09,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Setelah Lonjakan Minyak dan Perang, Negara Berkembang Tidak Terpengaruh oleh Risiko Fed",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/after-oil-surge-and-war-emerging-markets-unfazed-by-fed-risk",
        "summary": "Emerging markets have defied war, $100 oil and rising Treasury yields this year. And despite worries of a US interest-rate hike, investors see reasons for this year’s rally to keep going.",
        "published": "13 Sep 2026 19:52 WIB",
        "sentiment": "Bearish",
        "score": -0.696,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Iran Mencari Dukungan Teluk untuk Rencana Hormuz",
        "url": "https://www.bloomberg.com/news/videos/2026-09-13/iran-seeks-gulf-support-for-hormuz-plan-video",
        "summary": "Gulf states are weighing how to respond to Iran’s push for a new arrangement governing the Strait of Hormuz as continued attacks threaten shipping and drive up energy costs. On Bloomberg This Weekend, Bloomberg News Middle East Reporter Dan Williams and Bloomberg News White House Correspondent Skyla",
        "published": "13 Sep 2026 19:29 WIB",
        "sentiment": "Bearish",
        "score": -0.925,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Ukraina Mengatakan Kereta Penumpang Menuju Warsawa Ditabrak Drone",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/ukraine-says-passenger-train-headed-to-warsaw-is-hit-by-drone",
        "summary": "The locomotive of a passenger train traveling from Kyiv to Warsaw was hit by a Russian drone just kilometers from the Polish border on Sunday morning, Ukraine’s foreign minister said, as Moscow’s airstrikes push closer to NATO territory.",
        "published": "13 Sep 2026 17:52 WIB",
        "sentiment": "Bearish",
        "score": -0.132,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "RBI Dikatakan Menolak Permintaan Tata Sons untuk Menghindari IPO",
        "url": "https://www.bloomberg.com/news/articles/2026-09-12/rbi-said-to-reject-tata-sons-request-to-avoid-a-public-listing",
        "summary": "India’s central bank rejected an application from Tata Sons Pvt. to surrender its status as a shadow lender, according to people familiar with the matter, signaling it expects the company to adhere with rules for such entities that include an initial public offering.",
        "published": "12 Sep 2026 20:33 WIB",
        "sentiment": "Bearish",
        "score": -0.796,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "SpaceX Akan Mendapatkan Peningkatan Bobot di Nasdaq 100 Setelah Penyeimbangan Ulang",
        "url": "https://www.bloomberg.com/news/articles/2026-09-12/spacex-to-get-weighting-boost-in-nasdaq-100-after-rebalance",
        "summary": "SpaceX is set to get a larger weighting in the Nasdaq 100 later this month, a change that could trigger billions of dollars of buying by passive funds tied to the benchmark.",
        "published": "13 Sep 2026 00:58 WIB",
        "sentiment": "Bullish",
        "score": 0.542,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Bloomberg Akhir Pekan Ini 09/12/2026",
        "url": "https://www.bloomberg.com/news/videos/2026-09-12/bloomberg-this-weekend-09-12-2026-video",
        "summary": "The news doesn’t stop when markets close. Hosts David Gura, Christina Ruffini and Lisa Mateo bring clarity, context and a bit of humor to the weekend’s biggest headlines, LIVE from New York. Joined by Fmr. Ambassador to NATO Nick Burns, Council on Foreign Relations Ray Takeyh, Future of Life Institu",
        "published": "13 Sep 2026 00:10 WIB",
        "sentiment": "Bullish",
        "score": 0.572,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Google News Forex",
        "title": "Lonjakan inflasi membuat suku bunga kembali menjadi fokus saat para pembuat kebijakan bertemu di Jepang, AS, dan Inggris - theguardian.com",
        "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxPSjlxdEJuc05uQjJBcXJsU2cycGktTGlVMDVrVTdZcTRlMDRDNU9lWmhUaW9CTFB6cjhfdWpOaDkyaWhjeWp3amV1MkJmQXJkUjU1RERfWWY5T2hyNXhLX0puWHdFeFdCRHRRY0praXZPSjZGRmRQNDVuMUtBWjh3ME85endheVBtTXpxTjhXcXpaWER0X2dBTzFNeHd5bWtqdlE?oc=5",
        "summary": "Surging inflation puts interest rates back in focus as policymakers meet in Japan, US and UK theguardian.com",
        "published": "13 Sep 2026 20:56 WIB",
        "sentiment": "Bullish",
        "score": 0.718,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Google News Forex",
        "title": "Ringgit diperkirakan berada di antara RM4,06 dan RM4,08 terhadap dolar AS minggu depan - Malay Mail",
        "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxONFQwb21EZGN4ZW9kcmNYZGZJekp3ZFQ3UEliUmVEd2RveVktai1RZHNTVHJjckJfNW80UkRZQ1RkVUlMNmxyVzlfZHZfdkJ4WlZTM0V0bW9jS2hNQmx0MUZIWHF2VENQdzNTUVBlalkzRV9LX2hreV8zRE10TDljNlUtdjF5U25BQUplazV6ZlBlcEk2REE5SDB4dU9LRkE0RjVzMi1KUjZ2RFZNZ1EwMnI2TmpISG1zZ1p1OG9yUE1xd2pvMm9ZMF9LMm_SAdIBQVVfeXFMT0F0Rk12SllldTBHRTFHRDBNT1BEMDAyNTYzYUJINU9EVklsRlJKd0NIUXJiT24xZlN1aHl1VUNwNm94clE2MkRpTUVTV2NFSHF3S3RFWVBtZHgxTFJsdWNYQmlUSVZsNDNmS0QtWVItMW01S2d0bndlTEI3Z0JWc2lHUWdmTjZ3bEdfdGp0MDJhUGhha1dHaS1TZHZpYmlTYzR5LVNDbGxwSjg3c3dFNnRMYnNlWnBMblBNcUVSbUxNM1VzRWhyaGtiMWVRYlBwTVRR?oc=5",
        "summary": "Ringgit expected to hover between RM4.06 and RM4.08 against US dollar next week Malay Mail",
        "published": "12 Sep 2026 10:21 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Perang Iran membentuk kembali hubungan Bric tetapi juga memperlihatkan perpecahan",
        "url": "https://www.bbc.co.uk/news/articles/ce8767g4jdpo?at_medium=RSS&at_campaign=rss",
        "summary": "Brics members agree they need a new global order but it's harder to answer what should replace it and how to get there.",
        "published": "13 Sep 2026 18:23 WIB",
        "sentiment": "Bearish",
        "score": -0.067,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Komentar Trump mengenai persatuan Irlandia mungkin ditujukan kepada khalayak di seluruh Atlantik",
        "url": "https://www.bbc.co.uk/news/articles/cwyzppd1d5lo?at_medium=RSS&at_campaign=rss",
        "summary": "Nobody could have predicted that today's main global headline would be Trump's desire to see a unified Ireland.",
        "published": "13 Sep 2026 04:25 WIB",
        "sentiment": "Bullish",
        "score": 0.796,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Hanya handuk Roland Garros yang tersisa, kata pemain tenis Ukraina setelah serangan Rusia gagal",
        "url": "https://www.bbc.co.uk/news/articles/c4gr33g3evlo?at_medium=RSS&at_campaign=rss",
        "summary": "Dayana Yastremska says her flat took a \"direct hit\" by a Russian missile in Odesa, and all that left was her Roland Garros towel.",
        "published": "13 Sep 2026 03:27 WIB",
        "sentiment": "Bearish",
        "score": -0.208,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Wanita Afghanistan dideportasi dari AS untuk pertama kalinya menggunakan pengadilan 'teroris alien'",
        "url": "https://www.bbc.co.uk/news/articles/c3eqpd9zgl9o?at_medium=RSS&at_campaign=rss",
        "summary": "The legal US resident was never charged with a crime, but was deported due to her family links to terrorism.",
        "published": "13 Sep 2026 04:19 WIB",
        "sentiment": "Bearish",
        "score": -0.899,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Peringatan dramatis dari orang dalam mengenai AI tidak berlaku bagi sebagian orang di Silicon Valley",
        "url": "https://www.bbc.co.uk/news/articles/cq635037g18o?at_medium=RSS&at_campaign=rss",
        "summary": "A recent spate of stark warnings about the dangers of AI has been met with scepticism by executives and investors.",
        "published": "13 Sep 2026 16:05 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Sahabat selama beberapa dekade - sampai tes DNA mengungkapkan bahwa mereka adalah saudara perempuan",
        "url": "https://www.bbc.co.uk/news/articles/c5y6z72z9lno?at_medium=RSS&at_campaign=rss",
        "summary": "Meena Geltink and Minal Tijssen were adopted from orphanages in Mumbai in the 1980s and grew up in the Netherlands.",
        "published": "13 Sep 2026 05:00 WIB",
        "sentiment": "Bullish",
        "score": 0.807,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "Peringatan 'Skimpflasi' karena alternatif makarel kalengan lebih banyak tersedia di rak supermarket",
        "url": "https://www.bbc.co.uk/news/articles/crm9xk9eg88o?at_medium=RSS&at_campaign=rss",
        "summary": "Consumer group Which? has called the sale of jack mackerel, a cheaper, less nutritious species of fish, an example of \"skimpflation\".",
        "published": "13 Sep 2026 03:37 WIB",
        "sentiment": "Bearish",
        "score": -0.42,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "'Kemungkinan kecil' pemerintah akan mencapai target 1,5 juta rumah baru, kata Rayner kepada BBC",
        "url": "https://www.bbc.co.uk/news/articles/cgqdlw0x092o?at_medium=RSS&at_campaign=rss",
        "summary": "High construction costs and the Iran war are threatening the key manifesto pledge, the housing secretary says.",
        "published": "13 Sep 2026 18:16 WIB",
        "sentiment": "Bearish",
        "score": -0.823,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Gambar pelecehan anak di Kedutaan AS diduga diterbangkan dari Inggris sebelum wawancara polisi",
        "url": "https://www.bbc.co.uk/news/articles/c4gjw1j1eq7o?at_medium=RSS&at_campaign=rss",
        "summary": "The individual worked at the US embassy in Vauxhall, south London, had diplomatic protection, despite not being a diplomat.",
        "published": "13 Sep 2026 20:31 WIB",
        "sentiment": "Bearish",
        "score": -0.751,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Eropa harus menanggung kesulitan di musim dingin untuk terus menekan Putin, kata penasihat keamanan PM",
        "url": "https://www.bbc.co.uk/news/articles/crr4en2ylz8o?at_medium=RSS&at_campaign=rss",
        "summary": "In rare public remarks, Jonathan Powell said now was not the time for European nations to take their \"foot off the gas\".",
        "published": "13 Sep 2026 13:21 WIB",
        "sentiment": "Bearish",
        "score": -0.273,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Serangan pesawat tak berawak Ukraina menewaskan empat orang saat Rusia menyerang di dekat perbatasan Polandia",
        "url": "https://www.aljazeera.com/news/2026/9/13/ukraine-drone-strikes-kill-four-as-russia-attacks-close-to-poland-border?traffic_source=rss",
        "summary": "Russia says four people killed in Ukrainian strikes as both sides continue to attack each other with waves of drones.",
        "published": "13 Sep 2026 20:05 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Perang Iran mengungkap batasan BRICS",
        "url": "https://www.aljazeera.com/opinions/2026/9/13/the-iran-war-reveals-the-limits-of?traffic_source=rss",
        "summary": "The bloc struggles to translate its economic weight into geopolitical sway. But there may be a silver lining to it.",
        "published": "13 Sep 2026 19:46 WIB",
        "sentiment": "Bearish",
        "score": -0.574,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Eskalasi Houthi di Yaman bisa saja gagal",
        "url": "https://www.aljazeera.com/opinions/2026/9/13/the-houthis-escalation-in-yemen-could-flop?traffic_source=rss",
        "summary": "The Houthis and Iran are seeking to gain leverage, but they may instead get a unified front in the Red Sea.",
        "published": "13 Sep 2026 19:39 WIB",
        "sentiment": "Bullish",
        "score": 0.599,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "KTT BRICS 2026: Apa kesimpulan utamanya?",
        "url": "https://www.aljazeera.com/news/2026/9/13/brics-summit-2026-what-are-the-key-takeaways?traffic_source=rss",
        "summary": "The 11-nation bloc avoids condemning the US-Israel war on Iran, showing the divisions among the members.",
        "published": "13 Sep 2026 19:04 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Kehidupan yang bermartabat adalah ‘impian lama’ bagi banyak keluarga Iran di tengah perang Amerika",
        "url": "https://www.aljazeera.com/economy/2026/9/13/a-dignified-life-is-a-distant-dream-for-many-iranian-families-amid-us-war?traffic_source=rss",
        "summary": "With constant degredation and no real prospects of improvement in the foreseeable future, Iranians are losing hope.",
        "published": "13 Sep 2026 18:45 WIB",
        "sentiment": "Bearish",
        "score": -0.205,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Filipina akan mengadakan pemungutan suara bersejarah di Bangsamoro setelah konflik selama beberapa dekade",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/9/13/philippines-set-for-historic-vote-in-bangsamoro-after-decades-of-conflict?traffic_source=rss",
        "summary": "Philippines set for historic vote in Bangsamoro after decades of conflict",
        "published": "13 Sep 2026 18:35 WIB",
        "sentiment": "Bearish",
        "score": -0.637,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Pertempuran Berlanjut Antara Pasukan Pemerintah Yaman, Houthi: Apa Yang Terbaru?",
        "url": "https://www.aljazeera.com/news/2026/9/13/fighting-continues-between-yemen-govt-forces-houthis-what-is-the-latest?traffic_source=rss",
        "summary": "Government forces and Saudi Arabia carry out air attacks to stop Houthis' advance as thousands displaced by conflict.",
        "published": "13 Sep 2026 17:47 WIB",
        "sentiment": "Bearish",
        "score": -0.996,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Serangan Israel di Gaza menewaskan dua warga Palestina",
        "url": "https://www.aljazeera.com/news/2026/9/13/israeli-attack-on-gaza-kills-two-palestinians?traffic_source=rss",
        "summary": "Israeli strikes on Palestinian territory persist despite a 'ceasefire' brokered by the United States.",
        "published": "13 Sep 2026 17:22 WIB",
        "sentiment": "Bearish",
        "score": -0.743,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Sebuah kerajaan di dalam republik: Di dalam Buganda Uganda",
        "url": "https://www.aljazeera.com/news/2026/9/13/a-kingdom-within-a-republic-inside-ugandas-buganda?traffic_source=rss",
        "summary": "The kingdom’s traditions and institutions have endured through colonial rule, independence and decades of upheaval.",
        "published": "13 Sep 2026 17:12 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Pemerintah militer Niger merombak komando militer beberapa minggu setelah pemberontakan mematikan",
        "url": "https://www.aljazeera.com/news/2026/9/13/niger-military-government-reshuffles-army-command-weeks-after-deadly-mutiny?traffic_source=rss",
        "summary": "New chief of staff appointed after failed mutiny tested military rulers' grip on power.",
        "published": "13 Sep 2026 15:54 WIB",
        "sentiment": "Bearish",
        "score": -0.511,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Pemungutan suara sedang berlangsung dalam pemilu Swedia yang mungkin didominasi kelompok sayap kanan dalam pemerintahan",
        "url": "https://www.aljazeera.com/news/2026/9/13/voting-under-way-in-sweden-election-that-could-see-far-right-enter-govt?traffic_source=rss",
        "summary": "The far-right Sweden Democrats party could enter government for the first time if right-wing bloc wins.",
        "published": "13 Sep 2026 15:39 WIB",
        "sentiment": "Bullish",
        "score": 0.751,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "Masjid dan rumah rusak di Arab Saudi setelah dugaan serangan Houthi",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/9/13/mosque-and-homes-damaged-in-saudi-arabia-after-alleged-houthi-strike?traffic_source=rss",
        "summary": "Mosque and homes damaged in Saudi Arabia after alleged Houthi strike",
        "published": "13 Sep 2026 15:13 WIB",
        "sentiment": "Bearish",
        "score": -0.778,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Harga hampir semua barang di meja makan Anda langsung naik — dan Wall Street mulai memperhatikannya",
        "url": "https://www.marketwatch.com/story/the-price-of-almost-everything-on-your-dinner-table-is-climbing-at-once-and-wall-street-is-taking-notice-9623d1fc?mod=mw_rss_topstories",
        "summary": "Rising crop prices are making the current inflation problem bigger than just oil and the Iran war.",
        "published": "13 Sep 2026 20:00 WIB",
        "sentiment": "Bearish",
        "score": -0.845,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "‘Saya masih belum memiliki MRI’: Perusahaan asuransi kesehatan saya membatalkan rencana saya tanpa peringatan. Apakah itu sah?",
        "url": "https://www.marketwatch.com/story/i-still-dont-have-my-mri-my-health-insurer-canceled-my-plan-without-warning-is-that-legal-02143710?mod=mw_rss_topstories",
        "summary": "“It wasn’t an ACA plan, but it was meaningfully cheaper than anything I could find on the ACA exchange.”",
        "published": "13 Sep 2026 19:40 WIB",
        "sentiment": "Bullish",
        "score": 0.115,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC Forex",
        "title": "Perjalanan pulang-pergi minyak kembali ke $100. Mengapa Tiongkok bisa menentukan apa yang terjadi selanjutnya",
        "url": "https://www.cnbc.com/2026/09/12/oils-roundtrip-back-to-100-why-china-could-determine-what-happens-next.html",
        "summary": "The U.S. crude oil price on Thursday topped $102 per barrel for its highest close since May.",
        "published": "12 Sep 2026 19:40 WIB",
        "sentiment": "Bearish",
        "score": -0.572,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC Forex",
        "title": "Keyakinan Buffett terhadap akuisisi yang bermasalah selama satu dekade akhirnya membuahkan hasil",
        "url": "https://www.cnbc.com/2026/09/12/buffetts-confidence-in-troubled-decade-old-acquisition-finally-pays-off.html",
        "summary": "Warren Buffett has said he paid too much for Precision Castparts in 2016. Now its complex metal castings are in high demand.",
        "published": "12 Sep 2026 20:20 WIB",
        "sentiment": "Bearish",
        "score": -0.132,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC Economy",
        "title": "GM merencanakan pengembangan baterai AS ketika DOT Trump menyerang Ford karena hubungan dengan Tiongkok",
        "url": "https://www.cnbc.com/2026/09/12/gm-us-battery-development-ford-china-ties.html",
        "summary": "Most battery cells currently rely on raw materials from China. GM is seeking to establish domestic supply chains both for EVs and energy storage.",
        "published": "12 Sep 2026 19:00 WIB",
        "sentiment": "Bearish",
        "score": -0.282,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Kapal diserang di Selat Hormuz, kata UKMTO, karena prospek diplomasi AS-Iran tampak sulit dicapai",
        "url": "https://www.cnbc.com/2026/09/13/vessel-struck-strait-of-hormuz-ukmto.html",
        "summary": "The latest strike happened ahead of an expected meeting between Iranian and Gulf officials in Oman to sign an agreement for shipping through the strait.",
        "published": "13 Sep 2026 20:38 WIB",
        "sentiment": "Bullish",
        "score": 0.52,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "OpenAI mengesampingkan IPO tahun ini karena Altman, Musk & Amodei memperingatkan AI bergerak terlalu cepat",
        "url": "https://www.cnbc.com/2026/09/12/anthropics-amodei-proposes-plan-to-slow-the-pace-of-advancing-ai-capabilities.html",
        "summary": "Altman's IPO comments and Amodei's public call for more careful pacing of AI development cap a week of loud AI warnings.",
        "published": "13 Sep 2026 19:29 WIB",
        "sentiment": "Bearish",
        "score": -0.26,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Presiden Tiongkok Xi mendesak negara-negara BRICS untuk berupaya mewujudkan perdamaian di Timur Tengah",
        "url": "https://www.cnbc.com/2026/09/13/chinas-xi-urges-brics-peace-middle-east.html",
        "summary": "China, Iran's biggest trading partner and a key customer of Tehran's energy exports, is willing to work with BRICS towards peace in the region, Xi said.",
        "published": "13 Sep 2026 16:41 WIB",
        "sentiment": "Bullish",
        "score": 0.764,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Rusia, Trump, dan pertikaian mengenai kesejahteraan membayangi pemilu Swedia",
        "url": "https://www.cnbc.com/2026/09/12/sweden-election-russia-trump-welfare-defense.html",
        "summary": "Russia's war, permanently higher defense spending and uncertainty over U.S. commitments are narrowing the choices facing whoever wins Sunday's election.",
        "published": "12 Sep 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.705,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Larry Ellison nixes berencana melepas saham Oracle senilai hingga $7,5 miliar",
        "url": "https://www.cnbc.com/2026/09/12/larry-ellison-nixes-plan-to-offload-up-to-7point5-billion-worth-of-oracle-stock-.html",
        "summary": "Oracle founder Larry Ellison has canceled his plan to sell up to $7.5 billion worth of stock in the software company.",
        "published": "13 Sep 2026 00:14 WIB",
        "sentiment": "Bullish",
        "score": 0.341,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Trump melihat perang Iran berakhir segera setelah pemilu paruh waktu, memperkirakan harga minyak akan turun tajam",
        "url": "https://www.cnbc.com/2026/09/12/trump-sees-iran-war-ending-very-soon-oil-prices-then-falling.html",
        "summary": "Oil prices retreated on Friday on hopes of a resumptions in negotiations, but notched sharp weekly gains after soaring above $100 a barrel.",
        "published": "13 Sep 2026 00:22 WIB",
        "sentiment": "Bullish",
        "score": 0.292,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Dunia Trump yang mengutamakan Amerika mendorong negara-negara lain untuk melakukan lindung nilai terhadap taruhan mereka",
        "url": "https://www.cnbc.com/2026/09/12/brics-summit-xi-putin-modi-trump.html",
        "summary": "Xi, Putin and Modi meet in New Delhi as U.S. tariffs, sanctions and the Iran war test whether BRICS members can find more common ground.",
        "published": "12 Sep 2026 20:24 WIB",
        "sentiment": "Bearish",
        "score": -0.759,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Inflasi kembali melampaui pertumbuhan upah, sehingga mengurangi gaji warga Amerika",
        "url": "https://www.cnbc.com/2026/09/12/inflation-is-outpacing-wage-growth-again-squeezing-americans-paychecks.html",
        "summary": "In August, consumer prices rose 3.4% over the past year while wages increased just 3.1%.",
        "published": "12 Sep 2026 19:49 WIB",
        "sentiment": "Bullish",
        "score": 0.732,
        "emoji": "🟢",
        "impact": "medium"
      }
    ]
  },
  "geopolitik": {
    "generated": "13 Sep 2026 22:02 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.373,
        "count": 18
      },
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.365,
        "count": 16
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.277,
        "count": 15
      },
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.644,
        "count": 7
      },
      {
        "pair": "CAD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.063,
        "count": 3
      },
      {
        "pair": "NOK/SEK",
        "direction": "Tekanan Turun ▼",
        "score": -0.063,
        "count": 3
      },
      {
        "pair": "EUR",
        "direction": "Tekanan Turun ▼",
        "score": -0.115,
        "count": 1
      },
      {
        "pair": "GBP",
        "direction": "Tekanan Turun ▼",
        "score": -0.115,
        "count": 1
      }
    ],
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Bagaimana Silicon Valley Akan Mempersenjatai Kembali Amerika?",
        "url": "https://www.bloomberg.com/news/videos/2026-09-13/how-will-silicon-valley-rearm-america-video",
        "summary": "War in Ukraine, conflict in the Middle East and the rise of China have pushed national security back to the center of US economic and industrial strategy. Former Defense Secretary Mark Esper says the country needs to spend more on defense and better use cutting-edge weapons coming out of places like",
        "published": "13 Sep 2026 21:04 WIB",
        "sentiment": "Bullish",
        "score": 0.257,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Wall Street Mengatakan Tetap Mempertahankan Saham Meskipun Ada Suasana Dot-Com di Akhir Tahun 90-an",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/wall-street-says-stay-with-stocks-despite-late-90s-dot-com-vibe",
        "summary": "Rising bond yields and soaring oil prices have many Wall Street pros looking back a few decades to the volatile period before the dot-com crash. But that doesn’t mean they’re encouraging investors to dump their stocks.",
        "published": "13 Sep 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.09,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Setelah Lonjakan Minyak dan Perang, Negara Berkembang Tidak Terpengaruh oleh Risiko Fed",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/after-oil-surge-and-war-emerging-markets-unfazed-by-fed-risk",
        "summary": "Emerging markets have defied war, $100 oil and rising Treasury yields this year. And despite worries of a US interest-rate hike, investors see reasons for this year’s rally to keep going.",
        "published": "13 Sep 2026 19:52 WIB",
        "sentiment": "Bearish",
        "score": -0.115,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Iran Mencari Dukungan Teluk untuk Rencana Hormuz",
        "url": "https://www.bloomberg.com/news/videos/2026-09-13/iran-seeks-gulf-support-for-hormuz-plan-video",
        "summary": "Gulf states are weighing how to respond to Iran’s push for a new arrangement governing the Strait of Hormuz as continued attacks threaten shipping and drive up energy costs. On Bloomberg This Weekend, Bloomberg News Middle East Reporter Dan Williams and Bloomberg News White House Correspondent Skyla",
        "published": "13 Sep 2026 19:29 WIB",
        "sentiment": "Bearish",
        "score": -0.925,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Ukraina Mengatakan Kereta Penumpang Menuju Warsawa Ditabrak Drone",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/ukraine-says-passenger-train-headed-to-warsaw-is-hit-by-drone",
        "summary": "The locomotive of a passenger train traveling from Kyiv to Warsaw was hit by a Russian drone just kilometers from the Polish border on Sunday morning, Ukraine’s foreign minister said, as Moscow’s airstrikes push closer to NATO territory.",
        "published": "13 Sep 2026 17:52 WIB",
        "sentiment": "Bearish",
        "score": -0.132,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Bloomberg Akhir Pekan Ini 09/12/2026",
        "url": "https://www.bloomberg.com/news/videos/2026-09-12/bloomberg-this-weekend-09-12-2026-video",
        "summary": "The news doesn’t stop when markets close. Hosts David Gura, Christina Ruffini and Lisa Mateo bring clarity, context and a bit of humor to the weekend’s biggest headlines, LIVE from New York. Joined by Fmr. Ambassador to NATO Nick Burns, Council on Foreign Relations Ray Takeyh, Future of Life Institu",
        "published": "13 Sep 2026 00:10 WIB",
        "sentiment": "Bullish",
        "score": 0.572,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Hanya handuk Roland Garros yang tersisa, kata pemain tenis Ukraina setelah serangan Rusia gagal",
        "url": "https://www.bbc.co.uk/news/articles/c4gr33g3evlo?at_medium=RSS&at_campaign=rss",
        "summary": "Dayana Yastremska says her flat took a \"direct hit\" by a Russian missile in Odesa, and all that left was her Roland Garros towel.",
        "published": "13 Sep 2026 03:27 WIB",
        "sentiment": "Bearish",
        "score": -0.208,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Wanita Afghanistan dideportasi dari AS untuk pertama kalinya menggunakan pengadilan 'teroris alien'",
        "url": "https://www.bbc.co.uk/news/articles/c3eqpd9zgl9o?at_medium=RSS&at_campaign=rss",
        "summary": "The legal US resident was never charged with a crime, but was deported due to her family links to terrorism.",
        "published": "13 Sep 2026 04:19 WIB",
        "sentiment": "Bearish",
        "score": -0.899,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Peringatan dramatis dari orang dalam mengenai AI tidak berlaku bagi sebagian orang di Silicon Valley",
        "url": "https://www.bbc.co.uk/news/articles/cq635037g18o?at_medium=RSS&at_campaign=rss",
        "summary": "A recent spate of stark warnings about the dangers of AI has been met with scepticism by executives and investors.",
        "published": "13 Sep 2026 16:05 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "'Kemungkinan kecil' pemerintah akan mencapai target 1,5 juta rumah baru, kata Rayner kepada BBC",
        "url": "https://www.bbc.co.uk/news/articles/cgqdlw0x092o?at_medium=RSS&at_campaign=rss",
        "summary": "High construction costs and the Iran war are threatening the key manifesto pledge, the housing secretary says.",
        "published": "13 Sep 2026 18:16 WIB",
        "sentiment": "Bearish",
        "score": -0.823,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Gambar pelecehan anak di Kedutaan AS diduga diterbangkan dari Inggris sebelum wawancara polisi",
        "url": "https://www.bbc.co.uk/news/articles/c4gjw1j1eq7o?at_medium=RSS&at_campaign=rss",
        "summary": "The individual worked at the US embassy in Vauxhall, south London, had diplomatic protection, despite not being a diplomat.",
        "published": "13 Sep 2026 20:31 WIB",
        "sentiment": "Bearish",
        "score": -0.751,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Serangan pesawat tak berawak Ukraina menewaskan empat orang saat Rusia menyerang di dekat perbatasan Polandia",
        "url": "https://www.aljazeera.com/news/2026/9/13/ukraine-drone-strikes-kill-four-as-russia-attacks-close-to-poland-border?traffic_source=rss",
        "summary": "Russia says four people killed in Ukrainian strikes as both sides continue to attack each other with waves of drones.",
        "published": "13 Sep 2026 20:05 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Perang Iran mengungkap batasan BRICS",
        "url": "https://www.aljazeera.com/opinions/2026/9/13/the-iran-war-reveals-the-limits-of?traffic_source=rss",
        "summary": "The bloc struggles to translate its economic weight into geopolitical sway. But there may be a silver lining to it.",
        "published": "13 Sep 2026 19:46 WIB",
        "sentiment": "Bearish",
        "score": -0.574,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "KTT BRICS 2026: Apa kesimpulan utamanya?",
        "url": "https://www.aljazeera.com/news/2026/9/13/brics-summit-2026-what-are-the-key-takeaways?traffic_source=rss",
        "summary": "The 11-nation bloc avoids condemning the US-Israel war on Iran, showing the divisions among the members.",
        "published": "13 Sep 2026 19:04 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Filipina akan mengadakan pemungutan suara bersejarah di Bangsamoro setelah konflik selama beberapa dekade",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/9/13/philippines-set-for-historic-vote-in-bangsamoro-after-decades-of-conflict?traffic_source=rss",
        "summary": "Philippines set for historic vote in Bangsamoro after decades of conflict",
        "published": "13 Sep 2026 18:35 WIB",
        "sentiment": "Bearish",
        "score": -0.637,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Pertempuran Berlanjut Antara Pasukan Pemerintah Yaman, Houthi: Apa Yang Terbaru?",
        "url": "https://www.aljazeera.com/news/2026/9/13/fighting-continues-between-yemen-govt-forces-houthis-what-is-the-latest?traffic_source=rss",
        "summary": "Government forces and Saudi Arabia carry out air attacks to stop Houthis' advance as thousands displaced by conflict.",
        "published": "13 Sep 2026 17:47 WIB",
        "sentiment": "Bearish",
        "score": -0.996,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Serangan Israel di Gaza menewaskan dua warga Palestina",
        "url": "https://www.aljazeera.com/news/2026/9/13/israeli-attack-on-gaza-kills-two-palestinians?traffic_source=rss",
        "summary": "Israeli strikes on Palestinian territory persist despite a 'ceasefire' brokered by the United States.",
        "published": "13 Sep 2026 17:22 WIB",
        "sentiment": "Bearish",
        "score": -0.743,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Pemerintah militer Niger merombak komando militer beberapa minggu setelah pemberontakan mematikan",
        "url": "https://www.aljazeera.com/news/2026/9/13/niger-military-government-reshuffles-army-command-weeks-after-deadly-mutiny?traffic_source=rss",
        "summary": "New chief of staff appointed after failed mutiny tested military rulers' grip on power.",
        "published": "13 Sep 2026 15:54 WIB",
        "sentiment": "Bearish",
        "score": -0.511,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Harga hampir semua barang di meja makan Anda langsung naik — dan Wall Street mulai memperhatikannya",
        "url": "https://www.marketwatch.com/story/the-price-of-almost-everything-on-your-dinner-table-is-climbing-at-once-and-wall-street-is-taking-notice-9623d1fc?mod=mw_rss_topstories",
        "summary": "Rising crop prices are making the current inflation problem bigger than just oil and the Iran war.",
        "published": "13 Sep 2026 20:00 WIB",
        "sentiment": "Bearish",
        "score": -0.845,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC Forex",
        "title": "Perjalanan pulang-pergi minyak kembali ke $100. Mengapa Tiongkok bisa menentukan apa yang terjadi selanjutnya",
        "url": "https://www.cnbc.com/2026/09/12/oils-roundtrip-back-to-100-why-china-could-determine-what-happens-next.html",
        "summary": "The U.S. crude oil price on Thursday topped $102 per barrel for its highest close since May.",
        "published": "12 Sep 2026 19:40 WIB",
        "sentiment": "Bearish",
        "score": -0.572,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC Forex",
        "title": "Keyakinan Buffett terhadap akuisisi yang bermasalah selama satu dekade akhirnya membuahkan hasil",
        "url": "https://www.cnbc.com/2026/09/12/buffetts-confidence-in-troubled-decade-old-acquisition-finally-pays-off.html",
        "summary": "Warren Buffett has said he paid too much for Precision Castparts in 2016. Now its complex metal castings are in high demand.",
        "published": "12 Sep 2026 20:20 WIB",
        "sentiment": "Bearish",
        "score": -0.132,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "OpenAI mengesampingkan IPO tahun ini karena Altman, Musk & Amodei memperingatkan AI bergerak terlalu cepat",
        "url": "https://www.cnbc.com/2026/09/12/anthropics-amodei-proposes-plan-to-slow-the-pace-of-advancing-ai-capabilities.html",
        "summary": "Altman's IPO comments and Amodei's public call for more careful pacing of AI development cap a week of loud AI warnings.",
        "published": "13 Sep 2026 19:29 WIB",
        "sentiment": "Bearish",
        "score": -0.26,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Presiden Tiongkok Xi mendesak negara-negara BRICS untuk berupaya mewujudkan perdamaian di Timur Tengah",
        "url": "https://www.cnbc.com/2026/09/13/chinas-xi-urges-brics-peace-middle-east.html",
        "summary": "China, Iran's biggest trading partner and a key customer of Tehran's energy exports, is willing to work with BRICS towards peace in the region, Xi said.",
        "published": "13 Sep 2026 16:41 WIB",
        "sentiment": "Bullish",
        "score": 0.764,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Rusia, Trump, dan pertikaian mengenai kesejahteraan membayangi pemilu Swedia",
        "url": "https://www.cnbc.com/2026/09/12/sweden-election-russia-trump-welfare-defense.html",
        "summary": "Russia's war, permanently higher defense spending and uncertainty over U.S. commitments are narrowing the choices facing whoever wins Sunday's election.",
        "published": "12 Sep 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.705,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Larry Ellison nixes berencana melepas saham Oracle senilai hingga $7,5 miliar",
        "url": "https://www.cnbc.com/2026/09/12/larry-ellison-nixes-plan-to-offload-up-to-7point5-billion-worth-of-oracle-stock-.html",
        "summary": "Oracle founder Larry Ellison has canceled his plan to sell up to $7.5 billion worth of stock in the software company.",
        "published": "13 Sep 2026 00:14 WIB",
        "sentiment": "Bullish",
        "score": 0.341,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Trump melihat perang Iran berakhir segera setelah pemilu paruh waktu, memperkirakan harga minyak akan turun tajam",
        "url": "https://www.cnbc.com/2026/09/12/trump-sees-iran-war-ending-very-soon-oil-prices-then-falling.html",
        "summary": "Oil prices retreated on Friday on hopes of a resumptions in negotiations, but notched sharp weekly gains after soaring above $100 a barrel.",
        "published": "13 Sep 2026 00:22 WIB",
        "sentiment": "Bullish",
        "score": 0.292,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Dunia Trump yang mengutamakan Amerika mendorong negara-negara lain untuk melakukan lindung nilai terhadap taruhan mereka",
        "url": "https://www.cnbc.com/2026/09/12/brics-summit-xi-putin-modi-trump.html",
        "summary": "Xi, Putin and Modi meet in New Delhi as U.S. tariffs, sanctions and the Iran war test whether BRICS members can find more common ground.",
        "published": "12 Sep 2026 20:24 WIB",
        "sentiment": "Bearish",
        "score": -0.759,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Inflasi kembali melampaui pertumbuhan upah, sehingga mengurangi gaji warga Amerika",
        "url": "https://www.cnbc.com/2026/09/12/inflation-is-outpacing-wage-growth-again-squeezing-americans-paychecks.html",
        "summary": "In August, consumer prices rose 3.4% over the past year while wages increased just 3.1%.",
        "published": "12 Sep 2026 19:49 WIB",
        "sentiment": "Bullish",
        "score": 0.732,
        "emoji": "🟢",
        "impact": "medium"
      }
    ]
  },
  "fj_live": {
    "generated": "13 Sep 2026 22:02 WIB",
    "summary": {
      "total": 11,
      "bullish": 2,
      "bearish": 3,
      "netral": 6,
      "avg_score": -0.0903,
      "overall": "Bearish"
    },
    "items": [
      {
        "source": "Google News Forex",
        "title": "Lonjakan inflasi membuat suku bunga kembali menjadi fokus saat para pembuat kebijakan bertemu di Jepang, AS, dan Inggris - theguardian.com",
        "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxPSjlxdEJuc05uQjJBcXJsU2cycGktTGlVMDVrVTdZcTRlMDRDNU9lWmhUaW9CTFB6cjhfdWpOaDkyaWhjeWp3amV1MkJmQXJkUjU1RERfWWY5T2hyNXhLX0puWHdFeFdCRHRRY0praXZPSjZGRmRQNDVuMUtBWjh3ME85endheVBtTXpxTjhXcXpaWER0X2dBTzFNeHd5bWtqdlE?oc=5",
        "summary": "Surging inflation puts interest rates back in focus as policymakers meet in Japan, US and UK theguardian.com",
        "published": "13 Sep 2026 20:56 WIB",
        "sentiment": "Bullish",
        "score": 0.459,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Trump mengenai keputusan Fed minggu depan: mengatakan AS harus menetapkan suku bunga terendah secara global",
        "url": "https://www.financialjuice.com/News/9760856/Trump-on-Fed-decision-next-week-says-US-should-have-lowest-rates-globally.aspx?xy=rss",
        "summary": "",
        "published": "13 Sep 2026 20:10 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Harga hampir semua barang di meja makan Anda langsung naik — dan Wall Street mulai memperhatikannya",
        "url": "https://www.marketwatch.com/story/the-price-of-almost-everything-on-your-dinner-table-is-climbing-at-once-and-wall-street-is-taking-notice-9623d1fc?mod=mw_rss_topstories",
        "summary": "Rising crop prices are making the current inflation problem bigger than just oil and the Iran war.",
        "published": "13 Sep 2026 20:00 WIB",
        "sentiment": "Bearish",
        "score": -0.845,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Setelah Lonjakan Minyak dan Perang, Negara Berkembang Tidak Terpengaruh oleh Risiko Fed",
        "url": "https://www.bloomberg.com/news/articles/2026-09-13/after-oil-surge-and-war-emerging-markets-unfazed-by-fed-risk",
        "summary": "Emerging markets have defied war, $100 oil and rising Treasury yields this year. And despite worries of a US interest-rate hike, investors see reasons for this year’s rally to keep going.",
        "published": "13 Sep 2026 19:52 WIB",
        "sentiment": "Bearish",
        "score": -0.115,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "ETF ekuitas AS melihat arus keluar sebesar $4,5 miliar karena para pedagang memperkirakan kenaikan suku bunga Fed",
        "url": "https://www.investing.com/news/stock-market-news/us-equity-etfs-see-outflows-of-45-billion-as-traders-price-in-fed-rate-hike-4898731",
        "summary": "",
        "published": "13 Sep 2026 19:37 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Menteri Perekonomian Italia: penting bagi Italia untuk menjaga keuangan publik ketika ECB menaikkan suku bunga",
        "url": "https://www.financialjuice.com/News/9760785/Italy-economy-minister-crucial-for-Italy-to-maintain-public-finances-as-ECB-hikes-interest-rates.aspx?xy=rss",
        "summary": "",
        "published": "13 Sep 2026 15:24 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "ECB merilis wawancara media dengan Quest-France",
        "url": "https://www.financialjuice.com/News/9760629/ECB-releases-media-interview-with-Quest-France.aspx?xy=rss",
        "summary": "",
        "published": "13 Sep 2026 03:05 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Kerugian ekonomi akibat blokade dan penghancuran pelabuhan Ukraina sekitar 1,5 poin persentase PDB tahun ini: menteri",
        "url": "https://www.financialjuice.com/News/9760581/Economic-costs-from-Ukraines-seaports-blockade-and-destruction-about-15-percentage-points-of-GDP-this-year-minister.aspx?xy=rss",
        "summary": "",
        "published": "13 Sep 2026 00:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "CNBC Forex",
        "title": "Perjalanan pulang-pergi minyak kembali ke $100. Mengapa Tiongkok bisa menentukan apa yang terjadi selanjutnya",
        "url": "https://www.cnbc.com/2026/09/12/oils-roundtrip-back-to-100-why-china-could-determine-what-happens-next.html",
        "summary": "The U.S. crude oil price on Thursday topped $102 per barrel for its highest close since May.",
        "published": "12 Sep 2026 19:40 WIB",
        "sentiment": "Bearish",
        "score": -0.572,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Economy",
        "title": "Meloni melihat pertumbuhan Italia pada tahun 2026 sebesar 1%, menyamai zona euro",
        "url": "https://www.investing.com/news/economic-indicators/meloni-sees-italy-2026-growth-at-1-matching-euro-zone-4898632",
        "summary": "",
        "published": "12 Sep 2026 14:30 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Google News Forex",
        "title": "Ringgit diperkirakan berada di antara RM4,06 dan RM4,08 terhadap dolar AS minggu depan - Malay Mail",
        "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxONFQwb21EZGN4ZW9kcmNYZGZJekp3ZFQ3UEliUmVEd2RveVktai1RZHNTVHJjckJfNW80UkRZQ1RkVUlMNmxyVzlfZHZfdkJ4WlZTM0V0bW9jS2hNQmx0MUZIWHF2VENQdzNTUVBlalkzRV9LX2hreV8zRE10TDljNlUtdjF5U25BQUplazV6ZlBlcEk2REE5SDB4dU9LRkE0RjVzMi1KUjZ2RFZNZ1EwMnI2TmpISG1zZ1p1OG9yUE1xd2pvMm9ZMF9LMm_SAdIBQVVfeXFMT0F0Rk12SllldTBHRTFHRDBNT1BEMDAyNTYzYUJINU9EVklsRlJKd0NIUXJiT24xZlN1aHl1VUNwNm94clE2MkRpTUVTV2NFSHF3S3RFWVBtZHgxTFJsdWNYQmlUSVZsNDNmS0QtWVItMW01S2d0bndlTEI3Z0JWc2lHUWdmTjZ3bEdfdGp0MDJhUGhha1dHaS1TZHZpYmlTYzR5LVNDbGxwSjg3c3dFNnRMYnNlWnBMblBNcUVSbUxNM1VzRWhyaGtiMWVRYlBwTVRR?oc=5",
        "summary": "Ringgit expected to hover between RM4.06 and RM4.08 against US dollar next week Malay Mail",
        "published": "12 Sep 2026 10:21 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      }
    ]
  },
  "rekomendasi": {
    "generated": "13 Sep 2026 22:02 WIB",
    "pairs": [
      {
        "label": "GBP/AUD",
        "score": 43,
        "direction": "BUY",
        "rsi": 60.7,
        "last_close": "1.88674",
        "smma7": "1.88524",
        "ema9": "1.88544",
        "atr14": "0.00181",
        "bars_since_cross": 3,
        "cross_label": "3 candle lalu",
        "freshness_score": 35,
        "separation_score": 3,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/NZD",
        "score": 37,
        "direction": "BUY",
        "rsi": 51.6,
        "last_close": "1.99434",
        "smma7": "1.99387",
        "ema9": "1.99394",
        "atr14": "0.00227",
        "bars_since_cross": 3,
        "cross_label": "3 candle lalu",
        "freshness_score": 35,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/USD",
        "score": 31,
        "direction": "SELL",
        "rsi": 44.3,
        "last_close": "0.58163",
        "smma7": "0.58186",
        "ema9": "0.58178",
        "atr14": "0.00063",
        "bars_since_cross": 5,
        "cross_label": "5 candle lalu",
        "freshness_score": 25,
        "separation_score": 3,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.121,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.121,
          "base_count": 0,
          "quote_count": 5,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "CHF/JPY",
        "score": 29,
        "direction": "SELL",
        "rsi": 24.3,
        "last_close": "188.066",
        "smma7": "188.461",
        "ema9": "188.305",
        "atr14": "0.253",
        "bars_since_cross": 18,
        "cross_label": "18 candle lalu",
        "freshness_score": 0,
        "separation_score": 16,
        "rsi_score": 13,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/CHF",
        "score": 23,
        "direction": "BUY",
        "rsi": 52.9,
        "last_close": "0.58820",
        "smma7": "0.58828",
        "ema9": "0.58838",
        "atr14": "0.00125",
        "bars_since_cross": 6,
        "cross_label": "6 candle lalu",
        "freshness_score": 20,
        "separation_score": 2,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/JPY",
        "score": 20,
        "direction": "SELL",
        "rsi": 38.2,
        "last_close": "89.298",
        "smma7": "89.422",
        "ema9": "89.374",
        "atr14": "0.139",
        "bars_since_cross": 9,
        "cross_label": "9 candle lalu",
        "freshness_score": 5,
        "separation_score": 9,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CAD",
        "score": 20,
        "direction": "BUY",
        "rsi": 69.0,
        "last_close": "1.87633",
        "smma7": "1.87436",
        "ema9": "1.87502",
        "atr14": "0.00171",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 10,
        "rsi_score": 10,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/GBP",
        "score": 19,
        "direction": "SELL",
        "rsi": 33.6,
        "last_close": "0.85736",
        "smma7": "0.85782",
        "ema9": "0.85763",
        "atr14": "0.00045",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 11,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CHF",
        "score": 18,
        "direction": "BUY",
        "rsi": 66.3,
        "last_close": "1.10320",
        "smma7": "1.10271",
        "ema9": "1.10326",
        "atr14": "0.00134",
        "bars_since_cross": 38,
        "cross_label": "38 candle lalu",
        "freshness_score": 0,
        "separation_score": 10,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/JPY",
        "score": 18,
        "direction": "SELL",
        "rsi": 32.5,
        "last_close": "110.696",
        "smma7": "110.895",
        "ema9": "110.826",
        "atr14": "0.185",
        "bars_since_cross": 16,
        "cross_label": "16 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/USD",
        "score": 17,
        "direction": "BUY",
        "rsi": 55.3,
        "last_close": "1.35289",
        "smma7": "1.35232",
        "ema9": "1.35249",
        "atr14": "0.00099",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.121,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.121,
          "base_count": 0,
          "quote_count": 5,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/JPY",
        "score": 17,
        "direction": "SELL",
        "rsi": 35.0,
        "last_close": "178.142",
        "smma7": "178.341",
        "ema9": "178.256",
        "atr14": "0.237",
        "bars_since_cross": 16,
        "cross_label": "16 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CHF",
        "score": 17,
        "direction": "BUY",
        "rsi": 70.8,
        "last_close": "0.94673",
        "smma7": "0.94610",
        "ema9": "0.94641",
        "atr14": "0.00103",
        "bars_since_cross": 37,
        "cross_label": "37 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 10,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CHF",
        "score": 16,
        "direction": "BUY",
        "rsi": 65.7,
        "last_close": "0.81610",
        "smma7": "0.81553",
        "ema9": "0.81586",
        "atr14": "0.00097",
        "bars_since_cross": 37,
        "cross_label": "37 candle lalu",
        "freshness_score": 0,
        "separation_score": 8,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.121,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.121,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CAD",
        "score": 16,
        "direction": "BUY",
        "rsi": 70.1,
        "last_close": "1.38690",
        "smma7": "1.38610",
        "ema9": "1.38640",
        "atr14": "0.00137",
        "bars_since_cross": 56,
        "cross_label": "56 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 10,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.121,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.121,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/JPY",
        "score": 13,
        "direction": "SELL",
        "rsi": 37.0,
        "last_close": "110.117",
        "smma7": "110.262",
        "ema9": "110.222",
        "atr14": "0.152",
        "bars_since_cross": 33,
        "cross_label": "33 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/NZD",
        "score": 13,
        "direction": "BUY",
        "rsi": 50.5,
        "last_close": "1.23262",
        "smma7": "1.23269",
        "ema9": "1.23285",
        "atr14": "0.00137",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 3,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/JPY",
        "score": 12,
        "direction": "SELL",
        "rsi": 38.1,
        "last_close": "153.554",
        "smma7": "153.757",
        "ema9": "153.697",
        "atr14": "0.260",
        "bars_since_cross": 12,
        "cross_label": "12 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.121,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.121,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CHF",
        "score": 11,
        "direction": "BUY",
        "rsi": 63.2,
        "last_close": "0.47459",
        "smma7": "0.47437",
        "ema9": "0.47450",
        "atr14": "0.00072",
        "bars_since_cross": 19,
        "cross_label": "19 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 7,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/JPY",
        "score": 8,
        "direction": "SELL",
        "rsi": 42.1,
        "last_close": "207.771",
        "smma7": "207.884",
        "ema9": "207.832",
        "atr14": "0.292",
        "bars_since_cross": 16,
        "cross_label": "16 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/USD",
        "score": 7,
        "direction": "SELL",
        "rsi": 43.6,
        "last_close": "1.16023",
        "smma7": "1.16039",
        "ema9": "1.16027",
        "atr14": "0.00080",
        "bars_since_cross": 35,
        "cross_label": "35 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.121,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.121,
          "base_count": 2,
          "quote_count": 5,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CAD",
        "score": 7,
        "direction": "BUY",
        "rsi": 57.4,
        "last_close": "1.60850",
        "smma7": "1.60794",
        "ema9": "1.60813",
        "atr14": "0.00160",
        "bars_since_cross": 11,
        "cross_label": "11 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/AUD",
        "score": 4,
        "direction": "SELL",
        "rsi": 47.5,
        "last_close": "1.61710",
        "smma7": "1.61724",
        "ema9": "1.61701",
        "atr14": "0.00172",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CAD",
        "score": 3,
        "direction": "BUY",
        "rsi": 54.2,
        "last_close": "0.80631",
        "smma7": "0.80623",
        "ema9": "0.80628",
        "atr14": "0.00128",
        "bars_since_cross": 19,
        "cross_label": "19 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/CAD",
        "score": 3,
        "direction": "BUY",
        "rsi": 50.8,
        "last_close": "0.99359",
        "smma7": "0.99399",
        "ema9": "0.99417",
        "atr14": "0.00179",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/USD",
        "score": 1,
        "direction": "BUY",
        "rsi": 45.6,
        "last_close": "0.71726",
        "smma7": "0.71748",
        "ema9": "0.71749",
        "atr14": "0.00066",
        "bars_since_cross": 11,
        "cross_label": "11 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.121,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.121,
          "base_count": 0,
          "quote_count": 5,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      }
    ],
    "total": 26
  }
};
