// Diperbarui: 04 Oct 2026 22:01 WIB
window.FK_DATA = {
  "generated": "04 Oct 2026 22:01 WIB",
  "kalender": {
    "generated": "04 Oct 2026 22:01 WIB",
    "events": []
  },
  "sentimen": {
    "generated": "04 Oct 2026 22:01 WIB",
    "summary": {
      "total": 56,
      "bullish": 23,
      "bearish": 25,
      "netral": 8,
      "avg_score": -0.0901,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "EUR",
          "sentiment": "Bearish",
          "score": -0.429,
          "count": 4
        },
        {
          "currency": "USD",
          "sentiment": "Bullish",
          "score": 0.653,
          "count": 2
        }
      ]
    },
    "items": [
      {
        "source": "ForexLive",
        "title": "S&P 500 technical analysis as week ended less than 1% lower than ATH just shy of 7850",
        "url": "https://investinglive.com/stocks/s-p-500-technical-analysis-as-week-ended-less-than-1-lower-than-ath-just-shy-of-7850/",
        "summary": "S&P 500 futures test whether the channel breakout can hold S&P 500 E-mini futures have improved after breaking out of the broader descending channel that contained much of the August-to-September pullback. But the four-hour chart is now at the more interesting stage: not whether price can briefly ri",
        "published": "04 Oct 2026 00:36 WIB",
        "sentiment": "Bullish",
        "score": 0.741,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "ForexLive",
        "title": "Intel stock outlook: A failed rebound raises questions for traders and shareholders",
        "url": "https://investinglive.com/stocks/intel-stock-outlook-a-failed-rebound-raises-questions-for-traders-and-shareholders/",
        "summary": "Intel stock’s September recovery remains partly intact, but Friday’s failed rebound raises a warning INTC weakened while the broader technology benchmark strengthened. For traders considering an entry and shareholders weighing partial profit-taking, the next question is whether nearby support holds ",
        "published": "03 Oct 2026 13:24 WIB",
        "sentiment": "Bearish",
        "score": -0.631,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Saudi Arabia stocks higher at close of trade; Tadawul All Share up 1.09%",
        "url": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-higher-at-close-of-trade-tadawul-all-share-up-109-4930934",
        "summary": "",
        "published": "04 Oct 2026 19:45 WIB",
        "sentiment": "Bullish",
        "score": 0.296,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Why has e-Commerce accelerated and who is gaining?",
        "url": "https://www.investing.com/news/stock-market-news/why-has-ecommerce-accelerated-and-who-is-gaining-4930926",
        "summary": "",
        "published": "04 Oct 2026 18:07 WIB",
        "sentiment": "Bullish",
        "score": 0.501,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "US Supreme Court to kick off term with bid by Big Oil to toss climate suits",
        "url": "https://www.investing.com/news/stock-market-news/us-supreme-court-to-kick-off-term-with-bid-by-big-oil-to-toss-climate-suits-4930919",
        "summary": "",
        "published": "04 Oct 2026 17:36 WIB",
        "sentiment": "Bullish",
        "score": 0.557,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Like a ’vertical roller coaster’: Simulating flight FZ1073’s sudden plunge",
        "url": "https://www.investing.com/news/stock-market-news/like-a-vertical-roller-coaster-simulating-flight-fz1073s-sudden-plunge-4930921",
        "summary": "",
        "published": "04 Oct 2026 17:07 WIB",
        "sentiment": "Bullish",
        "score": 0.361,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Street calls of the week: Sep 28 to Oct 2, 2026",
        "url": "https://www.investing.com/news/stock-market-news/street-calls-of-the-week-sep-28-to-oct-2-2026-93CH-4930886",
        "summary": "",
        "published": "04 Oct 2026 17:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Citi explains why home improvement stocks are lagging in 2026",
        "url": "https://www.investing.com/news/stock-market-news/citi-explains-why-home-improvement-stocks-are-lagging-in-2026-4930904",
        "summary": "",
        "published": "04 Oct 2026 11:37 WIB",
        "sentiment": "Bullish",
        "score": 0.226,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "AI deal boom drives Hong Kong fundraising to record summer - Bloomberg",
        "url": "https://www.investing.com/news/stock-market-news/ai-deal-boom-drives-hong-kong-fundraising-to-record-summer--bloomberg-4930898",
        "summary": "",
        "published": "04 Oct 2026 09:12 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "How Muse Stacks up Vs. OpenAI Dots",
        "url": "https://www.investing.com/news/stock-market-news/how-muse-stacks-up-vs-openai-dots-4930890",
        "summary": "",
        "published": "04 Oct 2026 05:24 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Nestle India product sample declared unsafe by food regulator",
        "url": "https://www.investing.com/news/stock-market-news/nestle-india-product-sample-declared-unsafe-by-food-regulator-93CH-4930889",
        "summary": "",
        "published": "04 Oct 2026 04:52 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Russia stocks lower at close of trade; MOEX Russia Index unchanged",
        "url": "https://www.investing.com/news/stock-market-news/russia-stocks-lower-at-close-of-trade-moex-russia-index-unchanged-4930887",
        "summary": "",
        "published": "04 Oct 2026 04:20 WIB",
        "sentiment": "Bearish",
        "score": -0.296,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Reuters Currencies",
        "title": "Revolut's rise to become Europe's $115 billion big bank rival - Reuters",
        "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxQWDBEcXY1UUtrRGxIaE9neHYxeDlTWDNYaVlWdlp2UUhxSGtUV2RVZlR4Q25UUTlDTTR0QXlLYlVNZ1lMNEJfQkVmZnVtcFNaVW5mZE42d21uV1BZZzRESkxvVkxoM19FNkhoVThRWXYtUGR1eGZ6VmYtUHNrTWs5eXZfV1kxZ3ZnSHR2UWtmQWd5YVltQlNseWs0RGhXeVItVGVwQXNKbXpZVG9G?oc=5",
        "summary": "Revolut's rise to become Europe's $115 billion big bank rival Reuters",
        "published": "04 Oct 2026 20:56 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Jobs Slow but Inflation Keeps Fed on Alert",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/jobs-slow-but-inflation-keeps-fed-on-alert-video",
        "summary": "Bloomberg Intelligence Chief US Interest Rate Strategist Ira Jersey tells Bloomberg This Weekend that softer September jobs data give the Federal Reserve room to hold rates steady in October, but persistent inflation could still lead policymakers to raise rates again in December and early next year.",
        "published": "04 Oct 2026 20:04 WIB",
        "sentiment": "Bullish",
        "score": 1.0,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Wall Street’s AI Party Is on Edge as Soaring Yields Raise Risks",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/wall-street-s-ai-party-is-on-edge-as-soaring-yields-raise-risks",
        "summary": "Wall Street’s artificial intelligence fixation is so strong that it’s overwhelming all risks, including soaring interest rates, as investors continue to plow money into the market’s largest technology stocks and push equity indexes toward record highs.",
        "published": "04 Oct 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.79,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Markets Brace for Sharp Swings No Matter Result of Brazil Vote",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/markets-brace-for-sharp-swings-no-matter-result-of-brazil-vote",
        "summary": "Investors are expecting sharp swings in Brazilian markets in the aftermath of Sunday’s elections no matter the outcome, with assets to adjust quickly as the neck-and-neck presidential race prevented traders from taking too strong a view in the lead up to the vote.",
        "published": "04 Oct 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.686,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "EM Investors Shrug Off Quarter’s Pullback, Double Down on Carry Trades",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/em-investors-shrug-off-quarter-s-pullback-double-down-on-carry-trades",
        "summary": "Investors are sticking with emerging-market carry trades, even after a rare quarterly loss, betting the strategy will be able to weather Treasury yields at multi-decade highs",
        "published": "04 Oct 2026 19:30 WIB",
        "sentiment": "Bearish",
        "score": -0.208,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "G7 Fuel Release Offers Temporary Price Relief",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/g7-fuel-release-offers-temporary-price-relief-video",
        "summary": "Bloomberg Mideast Energy Correspondent Anthony Di Paola tells Bloomberg This Weekend that the G7’s 100 million-barrel emergency release is already pushing fuel prices lower but is likely to provide only temporary relief as refinery constraints and Middle East disruptions keep diesel supplies tight. ",
        "published": "04 Oct 2026 19:07 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Can America Break China’s Grip on Rare Earths?",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/can-america-break-china-s-grip-on-rare-earths-video",
        "summary": "China spent decades building a dominant position across rare-earth mining, processing and magnet manufacturing, leaving the US dependent on a foreign supply chain for materials essential to everything from vehicles and wind turbines to electronics and defense systems. MP Materials is now trying to r",
        "published": "04 Oct 2026 19:03 WIB",
        "sentiment": "Bullish",
        "score": 0.064,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "OPEC+ Agrees to Keep Oil Output Targets Steady in November",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/opec-has-deal-outline-for-steady-november-quotas-delegates-say",
        "summary": "Major OPEC+ nations agreed to keep oil production quotas unchanged next month, as conflict in the Middle East continues to shutter swaths of the group’s output.",
        "published": "04 Oct 2026 14:49 WIB",
        "sentiment": "Bullish",
        "score": 0.138,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Whispers of Contagion Risk Are Returning to Europe’s Bond Market",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/whispers-of-contagion-risk-are-returning-to-europe-s-bond-market",
        "summary": "Traders are on the alert for signs of contagion in Europe’s government bond market after a selloff triggered memories of the region’s debt crisis 15 years ago.",
        "published": "04 Oct 2026 18:15 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Iraq Shifts Oil Strategy by Arranging Tanker to Move Past Hormuz",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/iraq-shifts-oil-strategy-by-arranging-tanker-to-move-past-hormuz",
        "summary": "Iraq’s state tanker company arranged a very large crude carrier to transport 2 million barrels beyond the Strait of Hormuz, marking a move toward offering oil outside the Persian Gulf.",
        "published": "04 Oct 2026 17:09 WIB",
        "sentiment": "Bearish",
        "score": -0.69,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Ethiopia Retakes Tigray Airport as Northern Rebels Retreat",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/ethiopia-recaptures-tigray-airport-as-northern-rebels-retreat",
        "summary": "Ethiopian forces seized control of the airport and other parts of Mekelle, the capital of the northern Tigray region, as leaders of the Tigray People’s Liberation Front retreated from the city, a major turning point in the renewed conflict.",
        "published": "04 Oct 2026 14:47 WIB",
        "sentiment": "Bearish",
        "score": -0.398,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Lula, Bolsonaro in Tight Race as Brazil Prepares to Vote",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/lula-bolsonaro-in-dead-heat-as-brazil-prepares-to-vote",
        "summary": "President Luiz Inácio Lula da Silva and right-wing challenger Flávio Bolsonaro remain locked in a tight race as Brazil prepares to vote in Sunday’s election, according to three new polls.",
        "published": "04 Oct 2026 05:35 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Mexico Says Its Troops Sent to Border in Conjunction With US",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/mexico-says-its-troops-sent-to-border-in-conjunction-with-us",
        "summary": "The US and Mexico have jointly deployed military personnel in a border area in Texas as part of “mirror operations,” the Mexican government said Saturday.",
        "published": "04 Oct 2026 06:24 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "UAE Probe Labels FlyDubai Cockpit Ax Attack a Terrorist Act",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/uae-says-flydubai-co-pilot-planned-terrorist-operation",
        "summary": "A United Arab Emirates investigation of the near-catastrophic FlyDubai flight said the co-pilot attempted “to carry out a terrorist act” as more details emerged about what happened in the cockpit.",
        "published": "03 Oct 2026 14:06 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Kyiv bridge hit in further Russian drone attack as German chancellor makes surprise visit",
        "url": "https://www.bbc.co.uk/news/articles/ckreyjzzzywqo?at_medium=RSS&at_campaign=rss",
        "summary": "Footage shows a drone hitting the Pivnichyi (Northern) Bridge as vehicles move across it, creating a large fireball.",
        "published": "04 Oct 2026 19:09 WIB",
        "sentiment": "Netral",
        "score": -0.028,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Yemen announces military campaign to reclaim land from Iran-backed Houthis",
        "url": "https://www.bbc.co.uk/news/articles/cx8dzj9vpp01o?at_medium=RSS&at_campaign=rss",
        "summary": "The Yemeni president's announcement comes amid an exchange of strikes between the Houthis and the Saudi-led coalition.",
        "published": "04 Oct 2026 21:24 WIB",
        "sentiment": "Bearish",
        "score": -0.361,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "US Marine arrested over murder of woman in Okinawa, Japan",
        "url": "https://www.bbc.co.uk/news/articles/cme3xw4yy28do?at_medium=RSS&at_campaign=rss",
        "summary": "Japan's government lodged a formal protest with the US, demanding that military officials take action.",
        "published": "04 Oct 2026 21:36 WIB",
        "sentiment": "Bearish",
        "score": -0.893,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "What to know about Brazil's election pitting Lula against Flávio Bolsonaro",
        "url": "https://www.bbc.co.uk/news/articles/c6wyz0r2n0djo?at_medium=RSS&at_campaign=rss",
        "summary": "Polls suggest the election will be a closely run contest between the left-wing incumbent and his right-wing rival.",
        "published": "04 Oct 2026 18:03 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Why Canada is preparing for a (long shot) US invasion",
        "url": "https://www.bbc.co.uk/news/articles/c9m2mjj3yvg4o?at_medium=RSS&at_campaign=rss",
        "summary": "Prime Minister Mark Carney has said the military is running scenarios in the unlikely case the US invades Canada.",
        "published": "04 Oct 2026 06:30 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Why has Brazil accused the US of election interference?",
        "url": "https://www.bbc.co.uk/news/videos/c3eweld0nddeo?at_medium=RSS&at_campaign=rss",
        "summary": "The Latin American country will vote for its next president, as Lula da Silva and Bolsonaro clash over sovereignty, security and ties with Washington.",
        "published": "03 Oct 2026 20:52 WIB",
        "sentiment": "Bullish",
        "score": 0.052,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Will Spain's housing crisis lead to a snap election?",
        "url": "https://www.bbc.co.uk/news/videos/cmgj9vz2zxelo?at_medium=RSS&at_campaign=rss",
        "summary": "The BBC's Guy Hedgecoe is in Madrid, where a series of marches have been scheduled, after Spain's Congress rejected measures aimed at tackling the country's housing crisis.",
        "published": "03 Oct 2026 19:26 WIB",
        "sentiment": "Bearish",
        "score": -0.99,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "BBC Business",
        "title": "G7 to release millions of barrels of oil and diesel after Trump threat",
        "url": "https://www.bbc.co.uk/news/articles/ck87zg8jnwngo?at_medium=RSS&at_campaign=rss",
        "summary": "The co-ordinated release is aimed at heading off further price spikes and avoiding a ban on US diesel exports.",
        "published": "03 Oct 2026 11:38 WIB",
        "sentiment": "Bearish",
        "score": -0.856,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "British Museum announces changes to ease Bayeux Tapestry queues",
        "url": "https://www.bbc.co.uk/news/articles/cwvgrle6dx2lo?at_medium=RSS&at_campaign=rss",
        "summary": "Measures include extended opening hours, as well as an audio guide and additional seating for visitors.",
        "published": "04 Oct 2026 20:45 WIB",
        "sentiment": "Bullish",
        "score": 0.557,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Why Canada is preparing for an unlikely US invasion",
        "url": "https://www.bbc.co.uk/news/articles/c9m2mjj3yvg4o?at_medium=RSS&at_campaign=rss",
        "summary": "Prime Minister Mark Carney has said the military is running scenarios in the unlikely case the US invades Canada.",
        "published": "04 Oct 2026 06:30 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Dodik declared Bosnia ‘dead’. Irrelevant rhetoric or serious threat?",
        "url": "https://www.aljazeera.com/news/2026/10/4/dodik-declared-bosnia-dead-irrelevant-rhetoric-or-serious-threat?traffic_source=rss",
        "summary": "Bosnian Serb leader's controversial comments ahead of Bosnia and Herzegovina's high-stakes elections.",
        "published": "04 Oct 2026 21:21 WIB",
        "sentiment": "Bearish",
        "score": -0.67,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "How was Flydubai co-pilot cleared despite being deemed a security risk?",
        "url": "https://www.aljazeera.com/news/2026/10/4/how-was-flydubai-co-pilot-cleared-despite-being-deemed-a-security-risk?traffic_source=rss",
        "summary": "Aviation security protocols under scrutiny after co-pilot accused of attempted axe attack aboard Flydubai flight.",
        "published": "04 Oct 2026 20:42 WIB",
        "sentiment": "Bearish",
        "score": -0.521,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "What are the five questions being asked regarding the Flydubai attack?",
        "url": "https://www.aljazeera.com/news/2026/10/4/what-are-the-five-questions-being-asked-regarding-the-flydubai-attack?traffic_source=rss",
        "summary": "As investigations are conducted, official versions of the incident have come under scrutiny.",
        "published": "04 Oct 2026 20:11 WIB",
        "sentiment": "Bearish",
        "score": -0.557,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Did the fall of al-Andalus reshape Europe forever?",
        "url": "https://www.aljazeera.com/video/deja-vu-2/2026/10/4/did-the-fall-of-al-andalus-reshape-europe-forever?traffic_source=rss",
        "summary": "Deja Vu traces Europe’s Muslim history from Al-Andalus to today. Why are Muslims still treated as outsiders?",
        "published": "04 Oct 2026 20:01 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Yemen’s leader announces military operation to retake Houthi-held territory",
        "url": "https://www.aljazeera.com/news/2026/10/4/yemens-leader-announces-military-operation-to-retake-houthi-held-territory?traffic_source=rss",
        "summary": "Rashad al-Alimi says the campaign aims to restore state authority throughout Yemen.",
        "published": "04 Oct 2026 19:48 WIB",
        "sentiment": "Bullish",
        "score": 0.361,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Brazil votes in deeply polarised election pitting Lula against Bolsonaro",
        "url": "https://www.aljazeera.com/news/2026/10/4/brazil-votes-in-deeply-polarised-election-pitting-lula-against-bolsonaro?traffic_source=rss",
        "summary": "Close race expected as left-wing leader Lula seeks fourth nonconsecutive term against right-wing Flavio Bolsonaro.",
        "published": "04 Oct 2026 18:15 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "Iran says Hormuz to remain closed until US meets conditions",
        "url": "https://www.aljazeera.com/news/2026/10/4/iran-says-strait-of-hormuz-to-remain-closed-until-us-meets-conditions?traffic_source=rss",
        "summary": "Tehran says reopening Strait of Hormuz has been its main goal, while the US continues to focus on nuclear talks.",
        "published": "04 Oct 2026 18:11 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Ethiopian government forces seize Tigray capital Mekelle as TPLF withdraws",
        "url": "https://www.aljazeera.com/news/2026/10/4/government-forces-seize-capital-of-ethiopias-tigray-region-from-rebels?traffic_source=rss",
        "summary": "Federal troops and allied fighters seen in control of the city after capturing main regional airport.",
        "published": "04 Oct 2026 18:05 WIB",
        "sentiment": "Bearish",
        "score": -0.052,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Russia’s nuclear plants are ageing. Who will pay to dismantle them?",
        "url": "https://www.aljazeera.com/opinions/2026/10/4/russias-nuclear-plants-are-ageing-who-will-pay-to-dismantle-them?traffic_source=rss",
        "summary": "Moscow faces a huge decommissioning bill at home even as it expands its nuclear industry abroad.",
        "published": "04 Oct 2026 17:44 WIB",
        "sentiment": "Bullish",
        "score": 0.238,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Netanyahu’s fight to own the election narrative",
        "url": "https://www.aljazeera.com/video/the-listening-post/2026/10/4/netanyahus-fight-to-own-the-election-narrative?traffic_source=rss",
        "summary": "What did Netanyahu know about October 7 before it happened?",
        "published": "04 Oct 2026 17:05 WIB",
        "sentiment": "Bearish",
        "score": -0.382,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "Brazil elections live: Lula faces Bolsonaro in close presidential race",
        "url": "https://www.aljazeera.com/news/liveblog/2026/10/4/brazil-elections-live-voters-head-to-polls-for-close-presidential-race?traffic_source=rss",
        "summary": "Voting is underway in Brazil as Lula seeks a historic fourth term, facing a strong challenge from Flavio Bolsonaro.",
        "published": "04 Oct 2026 17:00 WIB",
        "sentiment": "Bullish",
        "score": 0.637,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "MarketWatch",
        "title": "Fed minutes coming this week could give markets important clues about future rate hikes",
        "url": "https://www.marketwatch.com/story/fed-minutes-coming-this-week-could-give-markets-important-clues-about-future-rate-hikes-31bfba5b?mod=mw_rss_topstories",
        "summary": "Minutes from the September meeting may provide extra context, as the real fed-funds rate is now surprisingly low.",
        "published": "04 Oct 2026 19:00 WIB",
        "sentiment": "Bullish",
        "score": 0.306,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Falling wages, soaring energy prices and inflation: It’s beginning to look a lot like the 1970s",
        "url": "https://www.marketwatch.com/story/falling-wages-soaring-energy-prices-and-inflation-its-beginning-to-look-a-lot-like-the-1970s-d645cbca?mod=mw_rss_topstories",
        "summary": "Is it time to dust off the financial playbook from that dismal decade?",
        "published": "04 Oct 2026 06:58 WIB",
        "sentiment": "Bearish",
        "score": -0.33,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "A tough job market is pushing more young Americans to make a big bet: on themselves",
        "url": "https://www.marketwatch.com/story/a-tough-job-market-is-pushing-more-young-americans-to-make-a-big-bet-on-themselves-1aaddeca?mod=mw_rss_topstories",
        "summary": "There has been a rise in entrepreneurship among young Americans as the entry-level labor market has become tougher to join.",
        "published": "04 Oct 2026 00:24 WIB",
        "sentiment": "Bullish",
        "score": 0.34,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "CNBC Forex",
        "title": "Lula or Bolsonaro: Wall Street braces for two wildly different results in Brazil election",
        "url": "https://www.cnbc.com/2026/10/03/lula-or-bolsonaro-wall-street-braces-for-two-wildly-different-results-in-brazil-election.html",
        "summary": "With the first round of Brazil's presidential election taking place Sunday, Wall Street is gearing up with starkly different market predictions.",
        "published": "03 Oct 2026 20:12 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "CNBC Economy",
        "title": "High-tech vehicles are driving up auto repair costs for shops and consumers",
        "url": "https://www.cnbc.com/2026/10/03/vehicle-repair-costs.html",
        "summary": "Investments in ADAS calibration equipment, computers and software subscriptions can drive up the cost of even a windshield replacement or an oil change.",
        "published": "03 Oct 2026 19:00 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "More tankers struck in the Middle East as Iran reiterates conditions for reopening the Strait of Hormuz",
        "url": "https://www.cnbc.com/2026/10/04/more-tankers-struck-in-gulf-waters-as-iran-reiterates-conditions.html",
        "summary": "Tehran's conditions include a halt to U.S. \"acts of aggression,\" an end to the naval blockade and economic warfare, and the release of Iranian assets.",
        "published": "04 Oct 2026 19:35 WIB",
        "sentiment": "Bearish",
        "score": -0.69,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Ukraine’s surprise robot offensive exposes a vulnerability in Putin’s war machine",
        "url": "https://www.cnbc.com/2026/10/04/russia-ukraine-war-putin-zelenskyy-donbas-lyman.html",
        "summary": "Experts say the offensive is not a decisive breakthrough, but demonstrates how Ukraine’s expanding use of robotic systems is reshaping frontline warfare.",
        "published": "04 Oct 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.909,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "FlyDubai plane attack by co-pilot was an attempted 'terrorist' act, UAE says",
        "url": "https://www.cnbc.com/2026/10/03/flydubai-co-pilot-attacked-pilot-with-axe-uae-says.html",
        "summary": "The FlyDubai co-pilot attacked the pilot inside the cockpit with a crash axe and attempted to take control of the aircraft, the UAE prosecutor general said.",
        "published": "03 Oct 2026 19:34 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "America’s data center fight is a preview of what's to come for the rest of the world",
        "url": "https://www.cnbc.com/2026/10/03/data-center-backlash-europe-asia-africa.html",
        "summary": "America’s fight over data centers is going global. Communities across Europe and Asia are pushing back over the rising costs of the AI infrastructure boom.",
        "published": "03 Oct 2026 19:39 WIB",
        "sentiment": "Bearish",
        "score": -0.637,
        "emoji": "🔴",
        "impact": "low"
      }
    ]
  },
  "geopolitik": {
    "generated": "04 Oct 2026 22:01 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.057,
        "count": 14
      },
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.199,
        "count": 12
      },
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.223,
        "count": 10
      },
      {
        "pair": "GBP/USD",
        "direction": "Netral →",
        "score": -0.038,
        "count": 10
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.368,
        "count": 6
      },
      {
        "pair": "EUR",
        "direction": "Tekanan Turun ▼",
        "score": -0.364,
        "count": 2
      },
      {
        "pair": "GBP",
        "direction": "Tekanan Turun ▼",
        "score": -0.364,
        "count": 2
      },
      {
        "pair": "JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.364,
        "count": 2
      }
    ],
    "items": [
      {
        "source": "ForexLive",
        "title": "Intel stock outlook: A failed rebound raises questions for traders and shareholders",
        "url": "https://investinglive.com/stocks/intel-stock-outlook-a-failed-rebound-raises-questions-for-traders-and-shareholders/",
        "summary": "Intel stock’s September recovery remains partly intact, but Friday’s failed rebound raises a warning INTC weakened while the broader technology benchmark strengthened. For traders considering an entry and shareholders weighing partial profit-taking, the next question is whether nearby support holds ",
        "published": "03 Oct 2026 13:24 WIB",
        "sentiment": "Bearish",
        "score": -0.631,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Wall Street’s AI Party Is on Edge as Soaring Yields Raise Risks",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/wall-street-s-ai-party-is-on-edge-as-soaring-yields-raise-risks",
        "summary": "Wall Street’s artificial intelligence fixation is so strong that it’s overwhelming all risks, including soaring interest rates, as investors continue to plow money into the market’s largest technology stocks and push equity indexes toward record highs.",
        "published": "04 Oct 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.79,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Markets Brace for Sharp Swings No Matter Result of Brazil Vote",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/markets-brace-for-sharp-swings-no-matter-result-of-brazil-vote",
        "summary": "Investors are expecting sharp swings in Brazilian markets in the aftermath of Sunday’s elections no matter the outcome, with assets to adjust quickly as the neck-and-neck presidential race prevented traders from taking too strong a view in the lead up to the vote.",
        "published": "04 Oct 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.686,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "G7 Fuel Release Offers Temporary Price Relief",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/g7-fuel-release-offers-temporary-price-relief-video",
        "summary": "Bloomberg Mideast Energy Correspondent Anthony Di Paola tells Bloomberg This Weekend that the G7’s 100 million-barrel emergency release is already pushing fuel prices lower but is likely to provide only temporary relief as refinery constraints and Middle East disruptions keep diesel supplies tight. ",
        "published": "04 Oct 2026 19:07 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "OPEC+ Agrees to Keep Oil Output Targets Steady in November",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/opec-has-deal-outline-for-steady-november-quotas-delegates-say",
        "summary": "Major OPEC+ nations agreed to keep oil production quotas unchanged next month, as conflict in the Middle East continues to shutter swaths of the group’s output.",
        "published": "04 Oct 2026 14:49 WIB",
        "sentiment": "Bullish",
        "score": 0.138,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Whispers of Contagion Risk Are Returning to Europe’s Bond Market",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/whispers-of-contagion-risk-are-returning-to-europe-s-bond-market",
        "summary": "Traders are on the alert for signs of contagion in Europe’s government bond market after a selloff triggered memories of the region’s debt crisis 15 years ago.",
        "published": "04 Oct 2026 18:15 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Iraq Shifts Oil Strategy by Arranging Tanker to Move Past Hormuz",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/iraq-shifts-oil-strategy-by-arranging-tanker-to-move-past-hormuz",
        "summary": "Iraq’s state tanker company arranged a very large crude carrier to transport 2 million barrels beyond the Strait of Hormuz, marking a move toward offering oil outside the Persian Gulf.",
        "published": "04 Oct 2026 17:09 WIB",
        "sentiment": "Bearish",
        "score": -0.69,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Ethiopia Retakes Tigray Airport as Northern Rebels Retreat",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/ethiopia-recaptures-tigray-airport-as-northern-rebels-retreat",
        "summary": "Ethiopian forces seized control of the airport and other parts of Mekelle, the capital of the northern Tigray region, as leaders of the Tigray People’s Liberation Front retreated from the city, a major turning point in the renewed conflict.",
        "published": "04 Oct 2026 14:47 WIB",
        "sentiment": "Bearish",
        "score": -0.398,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Lula, Bolsonaro in Tight Race as Brazil Prepares to Vote",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/lula-bolsonaro-in-dead-heat-as-brazil-prepares-to-vote",
        "summary": "President Luiz Inácio Lula da Silva and right-wing challenger Flávio Bolsonaro remain locked in a tight race as Brazil prepares to vote in Sunday’s election, according to three new polls.",
        "published": "04 Oct 2026 05:35 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Mexico Says Its Troops Sent to Border in Conjunction With US",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/mexico-says-its-troops-sent-to-border-in-conjunction-with-us",
        "summary": "The US and Mexico have jointly deployed military personnel in a border area in Texas as part of “mirror operations,” the Mexican government said Saturday.",
        "published": "04 Oct 2026 06:24 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "UAE Probe Labels FlyDubai Cockpit Ax Attack a Terrorist Act",
        "url": "https://www.bloomberg.com/news/articles/2026-10-03/uae-says-flydubai-co-pilot-planned-terrorist-operation",
        "summary": "A United Arab Emirates investigation of the near-catastrophic FlyDubai flight said the co-pilot attempted “to carry out a terrorist act” as more details emerged about what happened in the cockpit.",
        "published": "03 Oct 2026 14:06 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Kyiv bridge hit in further Russian drone attack as German chancellor makes surprise visit",
        "url": "https://www.bbc.co.uk/news/articles/ckreyjzzzywqo?at_medium=RSS&at_campaign=rss",
        "summary": "Footage shows a drone hitting the Pivnichyi (Northern) Bridge as vehicles move across it, creating a large fireball.",
        "published": "04 Oct 2026 19:09 WIB",
        "sentiment": "Netral",
        "score": -0.028,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Yemen announces military campaign to reclaim land from Iran-backed Houthis",
        "url": "https://www.bbc.co.uk/news/articles/cx8dzj9vpp01o?at_medium=RSS&at_campaign=rss",
        "summary": "The Yemeni president's announcement comes amid an exchange of strikes between the Houthis and the Saudi-led coalition.",
        "published": "04 Oct 2026 21:24 WIB",
        "sentiment": "Bearish",
        "score": -0.361,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "US Marine arrested over murder of woman in Okinawa, Japan",
        "url": "https://www.bbc.co.uk/news/articles/cme3xw4yy28do?at_medium=RSS&at_campaign=rss",
        "summary": "Japan's government lodged a formal protest with the US, demanding that military officials take action.",
        "published": "04 Oct 2026 21:36 WIB",
        "sentiment": "Bearish",
        "score": -0.893,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "What to know about Brazil's election pitting Lula against Flávio Bolsonaro",
        "url": "https://www.bbc.co.uk/news/articles/c6wyz0r2n0djo?at_medium=RSS&at_campaign=rss",
        "summary": "Polls suggest the election will be a closely run contest between the left-wing incumbent and his right-wing rival.",
        "published": "04 Oct 2026 18:03 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Why Canada is preparing for a (long shot) US invasion",
        "url": "https://www.bbc.co.uk/news/articles/c9m2mjj3yvg4o?at_medium=RSS&at_campaign=rss",
        "summary": "Prime Minister Mark Carney has said the military is running scenarios in the unlikely case the US invades Canada.",
        "published": "04 Oct 2026 06:30 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Why has Brazil accused the US of election interference?",
        "url": "https://www.bbc.co.uk/news/videos/c3eweld0nddeo?at_medium=RSS&at_campaign=rss",
        "summary": "The Latin American country will vote for its next president, as Lula da Silva and Bolsonaro clash over sovereignty, security and ties with Washington.",
        "published": "03 Oct 2026 20:52 WIB",
        "sentiment": "Bullish",
        "score": 0.052,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Will Spain's housing crisis lead to a snap election?",
        "url": "https://www.bbc.co.uk/news/videos/cmgj9vz2zxelo?at_medium=RSS&at_campaign=rss",
        "summary": "The BBC's Guy Hedgecoe is in Madrid, where a series of marches have been scheduled, after Spain's Congress rejected measures aimed at tackling the country's housing crisis.",
        "published": "03 Oct 2026 19:26 WIB",
        "sentiment": "Bearish",
        "score": -0.99,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "BBC Business",
        "title": "G7 to release millions of barrels of oil and diesel after Trump threat",
        "url": "https://www.bbc.co.uk/news/articles/ck87zg8jnwngo?at_medium=RSS&at_campaign=rss",
        "summary": "The co-ordinated release is aimed at heading off further price spikes and avoiding a ban on US diesel exports.",
        "published": "03 Oct 2026 11:38 WIB",
        "sentiment": "Bearish",
        "score": -0.856,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Why Canada is preparing for an unlikely US invasion",
        "url": "https://www.bbc.co.uk/news/articles/c9m2mjj3yvg4o?at_medium=RSS&at_campaign=rss",
        "summary": "Prime Minister Mark Carney has said the military is running scenarios in the unlikely case the US invades Canada.",
        "published": "04 Oct 2026 06:30 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Dodik declared Bosnia ‘dead’. Irrelevant rhetoric or serious threat?",
        "url": "https://www.aljazeera.com/news/2026/10/4/dodik-declared-bosnia-dead-irrelevant-rhetoric-or-serious-threat?traffic_source=rss",
        "summary": "Bosnian Serb leader's controversial comments ahead of Bosnia and Herzegovina's high-stakes elections.",
        "published": "04 Oct 2026 21:21 WIB",
        "sentiment": "Bearish",
        "score": -0.67,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "How was Flydubai co-pilot cleared despite being deemed a security risk?",
        "url": "https://www.aljazeera.com/news/2026/10/4/how-was-flydubai-co-pilot-cleared-despite-being-deemed-a-security-risk?traffic_source=rss",
        "summary": "Aviation security protocols under scrutiny after co-pilot accused of attempted axe attack aboard Flydubai flight.",
        "published": "04 Oct 2026 20:42 WIB",
        "sentiment": "Bearish",
        "score": -0.521,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "What are the five questions being asked regarding the Flydubai attack?",
        "url": "https://www.aljazeera.com/news/2026/10/4/what-are-the-five-questions-being-asked-regarding-the-flydubai-attack?traffic_source=rss",
        "summary": "As investigations are conducted, official versions of the incident have come under scrutiny.",
        "published": "04 Oct 2026 20:11 WIB",
        "sentiment": "Bearish",
        "score": -0.557,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Yemen’s leader announces military operation to retake Houthi-held territory",
        "url": "https://www.aljazeera.com/news/2026/10/4/yemens-leader-announces-military-operation-to-retake-houthi-held-territory?traffic_source=rss",
        "summary": "Rashad al-Alimi says the campaign aims to restore state authority throughout Yemen.",
        "published": "04 Oct 2026 19:48 WIB",
        "sentiment": "Bullish",
        "score": 0.361,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Brazil votes in deeply polarised election pitting Lula against Bolsonaro",
        "url": "https://www.aljazeera.com/news/2026/10/4/brazil-votes-in-deeply-polarised-election-pitting-lula-against-bolsonaro?traffic_source=rss",
        "summary": "Close race expected as left-wing leader Lula seeks fourth nonconsecutive term against right-wing Flavio Bolsonaro.",
        "published": "04 Oct 2026 18:15 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "Iran says Hormuz to remain closed until US meets conditions",
        "url": "https://www.aljazeera.com/news/2026/10/4/iran-says-strait-of-hormuz-to-remain-closed-until-us-meets-conditions?traffic_source=rss",
        "summary": "Tehran says reopening Strait of Hormuz has been its main goal, while the US continues to focus on nuclear talks.",
        "published": "04 Oct 2026 18:11 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Ethiopian government forces seize Tigray capital Mekelle as TPLF withdraws",
        "url": "https://www.aljazeera.com/news/2026/10/4/government-forces-seize-capital-of-ethiopias-tigray-region-from-rebels?traffic_source=rss",
        "summary": "Federal troops and allied fighters seen in control of the city after capturing main regional airport.",
        "published": "04 Oct 2026 18:05 WIB",
        "sentiment": "Bearish",
        "score": -0.052,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Russia’s nuclear plants are ageing. Who will pay to dismantle them?",
        "url": "https://www.aljazeera.com/opinions/2026/10/4/russias-nuclear-plants-are-ageing-who-will-pay-to-dismantle-them?traffic_source=rss",
        "summary": "Moscow faces a huge decommissioning bill at home even as it expands its nuclear industry abroad.",
        "published": "04 Oct 2026 17:44 WIB",
        "sentiment": "Bullish",
        "score": 0.238,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Netanyahu’s fight to own the election narrative",
        "url": "https://www.aljazeera.com/video/the-listening-post/2026/10/4/netanyahus-fight-to-own-the-election-narrative?traffic_source=rss",
        "summary": "What did Netanyahu know about October 7 before it happened?",
        "published": "04 Oct 2026 17:05 WIB",
        "sentiment": "Bearish",
        "score": -0.382,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "Al Jazeera",
        "title": "Brazil elections live: Lula faces Bolsonaro in close presidential race",
        "url": "https://www.aljazeera.com/news/liveblog/2026/10/4/brazil-elections-live-voters-head-to-polls-for-close-presidential-race?traffic_source=rss",
        "summary": "Voting is underway in Brazil as Lula seeks a historic fourth term, facing a strong challenge from Flavio Bolsonaro.",
        "published": "04 Oct 2026 17:00 WIB",
        "sentiment": "Bullish",
        "score": 0.637,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "CNBC Forex",
        "title": "Lula or Bolsonaro: Wall Street braces for two wildly different results in Brazil election",
        "url": "https://www.cnbc.com/2026/10/03/lula-or-bolsonaro-wall-street-braces-for-two-wildly-different-results-in-brazil-election.html",
        "summary": "With the first round of Brazil's presidential election taking place Sunday, Wall Street is gearing up with starkly different market predictions.",
        "published": "03 Oct 2026 20:12 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "CNBC Economy",
        "title": "High-tech vehicles are driving up auto repair costs for shops and consumers",
        "url": "https://www.cnbc.com/2026/10/03/vehicle-repair-costs.html",
        "summary": "Investments in ADAS calibration equipment, computers and software subscriptions can drive up the cost of even a windshield replacement or an oil change.",
        "published": "03 Oct 2026 19:00 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "More tankers struck in the Middle East as Iran reiterates conditions for reopening the Strait of Hormuz",
        "url": "https://www.cnbc.com/2026/10/04/more-tankers-struck-in-gulf-waters-as-iran-reiterates-conditions.html",
        "summary": "Tehran's conditions include a halt to U.S. \"acts of aggression,\" an end to the naval blockade and economic warfare, and the release of Iranian assets.",
        "published": "04 Oct 2026 19:35 WIB",
        "sentiment": "Bearish",
        "score": -0.69,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Ukraine’s surprise robot offensive exposes a vulnerability in Putin’s war machine",
        "url": "https://www.cnbc.com/2026/10/04/russia-ukraine-war-putin-zelenskyy-donbas-lyman.html",
        "summary": "Experts say the offensive is not a decisive breakthrough, but demonstrates how Ukraine’s expanding use of robotic systems is reshaping frontline warfare.",
        "published": "04 Oct 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.909,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "FlyDubai plane attack by co-pilot was an attempted 'terrorist' act, UAE says",
        "url": "https://www.cnbc.com/2026/10/03/flydubai-co-pilot-attacked-pilot-with-axe-uae-says.html",
        "summary": "The FlyDubai co-pilot attacked the pilot inside the cockpit with a crash axe and attempted to take control of the aircraft, the UAE prosecutor general said.",
        "published": "03 Oct 2026 19:34 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      }
    ]
  },
  "fj_live": {
    "generated": "04 Oct 2026 22:01 WIB",
    "summary": {
      "total": 14,
      "bullish": 7,
      "bearish": 4,
      "netral": 3,
      "avg_score": 0.0452,
      "overall": "Netral"
    },
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Jobs Slow but Inflation Keeps Fed on Alert",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/jobs-slow-but-inflation-keeps-fed-on-alert-video",
        "summary": "Bloomberg Intelligence Chief US Interest Rate Strategist Ira Jersey tells Bloomberg This Weekend that softer September jobs data give the Federal Reserve room to hold rates steady in October, but persistent inflation could still lead policymakers to raise rates again in December and early next year.",
        "published": "04 Oct 2026 20:04 WIB",
        "sentiment": "Bullish",
        "score": 1.0,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "EM Investors Shrug Off Quarter’s Pullback, Double Down on Carry Trades",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/em-investors-shrug-off-quarter-s-pullback-double-down-on-carry-trades",
        "summary": "Investors are sticking with emerging-market carry trades, even after a rare quarterly loss, betting the strategy will be able to weather Treasury yields at multi-decade highs",
        "published": "04 Oct 2026 19:30 WIB",
        "sentiment": "Bearish",
        "score": -0.208,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "G7 Fuel Release Offers Temporary Price Relief",
        "url": "https://www.bloomberg.com/news/videos/2026-10-04/g7-fuel-release-offers-temporary-price-relief-video",
        "summary": "Bloomberg Mideast Energy Correspondent Anthony Di Paola tells Bloomberg This Weekend that the G7’s 100 million-barrel emergency release is already pushing fuel prices lower but is likely to provide only temporary relief as refinery constraints and Middle East disruptions keep diesel supplies tight. ",
        "published": "04 Oct 2026 19:07 WIB",
        "sentiment": "Bullish",
        "score": 0.128,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Fed minutes coming this week could give markets important clues about future rate hikes",
        "url": "https://www.marketwatch.com/story/fed-minutes-coming-this-week-could-give-markets-important-clues-about-future-rate-hikes-31bfba5b?mod=mw_rss_topstories",
        "summary": "Minutes from the September meeting may provide extra context, as the real fed-funds rate is now surprisingly low.",
        "published": "04 Oct 2026 19:00 WIB",
        "sentiment": "Bullish",
        "score": 0.306,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "FinancialJuice",
        "title": "OPEC+ keeps oil output quotas unchanged for November at Sunday meeting: statement",
        "url": "https://www.financialjuice.com/News/9790797/OPEC-keeps-oil-output-quotas-unchanged-for-November-at-Sunday-meeting-statement.aspx?xy=rss",
        "summary": "",
        "published": "04 Oct 2026 18:14 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "OPEC+ reaches agreement in principle to maintain oil output targets in November, delegate says",
        "url": "https://www.financialjuice.com/News/9790739/OPEC-reaches-agreement-in-principle-to-maintain-oil-output-targets-in-November-delegate-says.aspx?xy=rss",
        "summary": "",
        "published": "04 Oct 2026 14:55 WIB",
        "sentiment": "Bullish",
        "score": 0.607,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "OPEC+ Agrees to Keep Oil Output Targets Steady in November",
        "url": "https://www.bloomberg.com/news/articles/2026-10-04/opec-has-deal-outline-for-steady-november-quotas-delegates-say",
        "summary": "Major OPEC+ nations agreed to keep oil production quotas unchanged next month, as conflict in the Middle East continues to shutter swaths of the group’s output.",
        "published": "04 Oct 2026 14:49 WIB",
        "sentiment": "Bullish",
        "score": 0.138,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Falling wages, soaring energy prices and inflation: It’s beginning to look a lot like the 1970s",
        "url": "https://www.marketwatch.com/story/falling-wages-soaring-energy-prices-and-inflation-its-beginning-to-look-a-lot-like-the-1970s-d645cbca?mod=mw_rss_topstories",
        "summary": "Is it time to dust off the financial playbook from that dismal decade?",
        "published": "04 Oct 2026 06:58 WIB",
        "sentiment": "Bearish",
        "score": -0.33,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Venezuela September inflation rises 8.4%: central bank",
        "url": "https://www.financialjuice.com/News/9790515/Venezuela-September-inflation-rises-84-central-bank.aspx?xy=rss",
        "summary": "",
        "published": "03 Oct 2026 21:18 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "US-Russia talks on Ukraine now include a multi-billion dollar oil pact linked to Trump allies: NYT",
        "url": "https://www.financialjuice.com/News/9790414/US-Russia-talks-on-Ukraine-now-include-a-multi-billion-dollar-oil-pact-linked-to-Trump-allies-NYT.aspx?xy=rss",
        "summary": "",
        "published": "03 Oct 2026 16:14 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "G7 to release millions of barrels of oil and diesel after Trump threat",
        "url": "https://www.bbc.co.uk/news/articles/ck87zg8jnwngo?at_medium=RSS&at_campaign=rss",
        "summary": "The co-ordinated release is aimed at heading off further price spikes and avoiding a ban on US diesel exports.",
        "published": "03 Oct 2026 11:38 WIB",
        "sentiment": "Bearish",
        "score": -0.856,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "UKMTO: master of crude oil tanker reports being hit by unknown projectile on port side",
        "url": "https://www.financialjuice.com/News/9790135/UKMTO-master-of-crude-oil-tanker-reports-being-hit-by-unknown-projectile-on-port-side.aspx?xy=rss",
        "summary": "",
        "published": "03 Oct 2026 06:17 WIB",
        "sentiment": "Bearish",
        "score": -0.572,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "IMF: board greenlit 36-month deal under the EFF for Bolivia, with access to SDR 1.369 billion, or 570% of quota, about $1.9 billion",
        "url": "https://www.financialjuice.com/News/9790117/IMF-board-greenlit-36-month-deal-under-the-EFF-for-Bolivia-with-access-to-SDR-1369-billion-or-570-of-quota-about-19-billion.aspx?xy=rss",
        "summary": "",
        "published": "03 Oct 2026 05:03 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "IMF: executive board endorses 36-month extended fund facility for Bolivia",
        "url": "https://www.financialjuice.com/News/9790116/IMF-executive-board-endorses-36-month-extended-fund-facility-for-Bolivia.aspx?xy=rss",
        "summary": "",
        "published": "03 Oct 2026 05:02 WIB",
        "sentiment": "Bullish",
        "score": 0.34,
        "emoji": "🟢",
        "impact": "low"
      }
    ]
  },
  "rekomendasi": {
    "generated": "04 Oct 2026 22:01 WIB",
    "pairs": [
      {
        "label": "GBP/AUD",
        "score": 51,
        "direction": "BUY",
        "rsi": 51.6,
        "last_close": "1.90398",
        "smma7": "1.90318",
        "ema9": "1.90321",
        "atr14": "0.00226",
        "bars_since_cross": 0,
        "cross_label": "Baru saja",
        "freshness_score": 50,
        "separation_score": 0,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/NZD",
        "score": 48,
        "direction": "SELL",
        "rsi": 37.6,
        "last_close": "2.00123",
        "smma7": "2.00393",
        "ema9": "2.00365",
        "atr14": "0.00279",
        "bars_since_cross": 2,
        "cross_label": "2 candle lalu",
        "freshness_score": 40,
        "separation_score": 2,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/JPY",
        "score": 42,
        "direction": "BUY",
        "rsi": 52.2,
        "last_close": "157.830",
        "smma7": "157.759",
        "ema9": "157.767",
        "atr14": "0.232",
        "bars_since_cross": 2,
        "cross_label": "2 candle lalu",
        "freshness_score": 40,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.479,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.479,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/JPY",
        "score": 27,
        "direction": "BUY",
        "rsi": 60.9,
        "last_close": "209.071",
        "smma7": "208.774",
        "ema9": "208.852",
        "atr14": "0.298",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CHF",
        "score": 27,
        "direction": "BUY",
        "rsi": 50.0,
        "last_close": "1.09710",
        "smma7": "1.09655",
        "ema9": "1.09673",
        "atr14": "0.00211",
        "bars_since_cross": 5,
        "cross_label": "5 candle lalu",
        "freshness_score": 25,
        "separation_score": 2,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/JPY",
        "score": 27,
        "direction": "BUY",
        "rsi": 50.5,
        "last_close": "177.659",
        "smma7": "177.583",
        "ema9": "177.601",
        "atr14": "0.268",
        "bars_since_cross": 5,
        "cross_label": "5 candle lalu",
        "freshness_score": 25,
        "separation_score": 2,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/JPY",
        "score": 23,
        "direction": "BUY",
        "rsi": 59.9,
        "last_close": "88.749",
        "smma7": "88.587",
        "ema9": "88.605",
        "atr14": "0.156",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 3,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CAD",
        "score": 22,
        "direction": "BUY",
        "rsi": 67.5,
        "last_close": "1.88648",
        "smma7": "1.88471",
        "ema9": "1.88564",
        "atr14": "0.00182",
        "bars_since_cross": 12,
        "cross_label": "12 candle lalu",
        "freshness_score": 0,
        "separation_score": 13,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/JPY",
        "score": 20,
        "direction": "BUY",
        "rsi": 59.9,
        "last_close": "109.802",
        "smma7": "109.677",
        "ema9": "109.716",
        "atr14": "0.186",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 5,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/GBP",
        "score": 19,
        "direction": "SELL",
        "rsi": 31.3,
        "last_close": "0.84972",
        "smma7": "0.85047",
        "ema9": "0.85022",
        "atr14": "0.00067",
        "bars_since_cross": 77,
        "cross_label": "77 candle lalu",
        "freshness_score": 0,
        "separation_score": 10,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CAD",
        "score": 16,
        "direction": "BUY",
        "rsi": 51.5,
        "last_close": "1.60320",
        "smma7": "1.60311",
        "ema9": "1.60345",
        "atr14": "0.00183",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 5,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/AUD",
        "score": 12,
        "direction": "SELL",
        "rsi": 36.6,
        "last_close": "1.61750",
        "smma7": "1.61882",
        "ema9": "1.61836",
        "atr14": "0.00214",
        "bars_since_cross": 40,
        "cross_label": "40 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 7,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/USD",
        "score": 11,
        "direction": "BUY",
        "rsi": 57.9,
        "last_close": "1.32405",
        "smma7": "1.32327",
        "ema9": "1.32364",
        "atr14": "0.00135",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.479,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.479,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CAD",
        "score": 10,
        "direction": "BUY",
        "rsi": 61.3,
        "last_close": "0.80067",
        "smma7": "0.79968",
        "ema9": "0.79993",
        "atr14": "0.00144",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/USD",
        "score": 10,
        "direction": "BUY",
        "rsi": 47.7,
        "last_close": "1.12575",
        "smma7": "1.12586",
        "ema9": "1.12587",
        "atr14": "0.00135",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 0,
        "rsi_score": 0,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -1.099,
          "confidence": "Kuat",
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Bullish",
          "base_score": -0.62,
          "quote_score": 0.479,
          "base_count": 4,
          "quote_count": 2,
          "base_insufficient": false,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/USD",
        "score": 9,
        "direction": "BUY",
        "rsi": 55.6,
        "last_close": "0.69575",
        "smma7": "0.69543",
        "ema9": "0.69562",
        "atr14": "0.00083",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.479,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.479,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/CAD",
        "score": 9,
        "direction": "BUY",
        "rsi": 55.4,
        "last_close": "0.98991",
        "smma7": "0.99002",
        "ema9": "0.99044",
        "atr14": "0.00184",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/CHF",
        "score": 9,
        "direction": "SELL",
        "rsi": 37.6,
        "last_close": "0.58130",
        "smma7": "0.58170",
        "ema9": "0.58150",
        "atr14": "0.00157",
        "bars_since_cross": 38,
        "cross_label": "38 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CHF/JPY",
        "score": 7,
        "direction": "BUY",
        "rsi": 58.9,
        "last_close": "190.499",
        "smma7": "190.353",
        "ema9": "190.389",
        "atr14": "0.336",
        "bars_since_cross": 50,
        "cross_label": "50 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CHF",
        "score": 6,
        "direction": "SELL",
        "rsi": 43.0,
        "last_close": "0.82848",
        "smma7": "0.82873",
        "ema9": "0.82862",
        "atr14": "0.00165",
        "bars_since_cross": 31,
        "cross_label": "31 candle lalu",
        "freshness_score": 0,
        "separation_score": 2,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.479,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.479,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CAD",
        "score": 6,
        "direction": "BUY",
        "rsi": 54.8,
        "last_close": "1.42450",
        "smma7": "1.42433",
        "ema9": "1.42459",
        "atr14": "0.00150",
        "bars_since_cross": 11,
        "cross_label": "11 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.479,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.479,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CHF",
        "score": 6,
        "direction": "SELL",
        "rsi": 41.4,
        "last_close": "0.93210",
        "smma7": "0.93268",
        "ema9": "0.93256",
        "atr14": "0.00187",
        "bars_since_cross": 38,
        "cross_label": "38 candle lalu",
        "freshness_score": 0,
        "separation_score": 2,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.62,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.62,
          "quote_score": 0.0,
          "base_count": 4,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/USD",
        "score": 5,
        "direction": "BUY",
        "rsi": 55.9,
        "last_close": "0.56230",
        "smma7": "0.56167",
        "ema9": "0.56173",
        "atr14": "0.00080",
        "bars_since_cross": 16,
        "cross_label": "16 candle lalu",
        "freshness_score": 0,
        "separation_score": 2,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.479,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.479,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/JPY",
        "score": 3,
        "direction": "SELL",
        "rsi": 48.7,
        "last_close": "110.789",
        "smma7": "110.756",
        "ema9": "110.741",
        "atr14": "0.166",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 2,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/NZD",
        "score": 2,
        "direction": "BUY",
        "rsi": 47.5,
        "last_close": "1.23671",
        "smma7": "1.23772",
        "ema9": "1.23785",
        "atr14": "0.00164",
        "bars_since_cross": 12,
        "cross_label": "12 candle lalu",
        "freshness_score": 0,
        "separation_score": 2,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CHF",
        "score": 0,
        "direction": "SELL",
        "rsi": 50.0,
        "last_close": "0.46565",
        "smma7": "0.46526",
        "ema9": "0.46526",
        "atr14": "0.00110",
        "bars_since_cross": 52,
        "cross_label": "52 candle lalu",
        "freshness_score": 0,
        "separation_score": 0,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      }
    ],
    "total": 26
  }
};
