// Diperbarui: 16 Aug 2026 22:01 WIB
window.FK_DATA = {
  "generated": "16 Aug 2026 22:01 WIB",
  "kalender": {
    "generated": "16 Aug 2026 22:01 WIB",
    "events": []
  },
  "sentimen": {
    "generated": "16 Aug 2026 22:01 WIB",
    "summary": {
      "total": 49,
      "bullish": 16,
      "bearish": 25,
      "netral": 8,
      "avg_score": -0.2184,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "EUR",
          "sentiment": "Netral",
          "score": -0.021,
          "count": 3
        },
        {
          "currency": "USD",
          "sentiment": "Bullish",
          "score": 0.12,
          "count": 2
        }
      ]
    },
    "items": [
      {
        "source": "ForexLive",
        "title": "Pendapatan saham: 3 Pelajaran penting bagi investor dan pedagang",
        "url": "https://investinglive.com/education/stock-earnings-3-key-lessons-for-investors-and-traders/",
        "summary": "Earnings beats are not enough: What experienced investors watch instead A stock can beat Wall Street’s earnings estimates and still fall sharply. Another company can miss an estimate and rally. This is not necessarily irrational. Stock prices respond to how results compare with the expectations alre",
        "published": "15 Aug 2026 22:00 WIB",
        "sentiment": "Bullish",
        "score": 0.112,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Arus masuk ekuitas AS tiga kali lipat dari minggu ke minggu karena Wall Street mendekati level rekor",
        "url": "https://www.investing.com/news/stock-market-news/us-equity-inflows-triple-weekonweek-as-wall-street-hovers-near-record-levels-4861984",
        "summary": "",
        "published": "16 Aug 2026 20:41 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Saham Arab Saudi menguat pada penutupan perdagangan; Tadawul Semua Saham naik 0,89%",
        "url": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-higher-at-close-of-trade-tadawul-all-share-up-089-4861977",
        "summary": "",
        "published": "16 Aug 2026 19:45 WIB",
        "sentiment": "Bullish",
        "score": 0.296,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Rusia menyerang pabrik baja dalam serangan baru di Ukraina, Kyiv menyerang wilayah Moskow",
        "url": "https://www.investing.com/news/stock-market-news/russia-hits-steel-plant-in-new-strikes-on-ukraine-kyiv-attacks-moscow-region-4861966",
        "summary": "",
        "published": "16 Aug 2026 18:18 WIB",
        "sentiment": "Bearish",
        "score": -0.74,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "5 gerakan AI analis besar: Bullish pada nama memori; Apple dan Cisco diturunkan peringkatnya",
        "url": "https://www.investing.com/news/stock-market-news/5-big-analyst-ai-moves-bullish-on-memory-names-apple-and-cisco-downgraded-4861817",
        "summary": "",
        "published": "16 Aug 2026 16:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Bisakah SpaceX Melompat ke Perbatasan AI?",
        "url": "https://www.investing.com/news/stock-market-news/can-spacex-leap-to-the-ai-frontier-4861908",
        "summary": "",
        "published": "16 Aug 2026 11:11 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Peter Thiel membeli 1% saham Vista Energy Argentina",
        "url": "https://www.investing.com/news/stock-market-news/peter-thiel-buys-1-stake-in-argentinas-vista-energy-4861898",
        "summary": "",
        "published": "16 Aug 2026 09:02 WIB",
        "sentiment": "Bullish",
        "score": 0.273,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Hanya 13% dari dana pemetikan saham berkapitalisasi besar di AS yang mengalahkan tolok ukur selama satu dekade",
        "url": "https://www.investing.com/news/stock-market-news/just-13-of-us-largecap-stockpicking-funds-beat-benchmarks-over-decade-4861893",
        "summary": "",
        "published": "16 Aug 2026 08:37 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Miliarder Peter Thiel membeli 1% saham di perusahaan minyak Argentina Vaca Muerta, menurut laporan",
        "url": "https://www.investing.com/news/stock-market-news/billionaire-peter-thiel-buys-1-stake-in-argentine-vaca-muerta-oil-firm-filing-shows-4861892",
        "summary": "",
        "published": "16 Aug 2026 08:36 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Bagaimana Disney bisa mendapatkan kembali momentum narasinya?",
        "url": "https://www.investing.com/news/stock-market-news/how-can-disney-get-back-its-narrative-momentum-4861890",
        "summary": "",
        "published": "16 Aug 2026 07:46 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Mengapa mobilisasi investasi Nvidia sebesar $500 miliar berdampak positif bagi sahamnya",
        "url": "https://www.investing.com/news/stock-market-news/why-nvidias-500bn-investment-mobilization-is-a-positive-for-the-stock-4861855",
        "summary": "",
        "published": "16 Aug 2026 04:07 WIB",
        "sentiment": "Bullish",
        "score": 0.557,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Kampanye Tekanan Iran Kurang Jelas",
        "url": "https://www.bloomberg.com/news/videos/2026-08-16/iran-pressure-campaign-lacks-clear-off-ramp",
        "summary": "Acting Principal Deputy Assistant Secretary for the Bureau of Near Eastern Affairs Jen Gavito and retired Vice Adm. Robert Harward join Bloomberg This Weekend and offer sharply different assessments of whether escalating US economic pressure can change Iran’s calculus, with Gavito arguing sanctions ",
        "published": "16 Aug 2026 20:01 WIB",
        "sentiment": "Bearish",
        "score": -0.991,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Di Pesta Pasar Berbahan Bakar AI, Wall Street Mengincar Harga Punch Bowl",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/at-ai-fueled-market-party-wall-street-eyes-the-rates-punch-bowl",
        "summary": "Enthusiasm for Big Tech and its huge investments in artificial intelligence is powering the stock market to record highs again. With a resilient economy and scorching demand, there’s seemingly only one obstacle that can derail this ride: higher interest rates.",
        "published": "16 Aug 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.912,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Pedagang Menjadi Lebih Pilih-pilih Setelah Pergerakan Besar di Pasar Utang Negara Berkembang senilai $886 Miliar",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/traders-get-pickier-after-big-run-in-886-billion-em-debt-market",
        "summary": "Persistent inflation worries and currency swings are pushing emerging-market investors to adjust bets in an $886 billion asset class that’s been delivering outsize returns for more than a year.",
        "published": "16 Aug 2026 19:30 WIB",
        "sentiment": "Bearish",
        "score": -0.421,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Apa yang Terjadi di EM: Trader Semakin Memilih Linker (Podcast)",
        "url": "https://www.bloomberg.com/news/audio/2026-08-16/what-s-happening-in-em-traders-get-pickier-on-linkers-podcast",
        "summary": "Bogota-based EM reporter Nicolle Yapur joins Leda Alvim to discuss why investors are looking beyond Brazil and Mexico for opportunities in inflation-linked bonds in the emerging world.",
        "published": "16 Aug 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.382,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "MOU Iran Berakhir Karena Diplomasi Masih Dijalankan",
        "url": "https://www.bloomberg.com/news/videos/2026-08-16/iran-mou-expires-with-diplomacy-still-in-play-video",
        "summary": "Bloomberg News Middle East Reporter Dan Williams is on Bloomberg This Weekend discussing how the expiration of the US-Iran memorandum of understanding is unlikely by itself to trigger a return to all-out fighting, with diplomatic efforts over the Strait of Hormuz continuing despite repeated attacks ",
        "published": "16 Aug 2026 19:13 WIB",
        "sentiment": "Bullish",
        "score": 0.239,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Mengapa Pedoman Ekuitas Swasta Kalah dari Pasar Publik",
        "url": "https://www.bloomberg.com/news/videos/2026-08-16/private-equity-s-playbook-is-losing-to-public-markets-video",
        "summary": "Private equity has long promised investors better returns than public markets, while offering entrepreneurs like Dan Namerow life-changing exits. But the market that made those deals work has changed. Higher interest rates have made debt-financed buyouts harder to justify, while deals struck at peak",
        "published": "16 Aug 2026 19:03 WIB",
        "sentiment": "Bullish",
        "score": 0.198,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Obligasi Menghadapi Ancaman yang Lebih Besar Dibandingkan The Fed seiring Meningkatnya Suku Bunga Global",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/bonds-face-a-bigger-threat-than-the-fed-as-global-rates-climb",
        "summary": "As investors debate whether and when the Federal Reserve will raise interest rates, market expectations for further tightening are building around the world — and spelling trouble for bonds.",
        "published": "16 Aug 2026 19:00 WIB",
        "sentiment": "Bearish",
        "score": -0.397,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "DAP Malaysia Memberi Anwar Penundaan Keputusan untuk Tetap di Kabinet",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/malaysia-s-dap-hands-anwar-reprieve-with-vote-to-stay-in-cabinet",
        "summary": "Malaysia’s Democratic Action Party voted on Sunday to remain in Prime Minister Anwar Ibrahim’s cabinet, giving him a reprieve after a string of electoral setbacks and turmoil within his own party.",
        "published": "16 Aug 2026 16:28 WIB",
        "sentiment": "Bullish",
        "score": 0.569,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "India Mempersiapkan Peningkatan Besar Produksi LPG karena Ketidakpastian Hormuz Masih Ada",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/india-readies-big-lpg-output-boost-as-hormuz-uncertainty-lingers",
        "summary": "India has directed its state companies and private refiners to prepare for a sharp increase in cooking gas production, seeking to bolster domestic supplies as the Iran war prolongs uncertainty over the Strait of Hormuz, the key waterway for about 90% of the country’s liquefied petroleum gas imports.",
        "published": "16 Aug 2026 14:13 WIB",
        "sentiment": "Bearish",
        "score": -0.652,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Forex Hari Ini: Dolar Turun Karena Taruhan Kenaikan Suku Bunga Fed Mendingin, Batasan Kebuntuan di Timur Tengah Bergerak - CryptoRank",
        "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQbjZfZGVseWNWbjktRjZnNXFWTHVXOGlVbEFRVThsMzlrZ0ItNnFPcEFJYkkySDUtSmdNTHpCeHlpa2l5STFPbDAxdW9KbU1wM2d0Zk84c251YmptVkEteEtpWEUwcEgzXzBnWHhKN2lGMzJYM2xXcndjZjdhT25DN3BpQnRqUjZZdEs4aXdoOG5hMXZFdGRIWWFyaDZrWFdvanJBTC1R?oc=5",
        "summary": "Forex Today: Dollar Dips as Fed Rate Hike Bets Cool, Mideast Stalemate Caps Moves CryptoRank",
        "published": "16 Aug 2026 06:28 WIB",
        "sentiment": "Bullish",
        "score": 0.637,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Lima orang tewas saat Rusia melancarkan serangan udara baru ke seluruh Ukraina",
        "url": "https://www.bbc.co.uk/news/articles/c1411pgje8xo?at_medium=RSS&at_campaign=rss",
        "summary": "Ukrainian President Volodymyr Zelensky accuses Russia of targeting civilian infrastructure, while Moscow reports that a warehouse was hit.",
        "published": "16 Aug 2026 17:52 WIB",
        "sentiment": "Bearish",
        "score": -0.978,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Patung Perawan Maria tertinggi di Eropa diresmikan di pedesaan Polandia",
        "url": "https://www.bbc.co.uk/news/articles/cn5nnlq2pwpo?at_medium=RSS&at_campaign=rss",
        "summary": "The 55.6-metre (182ft) concrete figure is head-and-shoulders above Rio de Jaineiro's Christ the Redeemer.",
        "published": "16 Aug 2026 18:35 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Qatar membantah menangkap tiga pilot Iran setelah menjatuhkan jet tempur",
        "url": "https://www.bbc.co.uk/news/articles/cj4kk8kz271o?at_medium=RSS&at_campaign=rss",
        "summary": "Iran claims they have been held since Qatar downed two fighter jets at the start of the US-Iran war.",
        "published": "16 Aug 2026 16:27 WIB",
        "sentiment": "Bearish",
        "score": -0.75,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Liechtenstein mengubah aturan suksesi untuk mengizinkan perempuan naik takhta",
        "url": "https://www.bbc.co.uk/news/articles/cn9nnxrxg4qo?at_medium=RSS&at_campaign=rss",
        "summary": "The declaration was made on the national day of the central European country, which has a population of just 44,000.",
        "published": "16 Aug 2026 02:41 WIB",
        "sentiment": "Bullish",
        "score": 0.402,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Sebelas orang tewas dalam serangan Israel di Lebanon selatan, kata pihak berwenang",
        "url": "https://www.bbc.co.uk/news/articles/c4gjygx4gjeo?at_medium=RSS&at_campaign=rss",
        "summary": "Israel's military said it had struck \"Hezbollah terror infrastructure\" in response to what it described as earlier action against its soldiers.",
        "published": "16 Aug 2026 03:21 WIB",
        "sentiment": "Bearish",
        "score": -0.828,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Negara bagian Australia akan meluncurkan pembelian kembali senjata setelah serangan Pantai Bondi",
        "url": "https://www.bbc.co.uk/news/articles/cgjee21eenvo?at_medium=RSS&at_campaign=rss",
        "summary": "New South Wales, where the attack took place, will offer gun owners cash to give up their firearms.",
        "published": "16 Aug 2026 04:41 WIB",
        "sentiment": "Bearish",
        "score": -0.955,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Korea Selatan mengusulkan perundingan untuk secara resmi mengakhiri perang dengan Korea Utara",
        "url": "https://www.bbc.co.uk/news/articles/c8en2z9jp2xo?at_medium=RSS&at_campaign=rss",
        "summary": "Lee Jae Myung offers chance to end the conflict, which has been frozen since an armistice in 1953.",
        "published": "15 Aug 2026 21:40 WIB",
        "sentiment": "Bearish",
        "score": -0.797,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Business",
        "title": "Larangan sementara terhadap BBQ sekali pakai saat militer dikerahkan untuk membantu memadamkan kebakaran hutan",
        "url": "https://www.bbc.co.uk/news/articles/c0jlyqdj6geo?at_medium=RSS&at_campaign=rss",
        "summary": "Single-use grills pose a \"significant risk to the public\" in current drought and heatwave conditions, the government warns.",
        "published": "15 Aug 2026 10:58 WIB",
        "sentiment": "Bearish",
        "score": -0.797,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Penyelidikan pembunuhan setelah pria yang digigit anjing meninggal",
        "url": "https://www.bbc.co.uk/news/articles/cx2dd0gd4z2o?at_medium=RSS&at_campaign=rss",
        "summary": "Police appeal for two people who stopped to help the victim in Wakefield to come forward.",
        "published": "16 Aug 2026 19:36 WIB",
        "sentiment": "Bearish",
        "score": -0.798,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Para influencer digigit saat mengejar gambar hiu yang sempurna",
        "url": "https://www.bbc.co.uk/news/articles/c5yvrn7rpqpo?at_medium=RSS&at_campaign=rss",
        "summary": "Tayane Dalazen was on a shark-diving trip in Brazil when she was attacked.",
        "published": "16 Aug 2026 06:04 WIB",
        "sentiment": "Bullish",
        "score": 0.098,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Drone buatan Inggris menyerang sasaran di wilayah Rusia",
        "url": "https://www.bbc.co.uk/news/articles/c5ywwv2pp44o?at_medium=RSS&at_campaign=rss",
        "summary": "The drones have been used for the first time in mainland Russia to hit military and industrial targets.",
        "published": "16 Aug 2026 19:22 WIB",
        "sentiment": "Bearish",
        "score": -0.128,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "‘Mediterania adalah jembatan, bukan perbatasan’",
        "url": "https://www.aljazeera.com/video/talk-to-al-jazeera/2026/8/16/the-mediterranean-is-a-bridge-not-a?traffic_source=rss",
        "summary": "Chris Fearne says Europe must look beyond its borders to solve its migration problem.",
        "published": "16 Aug 2026 21:40 WIB",
        "sentiment": "Bearish",
        "score": -0.226,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Apa Kuil Yasukuni di Tokyo, yang terkait dengan kekejaman Jepang di masa perang?",
        "url": "https://www.aljazeera.com/news/2026/8/16/what-is-tokyos-yasukuni-shrine-linked-to-japans-wartime-atrocities?traffic_source=rss",
        "summary": "About 2.5 million people, including Japanese war criminals who fought for the country, are enshrined at Yasukuni.",
        "published": "16 Aug 2026 21:29 WIB",
        "sentiment": "Bearish",
        "score": -0.952,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Houthi melancarkan serangan baru terhadap al-Makha dan Marib ketika konflik Yaman meningkat",
        "url": "https://www.aljazeera.com/news/2026/8/16/houthis-launch-new-attacks-on-al-makha-and-marib-as-yemen-conflict-escalates?traffic_source=rss",
        "summary": "Houthi missile and drone strikes target Marib and al-Makha, killing at least four people and injuring eight.",
        "published": "16 Aug 2026 20:18 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Timeline: Pengepungan Qusra selama satu minggu oleh pemukim Israel di Tepi Barat",
        "url": "https://www.aljazeera.com/gallery/2026/8/16/timeline-the-one-week-siege-of-qusra-by-israeli-settlers-in-the-west-bank?traffic_source=rss",
        "summary": "Israeli settlers encircle Palestinian homes and cut off supplies, leading to a declaration of a military zone.",
        "published": "16 Aug 2026 20:17 WIB",
        "sentiment": "Bearish",
        "score": -0.273,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Kebakaran hutan terbesar di Belgia yang pernah tercatat menyebar hingga ke perbatasan Jerman",
        "url": "https://www.aljazeera.com/news/2026/8/16/belgiums-largest-wildfire-on-record-spreads-towards-german-border?traffic_source=rss",
        "summary": "Largest recorded wildfire in Belgium forces 600 residents to evacuate as blaze spreads towards German border towns.",
        "published": "16 Aug 2026 19:35 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "'Pilihan terbatas' bagi banyak warga Iran karena perang dengan AS menghambat perekonomian",
        "url": "https://www.aljazeera.com/news/2026/8/16/limited-options-for-many-iranians-as-war-with-us-chokes-economy?traffic_source=rss",
        "summary": "Millions of Iranians struggle to make ends meet as war with US devastates the economy and sends prices soaring.",
        "published": "16 Aug 2026 18:38 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Trump mengancam menjadikan Selat Hormuz sebagai wilayah AS: Bolehkah?",
        "url": "https://www.aljazeera.com/news/2026/8/16/trump-threatens-to-make-the-strait-of-hormuz-a-us-territory-can-he?traffic_source=rss",
        "summary": "US president has yet another outlandish threat for Iran, with no end to war in sight.",
        "published": "16 Aug 2026 18:14 WIB",
        "sentiment": "Bearish",
        "score": -0.982,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Mengapa Israel meningkatkan serangan di Lebanon selatan meski gencatan senjata?",
        "url": "https://www.aljazeera.com/news/2026/8/16/why-has-israel-escalated-attacks-in-southern-lebanon-despite-ceasefire?traffic_source=rss",
        "summary": "At least 11 people killed in one day of Israeli attacks despite truce extension brokered by US in June.",
        "published": "16 Aug 2026 17:59 WIB",
        "sentiment": "Bearish",
        "score": -0.963,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Debut Mohamed Salah di Trabzonspor berakhir imbang dengan Kasimpasa",
        "url": "https://www.aljazeera.com/sports/2026/8/16/mohamed-salah-trabzonspor-debut-draw-kasimpasa-turkish-super-lig?traffic_source=rss",
        "summary": "The Egyptian forward, who joined the Turkish club on a free transfer, came off the bench early in the second half.",
        "published": "16 Aug 2026 16:48 WIB",
        "sentiment": "Bullish",
        "score": 0.431,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Inilah alasan sebenarnya mengapa harga minyak tidak bergerak lebih tinggi",
        "url": "https://www.marketwatch.com/story/heres-the-real-reason-oil-prices-arent-moving-higher-256afdbc?mod=mw_rss_topstories",
        "summary": "Oil prices are not higher largely because the world does not want as much oil as it used to — and that’s arguably the more troubling story.",
        "published": "16 Aug 2026 20:00 WIB",
        "sentiment": "Bearish",
        "score": -0.72,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Walmart dan Target akan mengungkap kesehatan konsumen AS",
        "url": "https://www.marketwatch.com/story/walmart-and-target-are-about-to-reveal-the-health-of-the-u-s-consumer-d5b89491?mod=mw_rss_topstories",
        "summary": "Earnings reports from the two major retailers will show how shoppers are holding up in an era of persistent inflation.",
        "published": "16 Aug 2026 18:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Apakah Anda pikir suku bunga sekarang tinggi? Bagan ini menawarkan perspektif yang berbeda.",
        "url": "https://www.marketwatch.com/story/think-interest-rates-are-high-now-these-charts-offers-a-different-perspective-ae5f28c6?mod=mw_rss_topstories",
        "summary": "Also in Weekend Reads: 10 remarkable housing markets, stock picks, and health-insurance battles.",
        "published": "16 Aug 2026 02:01 WIB",
        "sentiment": "Bullish",
        "score": 0.612,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Rahasia yang unggul: Menghilangkan 'mitos' tentang pasar saham yang tidak disukai",
        "url": "https://www.cnbc.com/2026/08/16/goldman-stock-market-outperformance.html",
        "summary": "European markets fly under the radar when compared with larger and more liquid U.S. markets, but Goldman Sachs offered to dispel some of the myths.",
        "published": "16 Aug 2026 16:45 WIB",
        "sentiment": "Bearish",
        "score": -0.238,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Cadangan minyak strategis yang menipis mendekati tingkat yang menimbulkan kekhawatiran akan kerusakan pada gua-gua dan operasi",
        "url": "https://www.cnbc.com/2026/08/15/strategic-petroleum-reserve-spr-oil-iran-war-caverns.html",
        "summary": "The rapid drawdown of the U.S. Strategic Petroleum Reserve could damage the caverns that store the oil, experts warn.",
        "published": "15 Aug 2026 21:19 WIB",
        "sentiment": "Bearish",
        "score": -0.858,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Perekonomian Rusia telah menentang pandangan skeptis. Retakan semakin sulit disembunyikan",
        "url": "https://www.cnbc.com/2026/08/15/ukraine-war-russia-economy-putin-oil.html",
        "summary": "Russia's wartime economy is under growing strain as its budget deficit widens and analysts warn pressure could intensify next year.",
        "published": "15 Aug 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.79,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Panas ekstrem memicu panen Champagne yang paling awal, sehingga menguji rasanya yang terkenal",
        "url": "https://www.cnbc.com/2026/08/15/heatwave-champagne-harvest-climate.html",
        "summary": "Producers of the iconic French fizz face a challenge to preserve its taste profile while they also battle tariff complications and fewer drinkers.",
        "published": "15 Aug 2026 12:00 WIB",
        "sentiment": "Netral",
        "score": -0.026,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "CNBC World",
        "title": "Pendapatan antropik dilaporkan melonjak hingga lebih dari $11,5 miliar pada kuartal kedua",
        "url": "https://www.cnbc.com/2026/08/15/anthropic-revenue-jumps-to-over-11point5-billion-in-q2-report.html",
        "summary": "The jump in revenue underscores the rapid growth of the Claude chatbot maker as it prepares for a potential blockbuster initial public offering.",
        "published": "15 Aug 2026 21:45 WIB",
        "sentiment": "Bullish",
        "score": 0.838,
        "emoji": "🟢",
        "impact": "low"
      }
    ]
  },
  "geopolitik": {
    "generated": "16 Aug 2026 22:01 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.575,
        "count": 17
      },
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.575,
        "count": 17
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.534,
        "count": 15
      },
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.605,
        "count": 3
      },
      {
        "pair": "USD/RUB",
        "direction": "Tekanan Turun ▼",
        "score": -0.991,
        "count": 1
      },
      {
        "pair": "CAD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.72,
        "count": 1
      },
      {
        "pair": "NOK/SEK",
        "direction": "Tekanan Turun ▼",
        "score": -0.72,
        "count": 1
      },
      {
        "pair": "AUD/USD",
        "direction": "Netral →",
        "score": -0.026,
        "count": 1
      }
    ],
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Kampanye Tekanan Iran Kurang Jelas",
        "url": "https://www.bloomberg.com/news/videos/2026-08-16/iran-pressure-campaign-lacks-clear-off-ramp",
        "summary": "Acting Principal Deputy Assistant Secretary for the Bureau of Near Eastern Affairs Jen Gavito and retired Vice Adm. Robert Harward join Bloomberg This Weekend and offer sharply different assessments of whether escalating US economic pressure can change Iran’s calculus, with Gavito arguing sanctions ",
        "published": "16 Aug 2026 20:01 WIB",
        "sentiment": "Bearish",
        "score": -0.991,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "MOU Iran Berakhir Karena Diplomasi Masih Dijalankan",
        "url": "https://www.bloomberg.com/news/videos/2026-08-16/iran-mou-expires-with-diplomacy-still-in-play-video",
        "summary": "Bloomberg News Middle East Reporter Dan Williams is on Bloomberg This Weekend discussing how the expiration of the US-Iran memorandum of understanding is unlikely by itself to trigger a return to all-out fighting, with diplomatic efforts over the Strait of Hormuz continuing despite repeated attacks ",
        "published": "16 Aug 2026 19:13 WIB",
        "sentiment": "Bullish",
        "score": 0.239,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "DAP Malaysia Memberi Anwar Penundaan Keputusan untuk Tetap di Kabinet",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/malaysia-s-dap-hands-anwar-reprieve-with-vote-to-stay-in-cabinet",
        "summary": "Malaysia’s Democratic Action Party voted on Sunday to remain in Prime Minister Anwar Ibrahim’s cabinet, giving him a reprieve after a string of electoral setbacks and turmoil within his own party.",
        "published": "16 Aug 2026 16:28 WIB",
        "sentiment": "Bullish",
        "score": 0.569,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "India Mempersiapkan Peningkatan Besar Produksi LPG karena Ketidakpastian Hormuz Masih Ada",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/india-readies-big-lpg-output-boost-as-hormuz-uncertainty-lingers",
        "summary": "India has directed its state companies and private refiners to prepare for a sharp increase in cooking gas production, seeking to bolster domestic supplies as the Iran war prolongs uncertainty over the Strait of Hormuz, the key waterway for about 90% of the country’s liquefied petroleum gas imports.",
        "published": "16 Aug 2026 14:13 WIB",
        "sentiment": "Bearish",
        "score": -0.652,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Lima orang tewas saat Rusia melancarkan serangan udara baru ke seluruh Ukraina",
        "url": "https://www.bbc.co.uk/news/articles/c1411pgje8xo?at_medium=RSS&at_campaign=rss",
        "summary": "Ukrainian President Volodymyr Zelensky accuses Russia of targeting civilian infrastructure, while Moscow reports that a warehouse was hit.",
        "published": "16 Aug 2026 17:52 WIB",
        "sentiment": "Bearish",
        "score": -0.978,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Qatar membantah menangkap tiga pilot Iran setelah menjatuhkan jet tempur",
        "url": "https://www.bbc.co.uk/news/articles/cj4kk8kz271o?at_medium=RSS&at_campaign=rss",
        "summary": "Iran claims they have been held since Qatar downed two fighter jets at the start of the US-Iran war.",
        "published": "16 Aug 2026 16:27 WIB",
        "sentiment": "Bearish",
        "score": -0.75,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Sebelas orang tewas dalam serangan Israel di Lebanon selatan, kata pihak berwenang",
        "url": "https://www.bbc.co.uk/news/articles/c4gjygx4gjeo?at_medium=RSS&at_campaign=rss",
        "summary": "Israel's military said it had struck \"Hezbollah terror infrastructure\" in response to what it described as earlier action against its soldiers.",
        "published": "16 Aug 2026 03:21 WIB",
        "sentiment": "Bearish",
        "score": -0.828,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Negara bagian Australia akan meluncurkan pembelian kembali senjata setelah serangan Pantai Bondi",
        "url": "https://www.bbc.co.uk/news/articles/cgjee21eenvo?at_medium=RSS&at_campaign=rss",
        "summary": "New South Wales, where the attack took place, will offer gun owners cash to give up their firearms.",
        "published": "16 Aug 2026 04:41 WIB",
        "sentiment": "Bearish",
        "score": -0.955,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Korea Selatan mengusulkan perundingan untuk secara resmi mengakhiri perang dengan Korea Utara",
        "url": "https://www.bbc.co.uk/news/articles/c8en2z9jp2xo?at_medium=RSS&at_campaign=rss",
        "summary": "Lee Jae Myung offers chance to end the conflict, which has been frozen since an armistice in 1953.",
        "published": "15 Aug 2026 21:40 WIB",
        "sentiment": "Bearish",
        "score": -0.797,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Business",
        "title": "Larangan sementara terhadap BBQ sekali pakai saat militer dikerahkan untuk membantu memadamkan kebakaran hutan",
        "url": "https://www.bbc.co.uk/news/articles/c0jlyqdj6geo?at_medium=RSS&at_campaign=rss",
        "summary": "Single-use grills pose a \"significant risk to the public\" in current drought and heatwave conditions, the government warns.",
        "published": "15 Aug 2026 10:58 WIB",
        "sentiment": "Bearish",
        "score": -0.797,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Penyelidikan pembunuhan setelah pria yang digigit anjing meninggal",
        "url": "https://www.bbc.co.uk/news/articles/cx2dd0gd4z2o?at_medium=RSS&at_campaign=rss",
        "summary": "Police appeal for two people who stopped to help the victim in Wakefield to come forward.",
        "published": "16 Aug 2026 19:36 WIB",
        "sentiment": "Bearish",
        "score": -0.798,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Para influencer digigit saat mengejar gambar hiu yang sempurna",
        "url": "https://www.bbc.co.uk/news/articles/c5yvrn7rpqpo?at_medium=RSS&at_campaign=rss",
        "summary": "Tayane Dalazen was on a shark-diving trip in Brazil when she was attacked.",
        "published": "16 Aug 2026 06:04 WIB",
        "sentiment": "Bullish",
        "score": 0.098,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Drone buatan Inggris menyerang sasaran di wilayah Rusia",
        "url": "https://www.bbc.co.uk/news/articles/c5ywwv2pp44o?at_medium=RSS&at_campaign=rss",
        "summary": "The drones have been used for the first time in mainland Russia to hit military and industrial targets.",
        "published": "16 Aug 2026 19:22 WIB",
        "sentiment": "Bearish",
        "score": -0.128,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Apa Kuil Yasukuni di Tokyo, yang terkait dengan kekejaman Jepang di masa perang?",
        "url": "https://www.aljazeera.com/news/2026/8/16/what-is-tokyos-yasukuni-shrine-linked-to-japans-wartime-atrocities?traffic_source=rss",
        "summary": "About 2.5 million people, including Japanese war criminals who fought for the country, are enshrined at Yasukuni.",
        "published": "16 Aug 2026 21:29 WIB",
        "sentiment": "Bearish",
        "score": -0.952,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Houthi melancarkan serangan baru terhadap al-Makha dan Marib ketika konflik Yaman meningkat",
        "url": "https://www.aljazeera.com/news/2026/8/16/houthis-launch-new-attacks-on-al-makha-and-marib-as-yemen-conflict-escalates?traffic_source=rss",
        "summary": "Houthi missile and drone strikes target Marib and al-Makha, killing at least four people and injuring eight.",
        "published": "16 Aug 2026 20:18 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Timeline: Pengepungan Qusra selama satu minggu oleh pemukim Israel di Tepi Barat",
        "url": "https://www.aljazeera.com/gallery/2026/8/16/timeline-the-one-week-siege-of-qusra-by-israeli-settlers-in-the-west-bank?traffic_source=rss",
        "summary": "Israeli settlers encircle Palestinian homes and cut off supplies, leading to a declaration of a military zone.",
        "published": "16 Aug 2026 20:17 WIB",
        "sentiment": "Bearish",
        "score": -0.273,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Kebakaran hutan terbesar di Belgia yang pernah tercatat menyebar hingga ke perbatasan Jerman",
        "url": "https://www.aljazeera.com/news/2026/8/16/belgiums-largest-wildfire-on-record-spreads-towards-german-border?traffic_source=rss",
        "summary": "Largest recorded wildfire in Belgium forces 600 residents to evacuate as blaze spreads towards German border towns.",
        "published": "16 Aug 2026 19:35 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "'Pilihan terbatas' bagi banyak warga Iran karena perang dengan AS menghambat perekonomian",
        "url": "https://www.aljazeera.com/news/2026/8/16/limited-options-for-many-iranians-as-war-with-us-chokes-economy?traffic_source=rss",
        "summary": "Millions of Iranians struggle to make ends meet as war with US devastates the economy and sends prices soaring.",
        "published": "16 Aug 2026 18:38 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Trump mengancam menjadikan Selat Hormuz sebagai wilayah AS: Bolehkah?",
        "url": "https://www.aljazeera.com/news/2026/8/16/trump-threatens-to-make-the-strait-of-hormuz-a-us-territory-can-he?traffic_source=rss",
        "summary": "US president has yet another outlandish threat for Iran, with no end to war in sight.",
        "published": "16 Aug 2026 18:14 WIB",
        "sentiment": "Bearish",
        "score": -0.982,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Mengapa Israel meningkatkan serangan di Lebanon selatan meski gencatan senjata?",
        "url": "https://www.aljazeera.com/news/2026/8/16/why-has-israel-escalated-attacks-in-southern-lebanon-despite-ceasefire?traffic_source=rss",
        "summary": "At least 11 people killed in one day of Israeli attacks despite truce extension brokered by US in June.",
        "published": "16 Aug 2026 17:59 WIB",
        "sentiment": "Bearish",
        "score": -0.963,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Debut Mohamed Salah di Trabzonspor berakhir imbang dengan Kasimpasa",
        "url": "https://www.aljazeera.com/sports/2026/8/16/mohamed-salah-trabzonspor-debut-draw-kasimpasa-turkish-super-lig?traffic_source=rss",
        "summary": "The Egyptian forward, who joined the Turkish club on a free transfer, came off the bench early in the second half.",
        "published": "16 Aug 2026 16:48 WIB",
        "sentiment": "Bullish",
        "score": 0.431,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Inilah alasan sebenarnya mengapa harga minyak tidak bergerak lebih tinggi",
        "url": "https://www.marketwatch.com/story/heres-the-real-reason-oil-prices-arent-moving-higher-256afdbc?mod=mw_rss_topstories",
        "summary": "Oil prices are not higher largely because the world does not want as much oil as it used to — and that’s arguably the more troubling story.",
        "published": "16 Aug 2026 20:00 WIB",
        "sentiment": "Bearish",
        "score": -0.72,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Apakah Anda pikir suku bunga sekarang tinggi? Bagan ini menawarkan perspektif yang berbeda.",
        "url": "https://www.marketwatch.com/story/think-interest-rates-are-high-now-these-charts-offers-a-different-perspective-ae5f28c6?mod=mw_rss_topstories",
        "summary": "Also in Weekend Reads: 10 remarkable housing markets, stock picks, and health-insurance battles.",
        "published": "16 Aug 2026 02:01 WIB",
        "sentiment": "Bullish",
        "score": 0.612,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Cadangan minyak strategis yang menipis mendekati tingkat yang menimbulkan kekhawatiran akan kerusakan pada gua-gua dan operasi",
        "url": "https://www.cnbc.com/2026/08/15/strategic-petroleum-reserve-spr-oil-iran-war-caverns.html",
        "summary": "The rapid drawdown of the U.S. Strategic Petroleum Reserve could damage the caverns that store the oil, experts warn.",
        "published": "15 Aug 2026 21:19 WIB",
        "sentiment": "Bearish",
        "score": -0.858,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Perekonomian Rusia telah menentang pandangan skeptis. Retakan semakin sulit disembunyikan",
        "url": "https://www.cnbc.com/2026/08/15/ukraine-war-russia-economy-putin-oil.html",
        "summary": "Russia's wartime economy is under growing strain as its budget deficit widens and analysts warn pressure could intensify next year.",
        "published": "15 Aug 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.79,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Panas ekstrem memicu panen Champagne yang paling awal, sehingga menguji rasanya yang terkenal",
        "url": "https://www.cnbc.com/2026/08/15/heatwave-champagne-harvest-climate.html",
        "summary": "Producers of the iconic French fizz face a challenge to preserve its taste profile while they also battle tariff complications and fewer drinkers.",
        "published": "15 Aug 2026 12:00 WIB",
        "sentiment": "Netral",
        "score": -0.026,
        "emoji": "⚪",
        "impact": "medium"
      }
    ]
  },
  "fj_live": {
    "generated": "16 Aug 2026 22:01 WIB",
    "summary": {
      "total": 20,
      "bullish": 3,
      "bearish": 1,
      "netral": 16,
      "avg_score": 0.0417,
      "overall": "Netral"
    },
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Pedagang Menjadi Lebih Pilih-pilih Setelah Pergerakan Besar di Pasar Utang Negara Berkembang senilai $886 Miliar",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/traders-get-pickier-after-big-run-in-886-billion-em-debt-market",
        "summary": "Persistent inflation worries and currency swings are pushing emerging-market investors to adjust bets in an $886 billion asset class that’s been delivering outsize returns for more than a year.",
        "published": "16 Aug 2026 19:30 WIB",
        "sentiment": "Bearish",
        "score": -0.077,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Apa yang Terjadi di EM: Trader Semakin Memilih Linker (Podcast)",
        "url": "https://www.bloomberg.com/news/audio/2026-08-16/what-s-happening-in-em-traders-get-pickier-on-linkers-podcast",
        "summary": "Bogota-based EM reporter Nicolle Yapur joins Leda Alvim to discuss why investors are looking beyond Brazil and Mexico for opportunities in inflation-linked bonds in the emerging world.",
        "published": "16 Aug 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.382,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Obligasi Menghadapi Ancaman yang Lebih Besar Dibandingkan The Fed seiring Meningkatnya Suku Bunga Global",
        "url": "https://www.bloomberg.com/news/articles/2026-08-16/bonds-face-a-bigger-threat-than-the-fed-as-global-rates-climb",
        "summary": "As investors debate whether and when the Federal Reserve will raise interest rates, market expectations for further tightening are building around the world — and spelling trouble for bonds.",
        "published": "16 Aug 2026 19:00 WIB",
        "sentiment": "Bullish",
        "score": 0.157,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Walmart dan Target akan mengungkap kesehatan konsumen AS",
        "url": "https://www.marketwatch.com/story/walmart-and-target-are-about-to-reveal-the-health-of-the-u-s-consumer-d5b89491?mod=mw_rss_topstories",
        "summary": "Earnings reports from the two major retailers will show how shoppers are holding up in an era of persistent inflation.",
        "published": "16 Aug 2026 18:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "PDB per kapita Israel pada kuartal kedua naik 14% secara tahunan: biro statistik",
        "url": "https://www.financialjuice.com/News/9723110/Israel-Q2-per-capita-GDP-up-14-annualised-statistics-bureau.aspx?xy=rss",
        "summary": "",
        "published": "16 Aug 2026 17:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Israel merevisi PDB Q1 menjadi -2,2% secara tahunan: biro statistik",
        "url": "https://www.financialjuice.com/News/9723109/Israel-revises-Q1-GDP-to--22-annualized-statistics-bureau.aspx?xy=rss",
        "summary": "",
        "published": "16 Aug 2026 17:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "PDB Israel Kuartal 2 tumbuh 15,4% secara tahunan kuartal-ke-kuartal menurut perkiraan pertama: Biro Statistik (perkiraan 6,9%)",
        "url": "https://www.financialjuice.com/News/9723108/Israel-Q2-GDP-grows-154-annualized-quarter-on-quarter-in-first-estimate-Statistics-Bureau-forecast-69.aspx?xy=rss",
        "summary": "",
        "published": "16 Aug 2026 17:00 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Forex Hari Ini: Dolar Turun Karena Taruhan Kenaikan Suku Bunga Fed Mendingin, Batasan Kebuntuan di Timur Tengah Bergerak - CryptoRank",
        "url": "https://news.google.com/rss/articles/CBMipgFBVV95cUxQbjZfZGVseWNWbjktRjZnNXFWTHVXOGlVbEFRVThsMzlrZ0ItNnFPcEFJYkkySDUtSmdNTHpCeHlpa2l5STFPbDAxdW9KbU1wM2d0Zk84c251YmptVkEteEtpWEUwcEgzXzBnWHhKN2lGMzJYM2xXcndjZjdhT25DN3BpQnRqUjZZdEs4aXdoOG5hMXZFdGRIWWFyaDZrWFdvanJBTC1R?oc=5",
        "summary": "Forex Today: Dollar Dips as Fed Rate Hike Bets Cool, Mideast Stalemate Caps Moves CryptoRank",
        "published": "16 Aug 2026 06:28 WIB",
        "sentiment": "Bullish",
        "score": 0.398,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "FinancialJuice",
        "title": "Seminggu ke Depan: Imbal Hasil Obligasi Jangka Panjang Meningkat, Ekspektasi Kenaikan Suku Bunga Fed Ditendang - FJElite",
        "url": "https://www.financialjuice.com/News/9722934/Week-Ahead-Long-Dated-Bond-Yields-Rise-Fed-Hike-Expectation-Kicked-Out----FJElite.aspx?xy=rss",
        "summary": "",
        "published": "16 Aug 2026 06:03 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "PDB Peru tumbuh 1,75% pada bulan Juni dibandingkan tahun sebelumnya: pemerintah",
        "url": "https://www.financialjuice.com/News/9722816/Perus-GDP-grows-175-in-June-vs-a-year-earlier-government.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 22:04 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Panas ekstrem memicu panen Champagne yang paling awal, sehingga menguji rasanya yang terkenal",
        "url": "https://www.cnbc.com/2026/08/15/heatwave-champagne-harvest-climate.html",
        "summary": "Producers of the iconic French fizz face a challenge to preserve its taste profile while they also battle tariff complications and fewer drinkers.",
        "published": "15 Aug 2026 12:00 WIB",
        "sentiment": "Netral",
        "score": -0.026,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "FinancialJuice",
        "title": "Neraca Perdagangan Korea Selatan Revisi Realisasi 30,39 miliar (Perkiraan -, Sebelumnya 30,32 miliar)",
        "url": "https://www.financialjuice.com/News/9722418/S-Korean-Trade-Balance-Revised-Actual-3039B-Forecast---Previous-3032B.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 07:15 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CFTC USD 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722237/USD-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Pekan Posisi CFTC EUR 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722227/EUR-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CFTC AUD 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722226/AUD-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CFTC JPY 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722225/JPY-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CFTC GBP 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722222/GBP-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Pekan Posisi CFTC CHF 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722221/CHF-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CFTC NZD 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722220/NZD-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "Minggu Posisi CAD CFTC 11 Agustus - FJElite",
        "url": "https://www.financialjuice.com/News/9722219/CAD-CFTC-Positions-Week-August-11th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "15 Aug 2026 03:16 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      }
    ]
  },
  "rekomendasi": {
    "generated": "16 Aug 2026 22:01 WIB",
    "pairs": [
      {
        "label": "USD/CHF",
        "score": 47,
        "direction": "BUY",
        "rsi": 51.5,
        "last_close": "0.81300",
        "smma7": "0.81278",
        "ema9": "0.81280",
        "atr14": "0.00085",
        "bars_since_cross": 1,
        "cross_label": "1 candle lalu",
        "freshness_score": 45,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.338,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.338,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/GBP",
        "score": 43,
        "direction": "BUY",
        "rsi": 54.2,
        "last_close": "0.85477",
        "smma7": "0.85464",
        "ema9": "0.85466",
        "atr14": "0.00037",
        "bars_since_cross": 2,
        "cross_label": "2 candle lalu",
        "freshness_score": 40,
        "separation_score": 1,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/JPY",
        "score": 38,
        "direction": "BUY",
        "rsi": 52.3,
        "last_close": "159.305",
        "smma7": "159.263",
        "ema9": "159.275",
        "atr14": "0.140",
        "bars_since_cross": 3,
        "cross_label": "3 candle lalu",
        "freshness_score": 35,
        "separation_score": 2,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.338,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.338,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/AUD",
        "score": 38,
        "direction": "SELL",
        "rsi": 46.2,
        "last_close": "1.91052",
        "smma7": "1.91082",
        "ema9": "1.91073",
        "atr14": "0.00153",
        "bars_since_cross": 3,
        "cross_label": "3 candle lalu",
        "freshness_score": 35,
        "separation_score": 1,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CAD",
        "score": 37,
        "direction": "SELL",
        "rsi": 42.3,
        "last_close": "1.87773",
        "smma7": "1.87829",
        "ema9": "1.87815",
        "atr14": "0.00131",
        "bars_since_cross": 4,
        "cross_label": "4 candle lalu",
        "freshness_score": 30,
        "separation_score": 3,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/CAD",
        "score": 37,
        "direction": "SELL",
        "rsi": 39.8,
        "last_close": "0.98194",
        "smma7": "0.98273",
        "ema9": "0.98264",
        "atr14": "0.00147",
        "bars_since_cross": 4,
        "cross_label": "4 candle lalu",
        "freshness_score": 30,
        "separation_score": 2,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CAD",
        "score": 35,
        "direction": "SELL",
        "rsi": 43.9,
        "last_close": "1.60490",
        "smma7": "1.60529",
        "ema9": "1.60518",
        "atr14": "0.00131",
        "bars_since_cross": 4,
        "cross_label": "4 candle lalu",
        "freshness_score": 30,
        "separation_score": 2,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CHF",
        "score": 24,
        "direction": "BUY",
        "rsi": 79.7,
        "last_close": "0.47898",
        "smma7": "0.47840",
        "ema9": "0.47861",
        "atr14": "0.00060",
        "bars_since_cross": 28,
        "cross_label": "28 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 15,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/JPY",
        "score": 22,
        "direction": "BUY",
        "rsi": 69.9,
        "last_close": "93.884",
        "smma7": "93.744",
        "ema9": "93.791",
        "atr14": "0.094",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 12,
        "rsi_score": 10,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/USD",
        "score": 21,
        "direction": "BUY",
        "rsi": 67.5,
        "last_close": "0.58938",
        "smma7": "0.58879",
        "ema9": "0.58904",
        "atr14": "0.00050",
        "bars_since_cross": 31,
        "cross_label": "31 candle lalu",
        "freshness_score": 0,
        "separation_score": 12,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.338,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.338,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/JPY",
        "score": 18,
        "direction": "BUY",
        "rsi": 66.1,
        "last_close": "184.365",
        "smma7": "184.204",
        "ema9": "184.261",
        "atr14": "0.139",
        "bars_since_cross": 35,
        "cross_label": "35 candle lalu",
        "freshness_score": 0,
        "separation_score": 10,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CAD",
        "score": 17,
        "direction": "SELL",
        "rsi": 31.4,
        "last_close": "1.38720",
        "smma7": "1.38802",
        "ema9": "1.38764",
        "atr14": "0.00124",
        "bars_since_cross": 30,
        "cross_label": "30 candle lalu",
        "freshness_score": 0,
        "separation_score": 8,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.338,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.338,
          "quote_score": 0.0,
          "base_count": 2,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/JPY",
        "score": 17,
        "direction": "BUY",
        "rsi": 65.9,
        "last_close": "114.818",
        "smma7": "114.732",
        "ema9": "114.772",
        "atr14": "0.113",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/USD",
        "score": 16,
        "direction": "BUY",
        "rsi": 63.5,
        "last_close": "1.15727",
        "smma7": "1.15685",
        "ema9": "1.15709",
        "atr14": "0.00070",
        "bars_since_cross": 22,
        "cross_label": "22 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 7,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.359,
          "confidence": "Kuat",
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": -0.021,
          "quote_score": 0.338,
          "base_count": 3,
          "quote_count": 2,
          "base_insufficient": false,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/NZD",
        "score": 16,
        "direction": "SELL",
        "rsi": 32.9,
        "last_close": "1.96318",
        "smma7": "1.96449",
        "ema9": "1.96406",
        "atr14": "0.00165",
        "bars_since_cross": 27,
        "cross_label": "27 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 9,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/USD",
        "score": 16,
        "direction": "BUY",
        "rsi": 63.1,
        "last_close": "0.70867",
        "smma7": "0.70838",
        "ema9": "0.70855",
        "atr14": "0.00048",
        "bars_since_cross": 31,
        "cross_label": "31 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 7,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.338,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.338,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/JPY",
        "score": 16,
        "direction": "BUY",
        "rsi": 64.7,
        "last_close": "112.879",
        "smma7": "112.781",
        "ema9": "112.817",
        "atr14": "0.106",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 9,
        "rsi_score": 7,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CHF/JPY",
        "score": 16,
        "direction": "BUY",
        "rsi": 50.0,
        "last_close": "195.916",
        "smma7": "195.926",
        "ema9": "195.935",
        "atr14": "0.176",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/JPY",
        "score": 15,
        "direction": "BUY",
        "rsi": 63.4,
        "last_close": "215.667",
        "smma7": "215.521",
        "ema9": "215.581",
        "atr14": "0.179",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 8,
        "rsi_score": 7,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CHF",
        "score": 14,
        "direction": "BUY",
        "rsi": 65.1,
        "last_close": "0.94055",
        "smma7": "0.94003",
        "ema9": "0.94025",
        "atr14": "0.00095",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/NZD",
        "score": 14,
        "direction": "SELL",
        "rsi": 33.9,
        "last_close": "1.20181",
        "smma7": "1.20276",
        "ema9": "1.20250",
        "atr14": "0.00113",
        "bars_since_cross": 26,
        "cross_label": "26 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/USD",
        "score": 12,
        "direction": "BUY",
        "rsi": 60.3,
        "last_close": "1.35358",
        "smma7": "1.35328",
        "ema9": "1.35354",
        "atr14": "0.00092",
        "bars_since_cross": 18,
        "cross_label": "18 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.338,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.338,
          "base_count": 0,
          "quote_count": 2,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CHF",
        "score": 11,
        "direction": "BUY",
        "rsi": 63.0,
        "last_close": "1.10033",
        "smma7": "1.09977",
        "ema9": "1.10000",
        "atr14": "0.00116",
        "bars_since_cross": 27,
        "cross_label": "27 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CAD",
        "score": 8,
        "direction": "BUY",
        "rsi": 59.4,
        "last_close": "0.81729",
        "smma7": "0.81700",
        "ema9": "0.81711",
        "atr14": "0.00095",
        "bars_since_cross": 21,
        "cross_label": "21 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/CHF",
        "score": 7,
        "direction": "BUY",
        "rsi": 57.0,
        "last_close": "0.58543",
        "smma7": "0.58543",
        "ema9": "0.58558",
        "atr14": "0.00118",
        "bars_since_cross": 28,
        "cross_label": "28 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/AUD",
        "score": 4,
        "direction": "SELL",
        "rsi": 43.3,
        "last_close": "1.63276",
        "smma7": "1.63311",
        "ema9": "1.63305",
        "atr14": "0.00127",
        "bars_since_cross": 16,
        "cross_label": "16 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.021,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": -0.021,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      }
    ],
    "total": 26
  }
};
