// Diperbarui: 21 Jun 2026 07:01 WIB
window.FK_DATA = {
  "generated": "21 Jun 2026 07:01 WIB",
  "kalender": {
    "generated": "21 Jun 2026 07:01 WIB",
    "events": [
      {
        "date": "2026-06-14",
        "day": "Minggu",
        "time_wib": "04:30",
        "currency": "NZD",
        "impact": "low",
        "event": "BusinessNZ Services Index",
        "actual": "47.5",
        "forecast": "",
        "previous": "48.7"
      },
      {
        "date": "2026-06-14",
        "day": "Minggu",
        "time_wib": "05:01",
        "currency": "GBP",
        "impact": "low",
        "event": "Rightmove HPI m/m",
        "actual": "-0.6%",
        "forecast": "",
        "previous": "1.2%"
      },
      {
        "date": "2026-06-14",
        "day": "Minggu",
        "time_wib": "10:30",
        "currency": "JPY",
        "impact": "low",
        "event": "Tertiary Industry Activity m/m",
        "actual": "1.3%",
        "forecast": "0.5%",
        "previous": "-0.6%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "12:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German WPI m/m",
        "actual": "-0.6%",
        "forecast": "0.8%",
        "previous": "2.0%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "12:30",
        "currency": "CHF",
        "impact": "low",
        "event": "PPI m/m",
        "actual": "-0.4%",
        "forecast": "0.4%",
        "previous": "0.8%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "13:00",
        "currency": "CHF",
        "impact": "low",
        "event": "SECO Consumer Climate",
        "actual": "-38",
        "forecast": "-38",
        "previous": "-40"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German Buba President Nagel Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "13:30",
        "currency": "EUR",
        "impact": "medium",
        "event": "ECB President Lagarde Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "14:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Italian Trade Balance",
        "actual": "4.29B",
        "forecast": "5.19B",
        "previous": "4.81B"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "Day 1",
        "currency": "ALL",
        "impact": "low",
        "event": "G7 Meetings",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Industrial Production m/m",
        "actual": "0.1%",
        "forecast": "0.2%",
        "previous": "0.4%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Trade Balance",
        "actual": "1.3B",
        "forecast": "7.8B",
        "previous": "0.6B"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "18:15",
        "currency": "CAD",
        "impact": "low",
        "event": "Housing Starts",
        "actual": "261K",
        "forecast": "255K",
        "previous": "278K"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "low",
        "event": "Manufacturing Sales m/m",
        "actual": "4.2%",
        "forecast": "4.4%",
        "previous": "3.4%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "19:30",
        "currency": "CAD",
        "impact": "low",
        "event": "Wholesale Sales m/m",
        "actual": "0.6%",
        "forecast": "0.2%",
        "previous": "1.6%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Empire State Manufacturing Index",
        "actual": "5.7",
        "forecast": "13.2",
        "previous": "19.6"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "19:15",
        "currency": "USD",
        "impact": "low",
        "event": "Capacity Utilization Rate",
        "actual": "76.2%",
        "forecast": "76.2%",
        "previous": "76.1%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Industrial Production m/m",
        "actual": "0.1%",
        "forecast": "0.3%",
        "previous": "0.9%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "20:00",
        "currency": "USD",
        "impact": "low",
        "event": "NAHB Housing Market Index",
        "actual": "35",
        "forecast": "36",
        "previous": "37"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "04:45",
        "currency": "NZD",
        "impact": "low",
        "event": "FPI m/m",
        "actual": "1.0%",
        "forecast": "",
        "previous": "0.0%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "07:30",
        "currency": "CNY",
        "impact": "low",
        "event": "New Home Prices m/m",
        "actual": "-0.20%",
        "forecast": "",
        "previous": "-0.19%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "08:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Fixed Asset Investment ytd/y",
        "actual": "-4.1%",
        "forecast": "-2.3%",
        "previous": "-1.6%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Industrial Production y/y",
        "actual": "4.5%",
        "forecast": "4.4%",
        "previous": "4.1%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "NBS Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Retail Sales y/y",
        "actual": "-0.6%",
        "forecast": "-0.3%",
        "previous": "0.2%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Unemployment Rate",
        "actual": "5.1%",
        "forecast": "5.2%",
        "previous": "5.2%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "09:19",
        "currency": "JPY",
        "impact": "high",
        "event": "BOJ Policy Rate",
        "actual": "<1.00%",
        "forecast": "<1.00%",
        "previous": "<0.75%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "high",
        "event": "Monetary Policy Statement",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "10:30",
        "currency": "AUD",
        "impact": "high",
        "event": "Cash Rate",
        "actual": "4.35%",
        "forecast": "4.35%",
        "previous": "4.35%"
      },
      {
        "date": "2026-06-15",
        "day": "Senin",
        "time_wib": "08:30",
        "currency": "AUD",
        "impact": "high",
        "event": "RBA Rate Statement",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "11:30",
        "currency": "AUD",
        "impact": "high",
        "event": "RBA Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "12:30",
        "currency": "JPY",
        "impact": "high",
        "event": "BOJ Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "Day 2",
        "currency": "ALL",
        "impact": "low",
        "event": "G7 Meetings",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German ZEW Economic Sentiment",
        "actual": "10.5",
        "forecast": "-5.8",
        "previous": "-10.2"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "ZEW Economic Sentiment",
        "actual": "9.5",
        "forecast": "-7.2",
        "previous": "-9.1"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "15:02",
        "currency": "GBP",
        "impact": "low",
        "event": "10-y Bond Auction",
        "actual": "4.86|3.5",
        "forecast": "",
        "previous": "4.98|3.6"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "18:15",
        "currency": "USD",
        "impact": "low",
        "event": "ADP Weekly Employment Change",
        "actual": "25.5K",
        "forecast": "",
        "previous": "29.0K"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "low",
        "event": "Foreign Securities Purchases",
        "actual": "46.91B",
        "forecast": "8.16B",
        "previous": "4.40B"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Building Permits",
        "actual": "1.41M",
        "forecast": "1.42M",
        "previous": "1.42M"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Housing Starts",
        "actual": "1.18M",
        "forecast": "1.43M",
        "previous": "1.39M"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Import Prices m/m",
        "actual": "1.9%",
        "forecast": "0.9%",
        "previous": "2.0%"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "21:14",
        "currency": "NZD",
        "impact": "low",
        "event": "GDT Price Index",
        "actual": "-2.8%",
        "forecast": "",
        "previous": "-0.6%"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "02:30",
        "currency": "USD",
        "impact": "low",
        "event": "API Weekly Statistical Bulletin",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "03:00",
        "currency": "NZD",
        "impact": "low",
        "event": "Westpac Consumer Sentiment",
        "actual": "80.4",
        "forecast": "",
        "previous": "94.7"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "04:45",
        "currency": "NZD",
        "impact": "low",
        "event": "Current Account",
        "actual": "-1.01B",
        "forecast": "-1.01B",
        "previous": "-5.64B"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "05:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Core Machinery Orders m/m",
        "actual": "8.7%",
        "forecast": "1.2%",
        "previous": "-9.4%"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Trade Balance",
        "actual": "-0.09T",
        "forecast": "-0.21T",
        "previous": "0.20T"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "06:30",
        "currency": "AUD",
        "impact": "low",
        "event": "MI Leading Index m/m",
        "actual": "0.0%",
        "forecast": "",
        "previous": "0.1%"
      },
      {
        "date": "2026-06-16",
        "day": "Selasa",
        "time_wib": "07:30",
        "currency": "AUD",
        "impact": "low",
        "event": "RBA Assist Gov Jones Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "12:00",
        "currency": "GBP",
        "impact": "high",
        "event": "CPI y/y",
        "actual": "2.8%",
        "forecast": "3.0%",
        "previous": "2.8%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Core CPI y/y",
        "actual": "2.6%",
        "forecast": "2.7%",
        "previous": "2.5%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "PPI Input m/m",
        "actual": "0.2%",
        "forecast": "0.5%",
        "previous": "2.6%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "PPI Output m/m",
        "actual": "0.5%",
        "forecast": "0.5%",
        "previous": "1.5%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "RPI y/y",
        "actual": "3.1%",
        "forecast": "3.3%",
        "previous": "3.0%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "14:30",
        "currency": "GBP",
        "impact": "low",
        "event": "HPI y/y",
        "actual": "3.8%",
        "forecast": "2.8%",
        "previous": "0.0%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "Day 3",
        "currency": "ALL",
        "impact": "low",
        "event": "G7 Meetings",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Final Core CPI y/y",
        "actual": "2.6%",
        "forecast": "2.5%",
        "previous": "2.5%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Final CPI y/y",
        "actual": "3.2%",
        "forecast": "3.2%",
        "previous": "3.2%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "16:50",
        "currency": "EUR",
        "impact": "medium",
        "event": "ECB President Lagarde Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "low",
        "event": "NHPI m/m",
        "actual": "-0.3%",
        "forecast": "-0.1%",
        "previous": "-0.4%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Core Retail Sales m/m",
        "actual": "0.8%",
        "forecast": "0.6%",
        "previous": "0.7%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Retail Sales m/m",
        "actual": "0.9%",
        "forecast": "0.5%",
        "previous": "0.4%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "20:00",
        "currency": "USD",
        "impact": "low",
        "event": "Business Inventories m/m",
        "actual": "0.5%",
        "forecast": "0.5%",
        "previous": "1.0%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Pending Home Sales m/m",
        "actual": "3.8%",
        "forecast": "0.8%",
        "previous": "0.3%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "20:30",
        "currency": "USD",
        "impact": "low",
        "event": "Crude Oil Inventories",
        "actual": "-8.3M",
        "forecast": "-3.6M",
        "previous": "-7.2M"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "20:45",
        "currency": "USD",
        "impact": "medium",
        "event": "President Trump Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "00:00",
        "currency": "USD",
        "impact": "high",
        "event": "Federal Funds Rate",
        "actual": "3.75%",
        "forecast": "3.75%",
        "previous": "3.75%"
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "high",
        "event": "FOMC Economic Projections",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "high",
        "event": "FOMC Statement",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "00:30",
        "currency": "USD",
        "impact": "high",
        "event": "FOMC Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-17",
        "day": "Rabu",
        "time_wib": "04:45",
        "currency": "NZD",
        "impact": "high",
        "event": "GDP q/q",
        "actual": "0.8%",
        "forecast": "0.8%",
        "previous": "0.5%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "12:00",
        "currency": "GBP",
        "impact": "high",
        "event": "Claimant Count Change",
        "actual": "31.2K",
        "forecast": "25.8K",
        "previous": "8.3K"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "medium",
        "event": "Average Earnings Index 3m/y",
        "actual": "4.4%",
        "forecast": "4.0%",
        "previous": "4.4%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Unemployment Rate",
        "actual": "4.9%",
        "forecast": "5.0%",
        "previous": "5.0%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "CHF",
        "impact": "low",
        "event": "SECO Economic Forecasts",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German Buba President Nagel Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:30",
        "currency": "CHF",
        "impact": "high",
        "event": "SNB Monetary Policy Assessment",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "CHF",
        "impact": "high",
        "event": "SNB Policy Rate",
        "actual": "0.00%",
        "forecast": "0.00%",
        "previous": "0.00%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "14:00",
        "currency": "CHF",
        "impact": "high",
        "event": "SNB Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Current Account",
        "actual": "15.7B",
        "forecast": "18.5B",
        "previous": "14.9B"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "14:36",
        "currency": "EUR",
        "impact": "low",
        "event": "Spanish 10-y Bond Auction",
        "actual": "3.38|1.9",
        "forecast": "",
        "previous": "3.39|2.1"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "16:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German Buba Monthly Report",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "17:00",
        "currency": "GBP",
        "impact": "high",
        "event": "Monetary Policy Summary",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "high",
        "event": "MPC Official Bank Rate Votes",
        "actual": "2-0-7",
        "forecast": "1-0-8",
        "previous": "1-0-8"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "high",
        "event": "Official Bank Rate",
        "actual": "3.75%",
        "forecast": "3.75%",
        "previous": "3.75%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "low",
        "event": "IPPI m/m",
        "actual": "1.2%",
        "forecast": "1.3%",
        "previous": "1.6%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "CAD",
        "impact": "low",
        "event": "RMPI m/m",
        "actual": "0.7%",
        "forecast": "1.1%",
        "previous": "2.6%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Philly Fed Manufacturing Index",
        "actual": "10.3",
        "forecast": "9.8",
        "previous": "-0.4"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Unemployment Claims",
        "actual": "226K",
        "forecast": "225K",
        "previous": "230K"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "20:00",
        "currency": "USD",
        "impact": "low",
        "event": "CB Leading Index m/m",
        "actual": "0.1%",
        "forecast": "0.1%",
        "previous": "0.2%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "20:30",
        "currency": "USD",
        "impact": "low",
        "event": "Natural Gas Storage",
        "actual": "73B",
        "forecast": "82B",
        "previous": "108B"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "02:00",
        "currency": "USD",
        "impact": "low",
        "event": "TIC Long-Term Purchases",
        "actual": "103.1B",
        "forecast": "72.5B",
        "previous": "79.9B"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "04:45",
        "currency": "NZD",
        "impact": "low",
        "event": "Trade Balance",
        "actual": "800M",
        "forecast": "875M",
        "previous": "1598M"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "05:01",
        "currency": "GBP",
        "impact": "low",
        "event": "GfK Consumer Confidence",
        "actual": "-23",
        "forecast": "-23",
        "previous": "-23"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "Sepanjang Hari",
        "currency": "CNY",
        "impact": "holiday",
        "event": "Bank Holiday",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "05:30",
        "currency": "JPY",
        "impact": "low",
        "event": "National Core CPI y/y",
        "actual": "1.4%",
        "forecast": "1.4%",
        "previous": "1.4%"
      },
      {
        "date": "2026-06-18",
        "day": "Kamis",
        "time_wib": "05:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Monetary Policy Meeting Minutes",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "12:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German PPI m/m",
        "actual": "0.3%",
        "forecast": "0.7%",
        "previous": "1.2%"
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "medium",
        "event": "Retail Sales m/m",
        "actual": "1.2%",
        "forecast": "0.5%",
        "previous": "-1.0%"
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Public Sector Net Borrowing",
        "actual": "23.3B",
        "forecast": "19.0B",
        "previous": "23.0B"
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "Sepanjang Hari",
        "currency": "USD",
        "impact": "holiday",
        "event": "Bank Holiday",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "low",
        "event": "Core Retail Sales m/m",
        "actual": "0.1%",
        "forecast": "0.8%",
        "previous": "1.2%"
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "19:30",
        "currency": "CAD",
        "impact": "low",
        "event": "Retail Sales m/m",
        "actual": "0.5%",
        "forecast": "0.6%",
        "previous": "0.9%"
      },
      {
        "date": "2026-06-19",
        "day": "Jumat",
        "time_wib": "20:30",
        "currency": "AUD",
        "impact": "low",
        "event": "CB Leading Index m/m",
        "actual": "0.3%",
        "forecast": "",
        "previous": "-0.7%"
      }
    ]
  },
  "sentimen": {
    "generated": "21 Jun 2026 07:01 WIB",
    "summary": {
      "total": 33,
      "bullish": 9,
      "bearish": 20,
      "netral": 4,
      "avg_score": -0.2686,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "USD",
          "sentiment": "Bullish",
          "score": 0.871,
          "count": 1
        },
        {
          "currency": "AUD",
          "sentiment": "Bearish",
          "score": -0.783,
          "count": 1
        }
      ]
    },
    "items": [
      {
        "source": "ForexLive",
        "title": "Komando militer Iran mengatakan pihaknya menutup Selat Hormuz karena pelanggaran gencatan senjata",
        "url": "https://investinglive.com/news/iran-military-command-says-its-closing-the-strait-of-hormuz-due-to-ceasefire-violations-20260620/",
        "summary": "Iran's Khatam-al Anbiya HQ announced that the Strait of Hormuz will be closed to all maritime traffic. The military headquarters cites US breaches of the war-ending deal and ongoing Israeli ceasefire violations, along with the non-withdrawal in Lebanon. They warned this is only the \"first step.\" The",
        "published": "20 Jun 2026 20:30 WIB",
        "sentiment": "Bearish",
        "score": -0.875,
        "emoji": "🔴"
      },
      {
        "source": "FXStreet News",
        "title": "Breaking: Iran menutup Selat Hormuz di tengah pelanggaran perjanjian gencatan senjata",
        "url": "https://www.fxstreet.com/news/breaking-iran-closes-the-strait-of-hormuz-amid-ceasefire-deal-violation-202606201419",
        "summary": "Iran says it is closing the Strait of Hormuz after accusing the United States (US) and Israel of violating the ceasefire. According to Iran, the decision came over the continued Israeli strikes in Lebanon.",
        "published": "20 Jun 2026 21:22 WIB",
        "sentiment": "Bearish",
        "score": -0.636,
        "emoji": "🔴"
      },
      {
        "source": "Investing.com Forex",
        "title": "Saham Rusia melemah pada penutupan perdagangan; Indeks MOEX Rusia tidak berubah",
        "url": "https://www.investing.com/news/stock-market-news/russia-stocks-lower-at-close-of-trade-moex-russia-index-unchanged-4751633",
        "summary": "",
        "published": "21 Jun 2026 04:20 WIB",
        "sentiment": "Bearish",
        "score": -0.296,
        "emoji": "🔴"
      },
      {
        "source": "Investing.com Forex",
        "title": "Wanita tewas, 1.700 orang dievakuasi dalam kebakaran hotel pantai di Republik Dominika",
        "url": "https://www.investing.com/news/stock-market-news/woman-killed-1700-evacuated-in-beach-hotel-fire-in-dominican-republic-4751586",
        "summary": "",
        "published": "20 Jun 2026 22:18 WIB",
        "sentiment": "Bearish",
        "score": -0.784,
        "emoji": "🔴"
      },
      {
        "source": "Investing.com Forex",
        "title": "Bagaimana kekuatan KOSPI menjadi kelemahan KRW: BofA mempertimbangkannya",
        "url": "https://www.investing.com/news/stock-market-news/how-kospi-strength-became-krw-weakness-bofa-weighs-in-4751616",
        "summary": "",
        "published": "20 Jun 2026 18:49 WIB",
        "sentiment": "Netral",
        "score": 0.023,
        "emoji": "⚪"
      },
      {
        "source": "Investing.com Forex",
        "title": "Goldman Sachs memangkas perkiraan pasar ponsel pintar global karena biaya memori yang tinggi",
        "url": "https://www.investing.com/news/stock-market-news/goldman-sachs-trims-global-smartphone-market-estimates-on-high-memory-costs-4751615",
        "summary": "",
        "published": "20 Jun 2026 18:32 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪"
      },
      {
        "source": "Investing.com Forex",
        "title": "CEO Porsche bertujuan untuk menyelesaikan paket pemotongan biaya baru pada bulan Juli, FAS melaporkan",
        "url": "https://www.investing.com/news/stock-market-news/porsche-ceo-aims-to-finalise-new-costcutting-package-by-july-fas-reports-4751602",
        "summary": "",
        "published": "20 Jun 2026 12:24 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪"
      },
      {
        "source": "Investing.com Economy",
        "title": "Kerajaan bisnis Garda Iran akan meraih keuntungan besar jika sanksi AS dicabut",
        "url": "https://www.investing.com/news/economic-indicators/iranian-guards-business-empire-to-win-big-if-us-sanctions-lifted-4751596",
        "summary": "",
        "published": "20 Jun 2026 10:12 WIB",
        "sentiment": "Bullish",
        "score": 0.506,
        "emoji": "🟢"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Indeks Favorit Fed Terlihat Menunjukkan Inflasi Lebih Cepat",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/fed-s-favorite-gauge-is-seen-showing-faster-inflation",
        "summary": "The latest update to the Federal Reserve’s favorite inflation gauge is unlikely to challenge a growing consensus at the US central bank around the need for interest-rate hikes this year.",
        "published": "21 Jun 2026 03:00 WIB",
        "sentiment": "Bullish",
        "score": 0.871,
        "emoji": "🟢"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Lula dari Brasil Memimpin Melawan Bolsonaro Setelah Skandal Bank",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/brazil-lula-maintains-lead-against-bolsonaro-after-bank-scandal",
        "summary": "President Luiz Inacio Lula da Silva maintained his lead in polls on the Brazilian presidential election against Senator Flavio Bolsonaro, who is weighed down by his ties to a former banker involved in the country’s biggest bank fraud scandal.",
        "published": "20 Jun 2026 23:30 WIB",
        "sentiment": "Bearish",
        "score": -0.783,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Sanksi Iran Kehilangan Kemanjuran",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/iran-sanctions-losing-efficacy-video",
        "summary": "In 2015, sanctions played a key role in bringing Iran to the negotiating table but now warfare has been the primary tool. Oliver Wyman Partner and Global Anti-Financial Crime Practice Leader Daniel Tannebaum explains to David Gura and Christina Ruffini on Bloomberg This Weekend how even if sanctions",
        "published": "20 Jun 2026 22:50 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Rep Warnock: Wall Street vs Main Street",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/rep-warnock-wall-street-vs-main-street-video",
        "summary": "Senator Raphael Warnock (D-GA) tells David Gura on Bloomberg This Weekend that the focus of the country should be on how local Main Streets are doing, not on well Wall Street is doing. Watch part one of Senator Warnock's interview now and tune in to Bloomberg This Weekend tomorrow for part two. (Sou",
        "published": "20 Jun 2026 22:26 WIB",
        "sentiment": "Bearish",
        "score": -0.286,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Kganyago Afrika Selatan Memperingatkan Ekspektasi Inflasi Meningkat",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/south-africa-central-bank-warns-it-must-act-on-rising-price-expectations",
        "summary": "South Africa’s central bank governor said policymakers are seeing early signs of second-round inflation effects as underlying price pressures build, emphasizing the need to act.",
        "published": "20 Jun 2026 21:50 WIB",
        "sentiment": "Bearish",
        "score": -0.482,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "KTT Reindustrialisasi: 'Bangun, Sayang, Bangun'",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/the-reindustrialize-summit-build-baby-build-video",
        "summary": "At the Reindustrialize Summit in Detroit, industrial leaders, White House officials, and major investors convened to emphasize the critical role of manufacturing in reinforcing national and military strength. Axios Defense reporter Colin Demarest joins David Gura and Christina Ruffini on Bloomberg T",
        "published": "20 Jun 2026 21:39 WIB",
        "sentiment": "Bullish",
        "score": 0.34,
        "emoji": "🟢"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Burnham Mungkin Akan Menulis Ulang Pedoman Fiskal Inggris Jika Dia Menjadi PM",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/burnham-may-yet-rewrite-uk-fiscal-rules-if-he-becomes-premier",
        "summary": "After Andy Burnham took a giant leap toward becoming the UK’s next leader, focus is turning to how the team he’s assembling could shape the country’s economic policies.",
        "published": "20 Jun 2026 13:00 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Trump Mencari Offramp Iran",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/trump-seeks-iran-offramp-video",
        "summary": "President and Founder of Eurasia Group and GZERO Media Ian Bremmer joins David Gura and Christina Ruffini on Bloomberg This Weekend to discuss how in the face of the United States failing to achieve any of the war goals given at the beginning of the conflict, President Trump is looking to put Iran b",
        "published": "20 Jun 2026 19:33 WIB",
        "sentiment": "Bearish",
        "score": -0.932,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Delegasi AS-Iran Diharapkan di Swiss",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/us-iran-delegations-expected-in-switzerland-video",
        "summary": "Three days after President Trump signed an agreement with Iran, Switzerland is playing host for diplomatic talks with the United States, Iran, Pakistan, and Qatar in attendance. The Associated Press's International Correspondent Philip Crowther joins Bloomberg This Weekend with hosts David Gura and ",
        "published": "20 Jun 2026 19:20 WIB",
        "sentiment": "Bullish",
        "score": 0.729,
        "emoji": "🟢"
      },
      {
        "source": "BBC World",
        "title": "Iran mengatakan telah menutup Selat Hormuz karena serangan Israel di Lebanon",
        "url": "https://www.bbc.com/news/articles/cwyekkwm1mmo?at_medium=RSS&at_campaign=rss",
        "summary": "The US military has disputed Tehran's claim, which comes ahead of US-Iran talks in Switzerland on Sunday.",
        "published": "21 Jun 2026 04:11 WIB",
        "sentiment": "Bearish",
        "score": -0.729,
        "emoji": "🔴"
      },
      {
        "source": "BBC World",
        "title": "Meloni meminta Trump untuk 'fokus pada popularitasnya sendiri' saat pertikaian meningkat",
        "url": "https://www.bbc.com/news/articles/cgqj77909jpo?at_medium=RSS&at_campaign=rss",
        "summary": "The US president earlier questioned Meloni's popularity after suggesting she \"begged\" for a photo at G7 summit",
        "published": "20 Jun 2026 22:31 WIB",
        "sentiment": "Bullish",
        "score": 0.7,
        "emoji": "🟢"
      },
      {
        "source": "BBC World",
        "title": "Serangan Israel menewaskan enam orang di Gaza termasuk juru kamera Al Jazeera, kata para pejabat",
        "url": "https://www.bbc.com/news/articles/c4gy26p6pwzo?at_medium=RSS&at_campaign=rss",
        "summary": "The Israeli military accused Ahmed Wishah of being a \"Hamas sniper operative\", without providing evidence.",
        "published": "21 Jun 2026 04:57 WIB",
        "sentiment": "Bearish",
        "score": -0.856,
        "emoji": "🔴"
      },
      {
        "source": "BBC World",
        "title": "Zelensky mengembalikan penghargaan tertinggi Polandia setelah penghargaannya dicabut",
        "url": "https://www.bbc.com/news/articles/c2lye7xje9yo?at_medium=RSS&at_campaign=rss",
        "summary": "Ukraine's president said his country was open to \"engagement\" about \"difficult and painful chapters of our shared past\".",
        "published": "20 Jun 2026 23:34 WIB",
        "sentiment": "Bullish",
        "score": 0.722,
        "emoji": "🟢"
      },
      {
        "source": "BBC Top Stories",
        "title": "Pembicaraan tentang Starmer yang bertahan untuk bertarung memudar - dengan cepat",
        "url": "https://www.bbc.com/news/articles/cjeg7p5w4y9o?at_medium=RSS&at_campaign=rss",
        "summary": "After Andy Burnham’s by-election victory, support for the prime minister is evaporating, writes Laura Kuenssberg.",
        "published": "20 Jun 2026 18:33 WIB",
        "sentiment": "Netral",
        "score": 0.026,
        "emoji": "⚪"
      },
      {
        "source": "BBC Top Stories",
        "title": "Peringatan panas ekstrem meluas saat gelombang panas 37C mendekati Inggris",
        "url": "https://www.bbc.com/weather/articles/cp8lye61jk6o?at_medium=RSS&at_campaign=rss",
        "summary": "After a slightly cooler Saturday, temperatures will rise again, possibly touching 36C by Tuesday with a Met Office amber extreme heat warning set to come into force.",
        "published": "21 Jun 2026 03:10 WIB",
        "sentiment": "Bearish",
        "score": -0.655,
        "emoji": "🔴"
      },
      {
        "source": "BBC Top Stories",
        "title": "Seorang pria didakwa setelah diduga melakukan serangan anti-Muslim di Edinburgh",
        "url": "https://www.bbc.com/news/articles/cx2xg6lwz5jo?at_medium=RSS&at_campaign=rss",
        "summary": "Two people were injured close to a mosque and a man was later seen battering the door of a pizzeria as members of the public run away.",
        "published": "21 Jun 2026 06:17 WIB",
        "sentiment": "Bearish",
        "score": -0.887,
        "emoji": "🔴"
      },
      {
        "source": "BBC Top Stories",
        "title": "Steve Rosenberg: Serangan kilang minyak Moskow membuat perang Rusia dengan Ukraina semakin dekat",
        "url": "https://www.bbc.com/news/articles/cp3xqkxp3x5o?at_medium=RSS&at_campaign=rss",
        "summary": "There are moments when life in Moscow feels completely normal - Thursday morning wasn't one of them, writes Steve Rosenberg.",
        "published": "20 Jun 2026 17:19 WIB",
        "sentiment": "Bearish",
        "score": -0.951,
        "emoji": "🔴"
      },
      {
        "source": "BBC Top Stories",
        "title": "Konflik internal yang brutal dan meningkat di Kolombia menentukan pemilihan presidennya",
        "url": "https://www.bbc.com/news/articles/cvgqv8q1ndpo?at_medium=RSS&at_campaign=rss",
        "summary": "A left-wing senator who backs talks with armed gangs faces an outsider endorsed by Trump.",
        "published": "21 Jun 2026 06:17 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Delegasi Iran tiba di Swiss untuk pembicaraan perdamaian AS",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/6/20/iranian-delegation-arrives-in-switzerland-for-us-peace-talks?traffic_source=rss",
        "summary": "Iranian delegation arrives in Switzerland for US peace talks",
        "published": "21 Jun 2026 06:39 WIB",
        "sentiment": "Bullish",
        "score": 0.791,
        "emoji": "🟢"
      },
      {
        "source": "Al Jazeera",
        "title": "Ukraina mengatakan serangan Rusia menewaskan lima orang di Zaporizhzhia",
        "url": "https://www.aljazeera.com/news/2026/6/20/ukraine-says-russian-attack-kills-five-people-in-zaporizhzhia?traffic_source=rss",
        "summary": "During nightly address, Ukrainian President Volodymyr Zelenskyy warns that Russia is preparing for 'massive' attack.",
        "published": "21 Jun 2026 02:31 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Juru kamera Al Jazeera Ahmed Wishah tewas dalam serangan Israel di Gaza",
        "url": "https://www.aljazeera.com/news/2026/6/20/al-jazeera-cameraman-ahmad-wishah-killed-in-israeli-attack-in-gaza?traffic_source=rss",
        "summary": "Al Jazeera condemned Israel's 'deliberate' targeting of Wishah, the network's 12th media worker killed during Gaza war.",
        "published": "21 Jun 2026 01:07 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Pembicaraan AS-Iran akan dimulai hari Minggu di Swiss, kata Pakistan",
        "url": "https://www.aljazeera.com/news/2026/6/20/us-iran-talks-to-kick-off-sunday-in-switzerland-says?traffic_source=rss",
        "summary": "Planned negotiations come amid tensions over Israeli attacks in Lebanon and Iran’s announced closure of Hormuz again.",
        "published": "21 Jun 2026 00:39 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴"
      },
      {
        "source": "MarketWatch",
        "title": "Janji satu halaman yang memaksa penasihat keuangan Anda untuk mengutamakan Anda",
        "url": "https://www.marketwatch.com/story/the-one-page-pledge-that-forces-your-financial-adviser-to-put-you-first-6e88ba07?mod=mw_rss_topstories",
        "summary": "Most investors ignore this abstract legal rule — and it’s fueling a massive wave of fraud.",
        "published": "21 Jun 2026 00:50 WIB",
        "sentiment": "Bearish",
        "score": -0.725,
        "emoji": "🔴"
      },
      {
        "source": "CNBC World",
        "title": "Iran dilaporkan menutup Selat Hormuz lagi saat Vance menuju ke Swiss untuk melakukan pembicaraan",
        "url": "https://www.cnbc.com/2026/06/20/iran-reportedly-closes-strait-of-hormuz-again-raising-doubt-over-talks.html",
        "summary": "Iran's joint military command said the closure was in response to continued Israeli military operations in Lebanon.",
        "published": "21 Jun 2026 05:59 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢"
      },
      {
        "source": "CNBC World",
        "title": "Bonus besar-besaran bagi pekerja chip di Korea Selatan membuat bank sentral waspada terhadap inflasi",
        "url": "https://www.cnbc.com/2026/06/20/south-korea-tech-samsung-sk-hynix-bonus-bank-of-korea.html",
        "summary": "Workers from tech industries receive bonus worth millions of won, prompting the Bank of Korea to warn of the upward pressure to inflation.",
        "published": "20 Jun 2026 15:59 WIB",
        "sentiment": "Bullish",
        "score": 0.826,
        "emoji": "🟢"
      }
    ]
  },
  "geopolitik": {
    "generated": "21 Jun 2026 07:01 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.582,
        "count": 11
      },
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.576,
        "count": 10
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.556,
        "count": 9
      },
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.7,
        "count": 6
      },
      {
        "pair": "GBP/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.379,
        "count": 2
      },
      {
        "pair": "USD/RUB",
        "direction": "Tekanan Turun ▼",
        "score": -1.0,
        "count": 1
      },
      {
        "pair": "EUR",
        "direction": "Tekanan Naik ▲",
        "score": 0.7,
        "count": 1
      },
      {
        "pair": "GBP",
        "direction": "Tekanan Naik ▲",
        "score": 0.7,
        "count": 1
      }
    ],
    "items": [
      {
        "source": "ForexLive",
        "title": "Komando militer Iran mengatakan pihaknya menutup Selat Hormuz karena pelanggaran gencatan senjata",
        "url": "https://investinglive.com/news/iran-military-command-says-its-closing-the-strait-of-hormuz-due-to-ceasefire-violations-20260620/",
        "summary": "Iran's Khatam-al Anbiya HQ announced that the Strait of Hormuz will be closed to all maritime traffic. The military headquarters cites US breaches of the war-ending deal and ongoing Israeli ceasefire violations, along with the non-withdrawal in Lebanon. They warned this is only the \"first step.\" The",
        "published": "20 Jun 2026 20:30 WIB",
        "sentiment": "Bearish",
        "score": -0.875,
        "emoji": "🔴"
      },
      {
        "source": "FXStreet News",
        "title": "Breaking: Iran menutup Selat Hormuz di tengah pelanggaran perjanjian gencatan senjata",
        "url": "https://www.fxstreet.com/news/breaking-iran-closes-the-strait-of-hormuz-amid-ceasefire-deal-violation-202606201419",
        "summary": "Iran says it is closing the Strait of Hormuz after accusing the United States (US) and Israel of violating the ceasefire. According to Iran, the decision came over the continued Israeli strikes in Lebanon.",
        "published": "20 Jun 2026 21:22 WIB",
        "sentiment": "Bearish",
        "score": -0.636,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Lula dari Brasil Memimpin Melawan Bolsonaro Setelah Skandal Bank",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/brazil-lula-maintains-lead-against-bolsonaro-after-bank-scandal",
        "summary": "President Luiz Inacio Lula da Silva maintained his lead in polls on the Brazilian presidential election against Senator Flavio Bolsonaro, who is weighed down by his ties to a former banker involved in the country’s biggest bank fraud scandal.",
        "published": "20 Jun 2026 23:30 WIB",
        "sentiment": "Bearish",
        "score": -0.783,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Sanksi Iran Kehilangan Kemanjuran",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/iran-sanctions-losing-efficacy-video",
        "summary": "In 2015, sanctions played a key role in bringing Iran to the negotiating table but now warfare has been the primary tool. Oliver Wyman Partner and Global Anti-Financial Crime Practice Leader Daniel Tannebaum explains to David Gura and Christina Ruffini on Bloomberg This Weekend how even if sanctions",
        "published": "20 Jun 2026 22:50 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Rep Warnock: Wall Street vs Main Street",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/rep-warnock-wall-street-vs-main-street-video",
        "summary": "Senator Raphael Warnock (D-GA) tells David Gura on Bloomberg This Weekend that the focus of the country should be on how local Main Streets are doing, not on well Wall Street is doing. Watch part one of Senator Warnock's interview now and tune in to Bloomberg This Weekend tomorrow for part two. (Sou",
        "published": "20 Jun 2026 22:26 WIB",
        "sentiment": "Bearish",
        "score": -0.286,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "KTT Reindustrialisasi: 'Bangun, Sayang, Bangun'",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/the-reindustrialize-summit-build-baby-build-video",
        "summary": "At the Reindustrialize Summit in Detroit, industrial leaders, White House officials, and major investors convened to emphasize the critical role of manufacturing in reinforcing national and military strength. Axios Defense reporter Colin Demarest joins David Gura and Christina Ruffini on Bloomberg T",
        "published": "20 Jun 2026 21:39 WIB",
        "sentiment": "Bullish",
        "score": 0.34,
        "emoji": "🟢"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Burnham Mungkin Akan Menulis Ulang Pedoman Fiskal Inggris Jika Dia Menjadi PM",
        "url": "https://www.bloomberg.com/news/articles/2026-06-20/burnham-may-yet-rewrite-uk-fiscal-rules-if-he-becomes-premier",
        "summary": "After Andy Burnham took a giant leap toward becoming the UK’s next leader, focus is turning to how the team he’s assembling could shape the country’s economic policies.",
        "published": "20 Jun 2026 13:00 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Trump Mencari Offramp Iran",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/trump-seeks-iran-offramp-video",
        "summary": "President and Founder of Eurasia Group and GZERO Media Ian Bremmer joins David Gura and Christina Ruffini on Bloomberg This Weekend to discuss how in the face of the United States failing to achieve any of the war goals given at the beginning of the conflict, President Trump is looking to put Iran b",
        "published": "20 Jun 2026 19:33 WIB",
        "sentiment": "Bearish",
        "score": -0.932,
        "emoji": "🔴"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Delegasi AS-Iran Diharapkan di Swiss",
        "url": "https://www.bloomberg.com/news/videos/2026-06-20/us-iran-delegations-expected-in-switzerland-video",
        "summary": "Three days after President Trump signed an agreement with Iran, Switzerland is playing host for diplomatic talks with the United States, Iran, Pakistan, and Qatar in attendance. The Associated Press's International Correspondent Philip Crowther joins Bloomberg This Weekend with hosts David Gura and ",
        "published": "20 Jun 2026 19:20 WIB",
        "sentiment": "Bullish",
        "score": 0.729,
        "emoji": "🟢"
      },
      {
        "source": "BBC World",
        "title": "Iran mengatakan telah menutup Selat Hormuz karena serangan Israel di Lebanon",
        "url": "https://www.bbc.com/news/articles/cwyekkwm1mmo?at_medium=RSS&at_campaign=rss",
        "summary": "The US military has disputed Tehran's claim, which comes ahead of US-Iran talks in Switzerland on Sunday.",
        "published": "21 Jun 2026 04:11 WIB",
        "sentiment": "Bearish",
        "score": -0.729,
        "emoji": "🔴"
      },
      {
        "source": "BBC World",
        "title": "Meloni meminta Trump untuk 'fokus pada popularitasnya sendiri' saat pertikaian meningkat",
        "url": "https://www.bbc.com/news/articles/cgqj77909jpo?at_medium=RSS&at_campaign=rss",
        "summary": "The US president earlier questioned Meloni's popularity after suggesting she \"begged\" for a photo at G7 summit",
        "published": "20 Jun 2026 22:31 WIB",
        "sentiment": "Bullish",
        "score": 0.7,
        "emoji": "🟢"
      },
      {
        "source": "BBC World",
        "title": "Serangan Israel menewaskan enam orang di Gaza termasuk juru kamera Al Jazeera, kata para pejabat",
        "url": "https://www.bbc.com/news/articles/c4gy26p6pwzo?at_medium=RSS&at_campaign=rss",
        "summary": "The Israeli military accused Ahmed Wishah of being a \"Hamas sniper operative\", without providing evidence.",
        "published": "21 Jun 2026 04:57 WIB",
        "sentiment": "Bearish",
        "score": -0.856,
        "emoji": "🔴"
      },
      {
        "source": "BBC Top Stories",
        "title": "Pembicaraan tentang Starmer yang bertahan untuk bertarung memudar - dengan cepat",
        "url": "https://www.bbc.com/news/articles/cjeg7p5w4y9o?at_medium=RSS&at_campaign=rss",
        "summary": "After Andy Burnham’s by-election victory, support for the prime minister is evaporating, writes Laura Kuenssberg.",
        "published": "20 Jun 2026 18:33 WIB",
        "sentiment": "Netral",
        "score": 0.026,
        "emoji": "⚪"
      },
      {
        "source": "BBC Top Stories",
        "title": "Peringatan panas ekstrem meluas saat gelombang panas 37C mendekati Inggris",
        "url": "https://www.bbc.com/weather/articles/cp8lye61jk6o?at_medium=RSS&at_campaign=rss",
        "summary": "After a slightly cooler Saturday, temperatures will rise again, possibly touching 36C by Tuesday with a Met Office amber extreme heat warning set to come into force.",
        "published": "21 Jun 2026 03:10 WIB",
        "sentiment": "Bearish",
        "score": -0.655,
        "emoji": "🔴"
      },
      {
        "source": "BBC Top Stories",
        "title": "Konflik internal yang brutal dan meningkat di Kolombia menentukan pemilihan presidennya",
        "url": "https://www.bbc.com/news/articles/cvgqv8q1ndpo?at_medium=RSS&at_campaign=rss",
        "summary": "A left-wing senator who backs talks with armed gangs faces an outsider endorsed by Trump.",
        "published": "21 Jun 2026 06:17 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Delegasi Iran tiba di Swiss untuk pembicaraan perdamaian AS",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/6/20/iranian-delegation-arrives-in-switzerland-for-us-peace-talks?traffic_source=rss",
        "summary": "Iranian delegation arrives in Switzerland for US peace talks",
        "published": "21 Jun 2026 06:39 WIB",
        "sentiment": "Bullish",
        "score": 0.791,
        "emoji": "🟢"
      },
      {
        "source": "Al Jazeera",
        "title": "Ukraina mengatakan serangan Rusia menewaskan lima orang di Zaporizhzhia",
        "url": "https://www.aljazeera.com/news/2026/6/20/ukraine-says-russian-attack-kills-five-people-in-zaporizhzhia?traffic_source=rss",
        "summary": "During nightly address, Ukrainian President Volodymyr Zelenskyy warns that Russia is preparing for 'massive' attack.",
        "published": "21 Jun 2026 02:31 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Juru kamera Al Jazeera Ahmed Wishah tewas dalam serangan Israel di Gaza",
        "url": "https://www.aljazeera.com/news/2026/6/20/al-jazeera-cameraman-ahmad-wishah-killed-in-israeli-attack-in-gaza?traffic_source=rss",
        "summary": "Al Jazeera condemned Israel's 'deliberate' targeting of Wishah, the network's 12th media worker killed during Gaza war.",
        "published": "21 Jun 2026 01:07 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴"
      },
      {
        "source": "Al Jazeera",
        "title": "Pembicaraan AS-Iran akan dimulai hari Minggu di Swiss, kata Pakistan",
        "url": "https://www.aljazeera.com/news/2026/6/20/us-iran-talks-to-kick-off-sunday-in-switzerland-says?traffic_source=rss",
        "summary": "Planned negotiations come amid tensions over Israeli attacks in Lebanon and Iran’s announced closure of Hormuz again.",
        "published": "21 Jun 2026 00:39 WIB",
        "sentiment": "Bearish",
        "score": -0.761,
        "emoji": "🔴"
      },
      {
        "source": "CNBC World",
        "title": "Iran dilaporkan menutup Selat Hormuz lagi saat Vance menuju ke Swiss untuk melakukan pembicaraan",
        "url": "https://www.cnbc.com/2026/06/20/iran-reportedly-closes-strait-of-hormuz-again-raising-doubt-over-talks.html",
        "summary": "Iran's joint military command said the closure was in response to continued Israeli military operations in Lebanon.",
        "published": "21 Jun 2026 05:59 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢"
      },
      {
        "source": "CNBC World",
        "title": "Bonus besar-besaran bagi pekerja chip di Korea Selatan membuat bank sentral waspada terhadap inflasi",
        "url": "https://www.cnbc.com/2026/06/20/south-korea-tech-samsung-sk-hynix-bonus-bank-of-korea.html",
        "summary": "Workers from tech industries receive bonus worth millions of won, prompting the Bank of Korea to warn of the upward pressure to inflation.",
        "published": "20 Jun 2026 15:59 WIB",
        "sentiment": "Bullish",
        "score": 0.826,
        "emoji": "🟢"
      }
    ]
  },
  "fj_live": {
    "generated": "21 Jun 2026 07:01 WIB",
    "summary": {
      "total": 1,
      "bullish": 0,
      "bearish": 0,
      "netral": 1,
      "avg_score": 0.0,
      "overall": "Netral"
    },
    "items": [
      {
        "source": "FinancialJuice",
        "title": "Xiao-i Corp: pengadilan menolak permintaan Apple sebesar 2 juta rmb untuk biaya hukum",
        "url": "https://www.financialjuice.com/News/9644565/Xiao-i-Corp-court-denies-Apples-request-for-2-mln-rmb-in-legal-costs.aspx?xy=rss",
        "summary": "",
        "published": "20 Jun 2026 04:02 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪"
      }
    ]
  },
  "rekomendasi": {
    "generated": "21 Jun 2026 07:01 WIB",
    "pairs": [
      {
        "label": "EUR/NZD",
        "score": 71,
        "direction": "BUY",
        "rsi": 62.0,
        "last_close": "1.99741",
        "sma20": "1.99272",
        "sma50": "1.98972",
        "sma200": "1.97974",
        "bull": 5,
        "bear": 0,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "AUD/USD",
        "score": 69,
        "direction": "SELL",
        "rsi": 42.0,
        "last_close": "0.70156",
        "sma20": "0.70326",
        "sma50": "0.70389",
        "sma200": "0.71361",
        "bull": 0,
        "bear": 5,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -1.654,
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Bullish",
          "base_score": -0.783,
          "quote_score": 0.871,
          "base_count": 1,
          "quote_count": 1
        }
      },
      {
        "label": "NZD/USD",
        "score": 68,
        "direction": "SELL",
        "rsi": 32.8,
        "last_close": "0.57422",
        "sma20": "0.57761",
        "sma50": "0.58038",
        "sma200": "0.58737",
        "bull": 0,
        "bear": 5,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.871,
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.871,
          "base_count": 0,
          "quote_count": 1
        }
      },
      {
        "label": "USD/JPY",
        "score": 67,
        "direction": "BUY",
        "rsi": 64.5,
        "last_close": "161.275",
        "sma20": "160.863",
        "sma50": "160.530",
        "sma200": "159.211",
        "bull": 5,
        "bear": 0,
        "total_sigs": 5,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.871,
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.871,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "CHF/JPY",
        "score": 66,
        "direction": "SELL",
        "rsi": 36.5,
        "last_close": "199.849",
        "sma20": "200.828",
        "sma50": "201.096",
        "sma200": "201.863",
        "bull": 0,
        "bear": 5,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "USD/CAD",
        "score": 65,
        "direction": "BUY",
        "rsi": 71.6,
        "last_close": "1.41520",
        "sma20": "1.40996",
        "sma50": "1.40222",
        "sma200": "1.38411",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.871,
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.871,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "EUR/CHF",
        "score": 63,
        "direction": "BUY",
        "rsi": 67.8,
        "last_close": "0.92522",
        "sma20": "0.92164",
        "sma50": "0.92156",
        "sma200": "0.91673",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "CAD/JPY",
        "score": 62,
        "direction": "SELL",
        "rsi": 42.5,
        "last_close": "113.939",
        "sma20": "114.087",
        "sma50": "114.480",
        "sma200": "115.025",
        "bull": 0,
        "bear": 5,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "GBP/USD",
        "score": 61,
        "direction": "SELL",
        "rsi": 34.9,
        "last_close": "1.32371",
        "sma20": "1.32898",
        "sma50": "1.33576",
        "sma200": "1.34364",
        "bull": 1,
        "bear": 4,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.871,
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.871,
          "base_count": 0,
          "quote_count": 1
        }
      },
      {
        "label": "EUR/USD",
        "score": 60,
        "direction": "SELL",
        "rsi": 36.3,
        "last_close": "1.14692",
        "sma20": "1.15209",
        "sma50": "1.15521",
        "sma200": "1.16305",
        "bull": 1,
        "bear": 4,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.871,
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.871,
          "base_count": 0,
          "quote_count": 1
        }
      },
      {
        "label": "NZD/JPY",
        "score": 58,
        "direction": "SELL",
        "rsi": 39.7,
        "last_close": "92.595",
        "sma20": "92.882",
        "sma50": "93.131",
        "sma200": "93.473",
        "bull": 1,
        "bear": 4,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "USD/CHF",
        "score": 57,
        "direction": "BUY",
        "rsi": 68.5,
        "last_close": "0.80640",
        "sma20": "0.80090",
        "sma50": "0.79819",
        "sma200": "0.78863",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.871,
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.871,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "GBP/CHF",
        "score": 52,
        "direction": "BUY",
        "rsi": 61.9,
        "last_close": "1.06764",
        "sma20": "1.06426",
        "sma50": "1.06606",
        "sma200": "1.05947",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "EUR/JPY",
        "score": 47,
        "direction": "SELL",
        "rsi": 46.8,
        "last_close": "184.998",
        "sma20": "185.225",
        "sma50": "185.366",
        "sma200": "185.085",
        "bull": 1,
        "bear": 4,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "EUR/CAD",
        "score": 46,
        "direction": "BUY",
        "rsi": 52.0,
        "last_close": "1.62254",
        "sma20": "1.62286",
        "sma50": "1.61876",
        "sma200": "1.60879",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "AUD/JPY",
        "score": 45,
        "direction": "BUY",
        "rsi": 50.8,
        "last_close": "113.122",
        "sma20": "113.091",
        "sma50": "112.955",
        "sma200": "113.562",
        "bull": 4,
        "bear": 1,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.783,
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.783,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "AUD/NZD",
        "score": 30,
        "direction": "WAIT",
        "rsi": 69.8,
        "last_close": "1.22117",
        "sma20": "1.21733",
        "sma50": "1.21264",
        "sma200": "1.21473",
        "bull": 3,
        "bear": 2,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.783,
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.783,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "CAD/CHF",
        "score": 27,
        "direction": "WAIT",
        "rsi": 55.8,
        "last_close": "0.56949",
        "sma20": "0.56795",
        "sma50": "0.56918",
        "sma200": "0.56972",
        "bull": 2,
        "bear": 3,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "EUR/GBP",
        "score": 22,
        "direction": "WAIT",
        "rsi": 57.2,
        "last_close": "0.86664",
        "sma20": "0.86599",
        "sma50": "0.86437",
        "sma200": "0.86523",
        "bull": 3,
        "bear": 2,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "AUD/CAD",
        "score": 21,
        "direction": "WAIT",
        "rsi": 54.4,
        "last_close": "0.99166",
        "sma20": "0.99106",
        "sma50": "0.98653",
        "sma200": "0.98714",
        "bull": 3,
        "bear": 2,
        "total_sigs": 5,
        "fundamental": {
          "signal": "SELL",
          "fund_score": -0.783,
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.783,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0
        }
      },
      {
        "label": "NZD/CHF",
        "score": 20,
        "direction": "WAIT",
        "rsi": 52.7,
        "last_close": "0.46309",
        "sma20": "0.46243",
        "sma50": "0.46306",
        "sma200": "0.46298",
        "bull": 3,
        "bear": 2,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "GBP/CAD",
        "score": 18,
        "direction": "WAIT",
        "rsi": 50.0,
        "last_close": "1.87289",
        "sma20": "1.87350",
        "sma50": "1.87273",
        "sma200": "1.85942",
        "bull": 2,
        "bear": 3,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "GBP/AUD",
        "score": 18,
        "direction": "WAIT",
        "rsi": 39.5,
        "last_close": "1.88695",
        "sma20": "1.89014",
        "sma50": "1.89813",
        "sma200": "1.88347",
        "bull": 2,
        "bear": 3,
        "total_sigs": 5,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.783,
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.0,
          "quote_score": -0.783,
          "base_count": 0,
          "quote_count": 1
        }
      },
      {
        "label": "GBP/JPY",
        "score": 16,
        "direction": "WAIT",
        "rsi": 43.9,
        "last_close": "213.465",
        "sma20": "213.776",
        "sma50": "214.418",
        "sma200": "213.903",
        "bull": 2,
        "bear": 3,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      },
      {
        "label": "EUR/AUD",
        "score": 16,
        "direction": "WAIT",
        "rsi": 43.6,
        "last_close": "1.63489",
        "sma20": "1.63746",
        "sma50": "1.64105",
        "sma200": "1.62969",
        "bull": 2,
        "bear": 3,
        "total_sigs": 5,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.783,
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.0,
          "quote_score": -0.783,
          "base_count": 0,
          "quote_count": 1
        }
      },
      {
        "label": "NZD/CAD",
        "score": 15,
        "direction": "WAIT",
        "rsi": 44.6,
        "last_close": "0.81229",
        "sma20": "0.81404",
        "sma50": "0.81344",
        "sma200": "0.81255",
        "bull": 3,
        "bear": 2,
        "total_sigs": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0
        }
      }
    ],
    "total": 26
  }
};
