// Diperbarui: 23 Aug 2026 22:01 WIB
window.FK_DATA = {
  "generated": "23 Aug 2026 22:01 WIB",
  "kalender": {
    "generated": "23 Aug 2026 22:01 WIB",
    "events": []
  },
  "sentimen": {
    "generated": "23 Aug 2026 22:01 WIB",
    "summary": {
      "total": 51,
      "bullish": 13,
      "bearish": 31,
      "netral": 7,
      "avg_score": -0.2991,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "USD",
          "sentiment": "Bearish",
          "score": -0.328,
          "count": 6
        },
        {
          "currency": "EUR",
          "sentiment": "Netral",
          "score": 0.02,
          "count": 5
        },
        {
          "currency": "AUD",
          "sentiment": "Bearish",
          "score": -0.927,
          "count": 1
        },
        {
          "currency": "CHF",
          "sentiment": "Netral",
          "score": 0.0,
          "count": 1
        }
      ]
    },
    "items": [
      {
        "source": "Investing.com Forex",
        "title": "Gulf markets rise as oil prices climb on Iran sanction fears",
        "url": "https://www.investing.com/news/stock-market-news/gulf-markets-rise-as-oil-prices-climb-on-iran-sanction-fears-93CH-4872460",
        "summary": "",
        "published": "23 Aug 2026 20:49 WIB",
        "sentiment": "Bearish",
        "score": -0.501,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Up another 12% Friday, this AI-picked energy stock is now up +90%",
        "url": "https://www.investing.com/news/stock-market-news/up-another-12-friday-this-aipicked-energy-stock-is-now-up-90-4872447",
        "summary": "",
        "published": "23 Aug 2026 20:10 WIB",
        "sentiment": "Bullish",
        "score": 0.273,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Saudi Arabia stocks higher at close of trade; Tadawul All Share up 1.13%",
        "url": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-higher-at-close-of-trade-tadawul-all-share-up-113-4872445",
        "summary": "",
        "published": "23 Aug 2026 19:45 WIB",
        "sentiment": "Bullish",
        "score": 0.296,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Robots can outrun humans, but can they plug in a cable?",
        "url": "https://www.investing.com/news/stock-market-news/robots-can-outrun-humans-but-can-they-plug-in-a-cable-4872417",
        "summary": "",
        "published": "23 Aug 2026 19:36 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Alibaba launches $10 billion Hong Kong share placement to fund AI spending",
        "url": "https://www.investing.com/news/stock-market-news/alibaba-proposes-hong-kong-share-placement-worth-10-billion-4872416",
        "summary": "",
        "published": "23 Aug 2026 18:36 WIB",
        "sentiment": "Bullish",
        "score": 0.296,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Citi expects Nvidia stock to trade higher post earnings",
        "url": "https://www.investing.com/news/stock-market-news/citi-expects-nvidia-stock-to-trade-higher-post-earnings-4872442",
        "summary": "",
        "published": "23 Aug 2026 18:17 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Eni targets commercial fusion power plant in Europe by 2040s",
        "url": "https://www.investing.com/news/stock-market-news/eni-targets-commercial-fusion-power-plant-in-europe-by-2040s-93CH-4872439",
        "summary": "",
        "published": "23 Aug 2026 18:01 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "ECB chief Lagarde ’ready to serve’ WEF, Swiss newspaper reports",
        "url": "https://www.investing.com/news/stock-market-news/ecb-chief-lagarde-ready-to-serve-wef-swiss-newspaper-reports-4872430",
        "summary": "",
        "published": "23 Aug 2026 15:42 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "5 big analyst AI moves: Apple upgraded on foldable iPhone push, new AI strategy",
        "url": "https://www.investing.com/news/stock-market-news/5-big-analyst-ai-moves-apple-upgraded-on-foldable-iphone-push-new-ai-strategy-4872396",
        "summary": "",
        "published": "23 Aug 2026 14:56 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Korean retail traders chase 40% coupons after historic stock rout - report",
        "url": "https://www.investing.com/news/stock-market-news/korean-retail-traders-chase-40-coupons-after-historic-stock-rout--report-4872421",
        "summary": "",
        "published": "23 Aug 2026 13:09 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Fed Faces High Stakes Test at Jackson Hole",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/fed-faces-high-stakes-test-at-jackson-hole-video",
        "summary": "Fed Chair Kevin Warsh heads into Jackson Hole under heightened scrutiny after the Treasury’s intervention in the bond market raised questions about the traditional boundaries between fiscal and monetary policy. Host of Bloomberg Money Tom Keene and Veda Partners Co-Founder Henrietta Treyz are on Blo",
        "published": "23 Aug 2026 21:47 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Rep. McCormick Warns Against Slowing AI Buildout",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/rep-mccormick-warns-against-slowing-ai-buildout-video",
        "summary": "Representative Rich McCormick is on Bloomberg This Weekend with David Gura and Christina Ruffini and says the US should continue expanding data centers to support its leadership in artificial intelligence, arguing they can be built responsibly while benefiting local economies. (Source: Bloomberg)",
        "published": "23 Aug 2026 21:29 WIB",
        "sentiment": "Bullish",
        "score": 0.718,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "How Water Scarcity Is Changing the Economics of the Southwest",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/the-water-crisis-reshaping-the-american-west-video",
        "summary": "The Colorado River provides water to seven states, contributing to an estimated $1.4 trillion in annual economic activity. But decades of decline, record-low snowpack and shrinking reservoirs have pushed the system toward crisis, with Lake Powell nearing levels that could threaten hydropower product",
        "published": "23 Aug 2026 21:02 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Canada Digs In as US Trade Fight Escalates",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/canada-digs-in-as-us-trade-fight-escalates-video",
        "summary": "Joining Bloomberg This Weekend, Former Canadian Finance Minister Chrystia Freeland says Canada was right to walk away from a trade deal she argues would have harmed both countries, urging Ottawa not to back down and saying past retaliation against US tariffs proved effective. Freeland warns hosts Da",
        "published": "23 Aug 2026 21:01 WIB",
        "sentiment": "Bearish",
        "score": -0.772,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Alliance Tested as Trump Pulls Out of South Korea Drill",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/alliance-tested-as-trump-pulls-out-of-south-korea-drill-video",
        "summary": "The US and South Korea sharply curtailed their annual military exercises after President Donald Trump ordered them scaled back, surprising Seoul as North Korea expands its nuclear and missile capabilities and deepens military ties with Russia. Bloomberg Economics and Senior Geoeconomics Analyst Adam",
        "published": "23 Aug 2026 20:48 WIB",
        "sentiment": "Bullish",
        "score": 0.281,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Treasury Buybacks Fail to Calm Bond Market",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/treasury-buybacks-fail-to-calm-bond-market-video",
        "summary": "The Treasury’s surprise decision to at least double buybacks of longer-dated US debt briefly pushed yields lower, but much of that move quickly reversed as investors questioned whether the intervention can overcome inflation and fiscal concerns. PIMCO Executive VP, Market Strategist and Generalist P",
        "published": "23 Aug 2026 20:26 WIB",
        "sentiment": "Bullish",
        "score": 0.052,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Iceland Faces Close Vote on EU Talks",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/iceland-faces-close-vote-on-eu-talks-video",
        "summary": "Iceland will vote August 29th on whether to resume accession talks with the European Union, with recent polling showing a narrow advantage for the “yes” side. RUV Correspondent Ingólfur Bjarni Sigfússon joins Christina Ruffini on Bloomberg This Weekend and explains that debate is being shaped by sec",
        "published": "23 Aug 2026 20:11 WIB",
        "sentiment": "Bullish",
        "score": 0.25,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Can Canada Still Trust America on Trade?",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/can-canada-still-trust-america-on-trade-video",
        "summary": "Chrystia Freeland says a tentative US-Canada trade agreement may prevent new US tariffs from taking effect, but only if Canada makes major concessions including easing retaliation, allowing US alcohol back into provincial stores and aligning with Washington on some digital issues. Existing US tariff",
        "published": "23 Aug 2026 19:03 WIB",
        "sentiment": "Bullish",
        "score": 0.526,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Saudi Oil Logistics Roiled Again by Houthis’ Red Sea Threat",
        "url": "https://www.bloomberg.com/news/articles/2026-08-23/saudis-oil-logistics-roiled-again-by-houthis-red-sea-threat",
        "summary": "Saudi Arabia is yet again being forced to overhaul how its oil gets to customers around the world, as Yemen’s Houthis make it harder for Riyadh to use a backup route that’s been vital to the global economy since the Iran war started.",
        "published": "23 Aug 2026 18:30 WIB",
        "sentiment": "Bearish",
        "score": -0.844,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Europe’s Luxury Giants Discern Green Shoots in Key China Market",
        "url": "https://www.bloomberg.com/news/articles/2026-08-23/europe-s-luxury-giants-discern-green-shoots-in-key-china-market",
        "summary": "Europe’s biggest luxury firms are turning a little more positive on the crucial Chinese market, as a fragile spending recovery takes shape in the country.",
        "published": "23 Aug 2026 14:00 WIB",
        "sentiment": "Bullish",
        "score": 0.639,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Swiss Franc Slides as Dollar Rebounds; Traders Eye FOMC Minutes - CryptoRank",
        "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOc3BleVNJTk5NRDdQU2pycFZfdERGZGhHeEJ2WGt3S0dJZkdXNTlCdzNUeXZMZ3VmUlZKeWp5Q1AxVmtDT3hMVWU2OEl4cHgtVTMyTTYycHdjVXJScldjcVdTVUZ6S2ZrS29XeHFNcFdJR2Eyal9CazVvTDJ3TDJGLUZJMzk?oc=5",
        "summary": "Swiss Franc Slides as Dollar Rebounds; Traders Eye FOMC Minutes CryptoRank",
        "published": "23 Aug 2026 00:17 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "high"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Why Doesn’t Geopolitical Risk Always Push Gold Higher? for OANDA:BTCUSD by Kelly_Carter12 - TradingView",
        "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxQbExQTFhpS1lkRi1HcVVLalY2cTZ2SmlraElNalVQSGZSbVd6bHd0d1VRR3U4bnZocEZ5QjNyQ2tHQVBrbUR2aVdpMjBBeFdJdUtUdkRpZVhIMjExdXBTSnBtS2psdGFDVW1zMmF1VENDblpWWWJGWkUwVlNOdWR1cVRvc1k5ZmlHclRDM2tETUlMY0NkeUZGZ1U1dDduYnFKSTItRkFWOA?oc=5",
        "summary": "Why Doesn’t Geopolitical Risk Always Push Gold Higher? for OANDA:BTCUSD by Kelly_Carter12 TradingView",
        "published": "22 Aug 2026 16:51 WIB",
        "sentiment": "Bearish",
        "score": -0.631,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Trump says Canada wants 'benefits' of being US state after trade talks collapse",
        "url": "https://www.bbc.co.uk/news/articles/cx272np7vgyo?at_medium=RSS&at_campaign=rss",
        "summary": "Canada's PM said he was \"reluctantly\" announcing retaliatory tariffs and accused the US of starting a trade war.",
        "published": "23 Aug 2026 12:46 WIB",
        "sentiment": "Bearish",
        "score": -0.876,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Zelensky should be asked what he knew about government corruption, sacked minister tells BBC",
        "url": "https://www.bbc.co.uk/news/articles/cwy4ypzvd7po?at_medium=RSS&at_campaign=rss",
        "summary": "Mykhailo Fedorov has also called for wartime elections to be held in Ukraine.",
        "published": "23 Aug 2026 19:56 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "DR Congo and M23 rebels agree roadmap for peace talks",
        "url": "https://www.bbc.co.uk/news/articles/cre4e1q3wewo?at_medium=RSS&at_campaign=rss",
        "summary": "Representatives met in Switzerland to work out next steps to resolve the conflict.",
        "published": "23 Aug 2026 19:52 WIB",
        "sentiment": "Bullish",
        "score": 0.591,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Dozens of co-ordinated arson attacks hit southern Thailand",
        "url": "https://www.bbc.co.uk/news/articles/c8enegx4xy3o?at_medium=RSS&at_campaign=rss",
        "summary": "No group has claimed responsibility for the attacks, which the military said \"aimed at creating unrest\".",
        "published": "23 Aug 2026 18:50 WIB",
        "sentiment": "Bearish",
        "score": -0.78,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Girl, 17, killed in Swedish sword attack, police say",
        "url": "https://www.bbc.co.uk/news/articles/c8jnjp0lwlwo?at_medium=RSS&at_campaign=rss",
        "summary": "Two boys aged 12 and 17 were also injured, while an 18-year-old suspect has been detained.",
        "published": "23 Aug 2026 08:34 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Syria says Israeli strike near Damascus violation of international law",
        "url": "https://www.bbc.co.uk/news/articles/c2dkdegr2xeo?at_medium=RSS&at_campaign=rss",
        "summary": "The latest incident comes days after reports emerged Israel had struck a military airbase close to the Turkish border.",
        "published": "23 Aug 2026 04:42 WIB",
        "sentiment": "Bearish",
        "score": -0.691,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Rescuers dig through Ukraine mall wreckage as Zelensky condemns 'despicable' Russian strike",
        "url": "https://www.bbc.co.uk/news/articles/c39egw7nmk2o?at_medium=RSS&at_campaign=rss",
        "summary": "Four people are still missing after Friday's attack which killed 16 and left 130 injured, including a number of children.",
        "published": "22 Aug 2026 20:13 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "US military newspaper editor voices censorship fears after being fired",
        "url": "https://www.bbc.co.uk/news/articles/cm2g23ng8p4o?at_medium=RSS&at_campaign=rss",
        "summary": "Erik Slavin believes he was fired for saying in an interview that \"in a hypothetical situation, censorship would be a red line\".",
        "published": "22 Aug 2026 23:57 WIB",
        "sentiment": "Bearish",
        "score": -0.875,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "Iran-linked hackers behind cyber attack that shut down power plant, reports say",
        "url": "https://www.bbc.co.uk/news/articles/ce9793g34yvo?at_medium=RSS&at_campaign=rss",
        "summary": "The government says at no point was there a risk to the UK's energy system during the attack in July.",
        "published": "23 Aug 2026 09:48 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "Les used a QR code to download a parking app - but it was a scam",
        "url": "https://www.bbc.co.uk/news/articles/cwyjqg578e1o?at_medium=RSS&at_campaign=rss",
        "summary": "Scammers set up a monthly subscription of £60 from Les Howard's account after he downloaded an app.",
        "published": "23 Aug 2026 13:23 WIB",
        "sentiment": "Bearish",
        "score": -0.803,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "How a new era of heatwaves could shake up the school calendar",
        "url": "https://www.bbc.co.uk/news/articles/cp872m0grgyo?at_medium=RSS&at_campaign=rss",
        "summary": "Teachers warn it could be increasingly difficult for classrooms to function during the hottest months.",
        "published": "23 Aug 2026 06:16 WIB",
        "sentiment": "Bearish",
        "score": -0.717,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Scammers increasingly using QR codes to steal money and data",
        "url": "https://www.bbc.co.uk/news/articles/cwyjqg578e1o?at_medium=RSS&at_campaign=rss",
        "summary": "Scammers set up a monthly subscription of £60 from Les Howard's account after he downloaded an app.",
        "published": "23 Aug 2026 13:23 WIB",
        "sentiment": "Bearish",
        "score": -0.654,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "The Suez Crisis stopped the British Empire. Will Hormuz defeat the US?",
        "url": "https://www.aljazeera.com/video/deja-vu-2/2026/8/23/the-suez-crisis-stopped-the-british-empire-will-hormuz-defeat-the-us?traffic_source=rss",
        "summary": "In the latest episode of Al Jazeera’s new podcast, Deja Vu looks at how oil, shipping and war shape the Gulf.",
        "published": "23 Aug 2026 20:37 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Heavy Israeli air strike hits warehouse in central Gaza",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/8/23/heavy-israeli-air-strike-hits-warehouse-in-central-gaza?traffic_source=rss",
        "summary": "Heavy Israeli air strike hits warehouse in central Gaza",
        "published": "23 Aug 2026 20:20 WIB",
        "sentiment": "Bearish",
        "score": -0.33,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Dozens of attacks in southern Thailand wound three people",
        "url": "https://www.aljazeera.com/news/2026/8/23/dozens-of-attacks-in-southern-thailand-wound-three-people?traffic_source=rss",
        "summary": "Many local government offices and several vehicles were damaged or destroyed in the 51 attacks late on Saturday.",
        "published": "23 Aug 2026 20:08 WIB",
        "sentiment": "Bearish",
        "score": -0.978,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "AI fraud costing victims millions of dollars",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/8/23/ai-fraud-costing-victims-millions-of-dollars?traffic_source=rss",
        "summary": "Deepfake scams are becoming harder to spot as criminals use AI to impersonate officials and public figures.",
        "published": "23 Aug 2026 20:08 WIB",
        "sentiment": "Bearish",
        "score": -0.927,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Zelenskyy says wartime elections could ‘destroy’ Ukraine",
        "url": "https://www.aljazeera.com/news/2026/8/23/zelenskyy-says-wartime-elections-could-destroy-ukraine?traffic_source=rss",
        "summary": "The embattled Ukrainian president slams Mykhailo Fedorov's idea as a 'tsunami' that would 'split' the country.",
        "published": "23 Aug 2026 19:19 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Can Iran retaliate against countries that join US ‘economic war’?",
        "url": "https://www.aljazeera.com/news/2026/8/23/can-iran-retaliate-against-countries-that-join-us-economic-war?traffic_source=rss",
        "summary": "Iran warns that countries backing US economic sanctions will be considered an enemy of Tehran.",
        "published": "23 Aug 2026 18:50 WIB",
        "sentiment": "Bearish",
        "score": -0.462,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Israel’s war on Gaza forces Palestinians to rely on ‘Stone Age’ toilets",
        "url": "https://www.aljazeera.com/features/2026/8/23/israels-war-on-gaza-forces-palestinians-to-rely-on-stone-age-toilets?traffic_source=rss",
        "summary": "The displaced in Gaza are struggling to find safe, discreet and sanitary toilets amid health crisis.",
        "published": "23 Aug 2026 18:00 WIB",
        "sentiment": "Bearish",
        "score": -0.996,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Syria’s foreign minister says door open for diplomacy with Israel",
        "url": "https://www.aljazeera.com/news/2026/8/23/syria-foreign-minister-says-door-open-for-diplomacy-with-israel?traffic_source=rss",
        "summary": "Asaad al-Shaibani urges Israel to seize 'historic opportunity' for diplomacy.",
        "published": "23 Aug 2026 17:48 WIB",
        "sentiment": "Bullish",
        "score": 0.421,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Far-right provocateur Jake Lang arrested after Minneapolis riot",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/8/23/far-right-provocateur-jake-lang-arrested-after-minneapolis-riot?traffic_source=rss",
        "summary": "Far-right influencer Jake Lang was arrested after clashes erupted at his rally outside Minneapolis City Hall.",
        "published": "23 Aug 2026 17:41 WIB",
        "sentiment": "Bearish",
        "score": -0.789,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "I’m turning 70. Here’s how I’m making this decade the richest of my retirement.",
        "url": "https://www.marketwatch.com/story/im-turning-70-heres-how-im-making-this-decade-the-richest-of-my-retirement-ae351f90?mod=mw_rss_topstories",
        "summary": "Tweaking my finances, work and life as I go from the “go-go” years to the “slow-go” years.",
        "published": "23 Aug 2026 19:00 WIB",
        "sentiment": "Bullish",
        "score": 0.447,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Canada announces retaliatory tariffs on U.S. goods after trade talks break down",
        "url": "https://www.marketwatch.com/story/canada-announces-retaliatory-tariffs-on-u-s-goods-after-trade-talks-break-down-45081c2f?mod=mw_rss_topstories",
        "summary": "Canadian Prime Minister Mark Carney on Saturday announced his country would impose “dollar-for-dollar” tariffs on U.S. goods — a retaliatory measure after trade talks between the two nations broke down.",
        "published": "23 Aug 2026 03:31 WIB",
        "sentiment": "Bearish",
        "score": -0.612,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "CNBC Forex",
        "title": "Warren Buffett Watch: It's Buffett, not Abel, who appears to be calling the shots on stocks",
        "url": "https://www.cnbc.com/2026/08/22/warren-buffett-not-greg-abel-appears-to-still-be-calling-the-shots-on-stocks.html",
        "summary": "New Berkshire Hathaway CEO Greg Abel appears to be letting Warren Buffett and portfolio manager Ted Weschler make all the decisions on the company's equities.",
        "published": "22 Aug 2026 19:06 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "As U.S.-Canada trade talks collapse, Carney says retaliatory tariffs will start Sept. 8",
        "url": "https://www.cnbc.com/2026/08/22/us-canada-trade-talks-collapse-ushering-in-wave-of-new-tariffs.html",
        "summary": "New 50% Trump administration tariffs on some Canadian exports went into place after the U.S. and Canada failed to reach a deal on Friday.",
        "published": "23 Aug 2026 13:39 WIB",
        "sentiment": "Bearish",
        "score": -0.671,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "CNBC World",
        "title": "Small UK power generator shut down after cyberattack linked to Iran: Telegraph",
        "url": "https://www.cnbc.com/2026/08/23/small-uk-power-plant-shut-down-after-iran-linked-cyberattack-report.html",
        "summary": "The U.K. government says the incident did not pose a risk to the country's energy system, adding that it briefed CEOs of companies in the sector with advice.",
        "published": "23 Aug 2026 19:46 WIB",
        "sentiment": "Bullish",
        "score": 0.283,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Ahead of tough new U.S. sanctions, Iran criticizes 'extraterritorial sovereignty'",
        "url": "https://www.cnbc.com/2026/08/22/iran-criticizes-us-sanctions-extraterritorial-sovereignty.html",
        "summary": "U.S. Treasury Secretary Scott Bessent told CNBC on Thursday that the proposed economic measures will likely negate the need for major U.S. military operations.",
        "published": "22 Aug 2026 17:34 WIB",
        "sentiment": "Bearish",
        "score": -0.353,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Paramount, California AG office reportedly plan to meet Monday to discuss settling WBD lawsuit",
        "url": "https://www.cnbc.com/2026/08/22/paramount-california-ag-said-to-plan-meeting-on-settling-wbd-suit-.html",
        "summary": "Paramount and the California A.G. office are set to meet Monday to discuss a settlement of the antitrust lawsuit over Paramount's Warner Bros. Discovery deal.",
        "published": "23 Aug 2026 03:34 WIB",
        "sentiment": "Bearish",
        "score": -0.421,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Nvidia customers reportedly warned about AI-related price hikes",
        "url": "https://www.cnbc.com/2026/08/22/nvidia-customers-reportedly-warned-about-ai-related-price-hikes-.html",
        "summary": "The chipmaker has told some of its largest customers that the prices of servers containing its AI chips could move more than 15% higher, Bloomberg News reported.",
        "published": "23 Aug 2026 03:26 WIB",
        "sentiment": "Bearish",
        "score": -0.353,
        "emoji": "🔴",
        "impact": "high"
      }
    ]
  },
  "geopolitik": {
    "generated": "23 Aug 2026 22:01 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.398,
        "count": 20
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.491,
        "count": 18
      },
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.351,
        "count": 18
      },
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.299,
        "count": 11
      },
      {
        "pair": "AUD/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.481,
        "count": 5
      },
      {
        "pair": "USD/CNY",
        "direction": "Tekanan Turun ▼",
        "score": -0.481,
        "count": 5
      },
      {
        "pair": "USD/RUB",
        "direction": "Tekanan Turun ▼",
        "score": -0.439,
        "count": 3
      },
      {
        "pair": "GBP/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.08,
        "count": 2
      }
    ],
    "items": [
      {
        "source": "Investing.com Forex",
        "title": "Gulf markets rise as oil prices climb on Iran sanction fears",
        "url": "https://www.investing.com/news/stock-market-news/gulf-markets-rise-as-oil-prices-climb-on-iran-sanction-fears-93CH-4872460",
        "summary": "",
        "published": "23 Aug 2026 20:49 WIB",
        "sentiment": "Bearish",
        "score": -0.501,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Korean retail traders chase 40% coupons after historic stock rout - report",
        "url": "https://www.investing.com/news/stock-market-news/korean-retail-traders-chase-40-coupons-after-historic-stock-rout--report-4872421",
        "summary": "",
        "published": "23 Aug 2026 13:09 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Fed Faces High Stakes Test at Jackson Hole",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/fed-faces-high-stakes-test-at-jackson-hole-video",
        "summary": "Fed Chair Kevin Warsh heads into Jackson Hole under heightened scrutiny after the Treasury’s intervention in the bond market raised questions about the traditional boundaries between fiscal and monetary policy. Host of Bloomberg Money Tom Keene and Veda Partners Co-Founder Henrietta Treyz are on Blo",
        "published": "23 Aug 2026 21:47 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Rep. McCormick Warns Against Slowing AI Buildout",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/rep-mccormick-warns-against-slowing-ai-buildout-video",
        "summary": "Representative Rich McCormick is on Bloomberg This Weekend with David Gura and Christina Ruffini and says the US should continue expanding data centers to support its leadership in artificial intelligence, arguing they can be built responsibly while benefiting local economies. (Source: Bloomberg)",
        "published": "23 Aug 2026 21:29 WIB",
        "sentiment": "Bullish",
        "score": 0.718,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "How Water Scarcity Is Changing the Economics of the Southwest",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/the-water-crisis-reshaping-the-american-west-video",
        "summary": "The Colorado River provides water to seven states, contributing to an estimated $1.4 trillion in annual economic activity. But decades of decline, record-low snowpack and shrinking reservoirs have pushed the system toward crisis, with Lake Powell nearing levels that could threaten hydropower product",
        "published": "23 Aug 2026 21:02 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Canada Digs In as US Trade Fight Escalates",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/canada-digs-in-as-us-trade-fight-escalates-video",
        "summary": "Joining Bloomberg This Weekend, Former Canadian Finance Minister Chrystia Freeland says Canada was right to walk away from a trade deal she argues would have harmed both countries, urging Ottawa not to back down and saying past retaliation against US tariffs proved effective. Freeland warns hosts Da",
        "published": "23 Aug 2026 21:01 WIB",
        "sentiment": "Bearish",
        "score": -0.772,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Alliance Tested as Trump Pulls Out of South Korea Drill",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/alliance-tested-as-trump-pulls-out-of-south-korea-drill-video",
        "summary": "The US and South Korea sharply curtailed their annual military exercises after President Donald Trump ordered them scaled back, surprising Seoul as North Korea expands its nuclear and missile capabilities and deepens military ties with Russia. Bloomberg Economics and Senior Geoeconomics Analyst Adam",
        "published": "23 Aug 2026 20:48 WIB",
        "sentiment": "Bullish",
        "score": 0.281,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Can Canada Still Trust America on Trade?",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/can-canada-still-trust-america-on-trade-video",
        "summary": "Chrystia Freeland says a tentative US-Canada trade agreement may prevent new US tariffs from taking effect, but only if Canada makes major concessions including easing retaliation, allowing US alcohol back into provincial stores and aligning with Washington on some digital issues. Existing US tariff",
        "published": "23 Aug 2026 19:03 WIB",
        "sentiment": "Bullish",
        "score": 0.526,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Saudi Oil Logistics Roiled Again by Houthis’ Red Sea Threat",
        "url": "https://www.bloomberg.com/news/articles/2026-08-23/saudis-oil-logistics-roiled-again-by-houthis-red-sea-threat",
        "summary": "Saudi Arabia is yet again being forced to overhaul how its oil gets to customers around the world, as Yemen’s Houthis make it harder for Riyadh to use a backup route that’s been vital to the global economy since the Iran war started.",
        "published": "23 Aug 2026 18:30 WIB",
        "sentiment": "Bearish",
        "score": -0.844,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Why Doesn’t Geopolitical Risk Always Push Gold Higher? for OANDA:BTCUSD by Kelly_Carter12 - TradingView",
        "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxQbExQTFhpS1lkRi1HcVVLalY2cTZ2SmlraElNalVQSGZSbVd6bHd0d1VRR3U4bnZocEZ5QjNyQ2tHQVBrbUR2aVdpMjBBeFdJdUtUdkRpZVhIMjExdXBTSnBtS2psdGFDVW1zMmF1VENDblpWWWJGWkUwVlNOdWR1cVRvc1k5ZmlHclRDM2tETUlMY0NkeUZGZ1U1dDduYnFKSTItRkFWOA?oc=5",
        "summary": "Why Doesn’t Geopolitical Risk Always Push Gold Higher? for OANDA:BTCUSD by Kelly_Carter12 TradingView",
        "published": "22 Aug 2026 16:51 WIB",
        "sentiment": "Bearish",
        "score": -0.631,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Trump says Canada wants 'benefits' of being US state after trade talks collapse",
        "url": "https://www.bbc.co.uk/news/articles/cx272np7vgyo?at_medium=RSS&at_campaign=rss",
        "summary": "Canada's PM said he was \"reluctantly\" announcing retaliatory tariffs and accused the US of starting a trade war.",
        "published": "23 Aug 2026 12:46 WIB",
        "sentiment": "Bearish",
        "score": -0.876,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Zelensky should be asked what he knew about government corruption, sacked minister tells BBC",
        "url": "https://www.bbc.co.uk/news/articles/cwy4ypzvd7po?at_medium=RSS&at_campaign=rss",
        "summary": "Mykhailo Fedorov has also called for wartime elections to be held in Ukraine.",
        "published": "23 Aug 2026 19:56 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "DR Congo and M23 rebels agree roadmap for peace talks",
        "url": "https://www.bbc.co.uk/news/articles/cre4e1q3wewo?at_medium=RSS&at_campaign=rss",
        "summary": "Representatives met in Switzerland to work out next steps to resolve the conflict.",
        "published": "23 Aug 2026 19:52 WIB",
        "sentiment": "Bullish",
        "score": 0.591,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Dozens of co-ordinated arson attacks hit southern Thailand",
        "url": "https://www.bbc.co.uk/news/articles/c8enegx4xy3o?at_medium=RSS&at_campaign=rss",
        "summary": "No group has claimed responsibility for the attacks, which the military said \"aimed at creating unrest\".",
        "published": "23 Aug 2026 18:50 WIB",
        "sentiment": "Bearish",
        "score": -0.78,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Girl, 17, killed in Swedish sword attack, police say",
        "url": "https://www.bbc.co.uk/news/articles/c8jnjp0lwlwo?at_medium=RSS&at_campaign=rss",
        "summary": "Two boys aged 12 and 17 were also injured, while an 18-year-old suspect has been detained.",
        "published": "23 Aug 2026 08:34 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Syria says Israeli strike near Damascus violation of international law",
        "url": "https://www.bbc.co.uk/news/articles/c2dkdegr2xeo?at_medium=RSS&at_campaign=rss",
        "summary": "The latest incident comes days after reports emerged Israel had struck a military airbase close to the Turkish border.",
        "published": "23 Aug 2026 04:42 WIB",
        "sentiment": "Bearish",
        "score": -0.691,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Rescuers dig through Ukraine mall wreckage as Zelensky condemns 'despicable' Russian strike",
        "url": "https://www.bbc.co.uk/news/articles/c39egw7nmk2o?at_medium=RSS&at_campaign=rss",
        "summary": "Four people are still missing after Friday's attack which killed 16 and left 130 injured, including a number of children.",
        "published": "22 Aug 2026 20:13 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "US military newspaper editor voices censorship fears after being fired",
        "url": "https://www.bbc.co.uk/news/articles/cm2g23ng8p4o?at_medium=RSS&at_campaign=rss",
        "summary": "Erik Slavin believes he was fired for saying in an interview that \"in a hypothetical situation, censorship would be a red line\".",
        "published": "22 Aug 2026 23:57 WIB",
        "sentiment": "Bearish",
        "score": -0.875,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "Iran-linked hackers behind cyber attack that shut down power plant, reports say",
        "url": "https://www.bbc.co.uk/news/articles/ce9793g34yvo?at_medium=RSS&at_campaign=rss",
        "summary": "The government says at no point was there a risk to the UK's energy system during the attack in July.",
        "published": "23 Aug 2026 09:48 WIB",
        "sentiment": "Bearish",
        "score": -0.973,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "Les used a QR code to download a parking app - but it was a scam",
        "url": "https://www.bbc.co.uk/news/articles/cwyjqg578e1o?at_medium=RSS&at_campaign=rss",
        "summary": "Scammers set up a monthly subscription of £60 from Les Howard's account after he downloaded an app.",
        "published": "23 Aug 2026 13:23 WIB",
        "sentiment": "Bearish",
        "score": -0.803,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "How a new era of heatwaves could shake up the school calendar",
        "url": "https://www.bbc.co.uk/news/articles/cp872m0grgyo?at_medium=RSS&at_campaign=rss",
        "summary": "Teachers warn it could be increasingly difficult for classrooms to function during the hottest months.",
        "published": "23 Aug 2026 06:16 WIB",
        "sentiment": "Bearish",
        "score": -0.717,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Scammers increasingly using QR codes to steal money and data",
        "url": "https://www.bbc.co.uk/news/articles/cwyjqg578e1o?at_medium=RSS&at_campaign=rss",
        "summary": "Scammers set up a monthly subscription of £60 from Les Howard's account after he downloaded an app.",
        "published": "23 Aug 2026 13:23 WIB",
        "sentiment": "Bearish",
        "score": -0.654,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "The Suez Crisis stopped the British Empire. Will Hormuz defeat the US?",
        "url": "https://www.aljazeera.com/video/deja-vu-2/2026/8/23/the-suez-crisis-stopped-the-british-empire-will-hormuz-defeat-the-us?traffic_source=rss",
        "summary": "In the latest episode of Al Jazeera’s new podcast, Deja Vu looks at how oil, shipping and war shape the Gulf.",
        "published": "23 Aug 2026 20:37 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Heavy Israeli air strike hits warehouse in central Gaza",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/8/23/heavy-israeli-air-strike-hits-warehouse-in-central-gaza?traffic_source=rss",
        "summary": "Heavy Israeli air strike hits warehouse in central Gaza",
        "published": "23 Aug 2026 20:20 WIB",
        "sentiment": "Bearish",
        "score": -0.33,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Dozens of attacks in southern Thailand wound three people",
        "url": "https://www.aljazeera.com/news/2026/8/23/dozens-of-attacks-in-southern-thailand-wound-three-people?traffic_source=rss",
        "summary": "Many local government offices and several vehicles were damaged or destroyed in the 51 attacks late on Saturday.",
        "published": "23 Aug 2026 20:08 WIB",
        "sentiment": "Bearish",
        "score": -0.978,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Zelenskyy says wartime elections could ‘destroy’ Ukraine",
        "url": "https://www.aljazeera.com/news/2026/8/23/zelenskyy-says-wartime-elections-could-destroy-ukraine?traffic_source=rss",
        "summary": "The embattled Ukrainian president slams Mykhailo Fedorov's idea as a 'tsunami' that would 'split' the country.",
        "published": "23 Aug 2026 19:19 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Can Iran retaliate against countries that join US ‘economic war’?",
        "url": "https://www.aljazeera.com/news/2026/8/23/can-iran-retaliate-against-countries-that-join-us-economic-war?traffic_source=rss",
        "summary": "Iran warns that countries backing US economic sanctions will be considered an enemy of Tehran.",
        "published": "23 Aug 2026 18:50 WIB",
        "sentiment": "Bearish",
        "score": -0.462,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Israel’s war on Gaza forces Palestinians to rely on ‘Stone Age’ toilets",
        "url": "https://www.aljazeera.com/features/2026/8/23/israels-war-on-gaza-forces-palestinians-to-rely-on-stone-age-toilets?traffic_source=rss",
        "summary": "The displaced in Gaza are struggling to find safe, discreet and sanitary toilets amid health crisis.",
        "published": "23 Aug 2026 18:00 WIB",
        "sentiment": "Bearish",
        "score": -0.996,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Syria’s foreign minister says door open for diplomacy with Israel",
        "url": "https://www.aljazeera.com/news/2026/8/23/syria-foreign-minister-says-door-open-for-diplomacy-with-israel?traffic_source=rss",
        "summary": "Asaad al-Shaibani urges Israel to seize 'historic opportunity' for diplomacy.",
        "published": "23 Aug 2026 17:48 WIB",
        "sentiment": "Bullish",
        "score": 0.421,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "MarketWatch",
        "title": "Canada announces retaliatory tariffs on U.S. goods after trade talks break down",
        "url": "https://www.marketwatch.com/story/canada-announces-retaliatory-tariffs-on-u-s-goods-after-trade-talks-break-down-45081c2f?mod=mw_rss_topstories",
        "summary": "Canadian Prime Minister Mark Carney on Saturday announced his country would impose “dollar-for-dollar” tariffs on U.S. goods — a retaliatory measure after trade talks between the two nations broke down.",
        "published": "23 Aug 2026 03:31 WIB",
        "sentiment": "Bearish",
        "score": -0.612,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "CNBC Forex",
        "title": "Warren Buffett Watch: It's Buffett, not Abel, who appears to be calling the shots on stocks",
        "url": "https://www.cnbc.com/2026/08/22/warren-buffett-not-greg-abel-appears-to-still-be-calling-the-shots-on-stocks.html",
        "summary": "New Berkshire Hathaway CEO Greg Abel appears to be letting Warren Buffett and portfolio manager Ted Weschler make all the decisions on the company's equities.",
        "published": "22 Aug 2026 19:06 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "As U.S.-Canada trade talks collapse, Carney says retaliatory tariffs will start Sept. 8",
        "url": "https://www.cnbc.com/2026/08/22/us-canada-trade-talks-collapse-ushering-in-wave-of-new-tariffs.html",
        "summary": "New 50% Trump administration tariffs on some Canadian exports went into place after the U.S. and Canada failed to reach a deal on Friday.",
        "published": "23 Aug 2026 13:39 WIB",
        "sentiment": "Bearish",
        "score": -0.671,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "CNBC World",
        "title": "Small UK power generator shut down after cyberattack linked to Iran: Telegraph",
        "url": "https://www.cnbc.com/2026/08/23/small-uk-power-plant-shut-down-after-iran-linked-cyberattack-report.html",
        "summary": "The U.K. government says the incident did not pose a risk to the country's energy system, adding that it briefed CEOs of companies in the sector with advice.",
        "published": "23 Aug 2026 19:46 WIB",
        "sentiment": "Bullish",
        "score": 0.283,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Ahead of tough new U.S. sanctions, Iran criticizes 'extraterritorial sovereignty'",
        "url": "https://www.cnbc.com/2026/08/22/iran-criticizes-us-sanctions-extraterritorial-sovereignty.html",
        "summary": "U.S. Treasury Secretary Scott Bessent told CNBC on Thursday that the proposed economic measures will likely negate the need for major U.S. military operations.",
        "published": "22 Aug 2026 17:34 WIB",
        "sentiment": "Bearish",
        "score": -0.353,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Paramount, California AG office reportedly plan to meet Monday to discuss settling WBD lawsuit",
        "url": "https://www.cnbc.com/2026/08/22/paramount-california-ag-said-to-plan-meeting-on-settling-wbd-suit-.html",
        "summary": "Paramount and the California A.G. office are set to meet Monday to discuss a settlement of the antitrust lawsuit over Paramount's Warner Bros. Discovery deal.",
        "published": "23 Aug 2026 03:34 WIB",
        "sentiment": "Bearish",
        "score": -0.421,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Nvidia customers reportedly warned about AI-related price hikes",
        "url": "https://www.cnbc.com/2026/08/22/nvidia-customers-reportedly-warned-about-ai-related-price-hikes-.html",
        "summary": "The chipmaker has told some of its largest customers that the prices of servers containing its AI chips could move more than 15% higher, Bloomberg News reported.",
        "published": "23 Aug 2026 03:26 WIB",
        "sentiment": "Bearish",
        "score": -0.353,
        "emoji": "🔴",
        "impact": "high"
      }
    ]
  },
  "fj_live": {
    "generated": "23 Aug 2026 22:01 WIB",
    "summary": {
      "total": 22,
      "bullish": 5,
      "bearish": 6,
      "netral": 11,
      "avg_score": -0.045,
      "overall": "Netral"
    },
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Fed Faces High Stakes Test at Jackson Hole",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/fed-faces-high-stakes-test-at-jackson-hole-video",
        "summary": "Fed Chair Kevin Warsh heads into Jackson Hole under heightened scrutiny after the Treasury’s intervention in the bond market raised questions about the traditional boundaries between fiscal and monetary policy. Host of Bloomberg Money Tom Keene and Veda Partners Co-Founder Henrietta Treyz are on Blo",
        "published": "23 Aug 2026 21:47 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Canada Digs In as US Trade Fight Escalates",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/canada-digs-in-as-us-trade-fight-escalates-video",
        "summary": "Joining Bloomberg This Weekend, Former Canadian Finance Minister Chrystia Freeland says Canada was right to walk away from a trade deal she argues would have harmed both countries, urging Ottawa not to back down and saying past retaliation against US tariffs proved effective. Freeland warns hosts Da",
        "published": "23 Aug 2026 21:01 WIB",
        "sentiment": "Bearish",
        "score": -0.772,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Gulf markets rise as oil prices climb on Iran sanction fears",
        "url": "https://www.investing.com/news/stock-market-news/gulf-markets-rise-as-oil-prices-climb-on-iran-sanction-fears-93CH-4872460",
        "summary": "",
        "published": "23 Aug 2026 20:49 WIB",
        "sentiment": "Bearish",
        "score": -0.501,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Treasury Buybacks Fail to Calm Bond Market",
        "url": "https://www.bloomberg.com/news/videos/2026-08-23/treasury-buybacks-fail-to-calm-bond-market-video",
        "summary": "The Treasury’s surprise decision to at least double buybacks of longer-dated US debt briefly pushed yields lower, but much of that move quickly reversed as investors questioned whether the intervention can overcome inflation and fiscal concerns. PIMCO Executive VP, Market Strategist and Generalist P",
        "published": "23 Aug 2026 20:26 WIB",
        "sentiment": "Bullish",
        "score": 0.052,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "ECB chief Lagarde ’ready to serve’ WEF, Swiss newspaper reports",
        "url": "https://www.investing.com/news/stock-market-news/ecb-chief-lagarde-ready-to-serve-wef-swiss-newspaper-reports-4872430",
        "summary": "",
        "published": "23 Aug 2026 15:42 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Trump says Canada wants 'benefits' of being US state after trade talks collapse",
        "url": "https://www.bbc.co.uk/news/articles/cx272np7vgyo?at_medium=RSS&at_campaign=rss",
        "summary": "Canada's PM said he was \"reluctantly\" announcing retaliatory tariffs and accused the US of starting a trade war.",
        "published": "23 Aug 2026 12:46 WIB",
        "sentiment": "Bearish",
        "score": -0.876,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Canada announces retaliatory tariffs on U.S. goods after trade talks break down",
        "url": "https://www.marketwatch.com/story/canada-announces-retaliatory-tariffs-on-u-s-goods-after-trade-talks-break-down-45081c2f?mod=mw_rss_topstories",
        "summary": "Canadian Prime Minister Mark Carney on Saturday announced his country would impose “dollar-for-dollar” tariffs on U.S. goods — a retaliatory measure after trade talks between the two nations broke down.",
        "published": "23 Aug 2026 03:31 WIB",
        "sentiment": "Bearish",
        "score": -0.612,
        "emoji": "🔴",
        "impact": "medium"
      },
      {
        "source": "FinancialJuice",
        "title": "Carney outlined next steps to protect Canadian interests: dollar-for-dollar counter-tariffs to begin the Tuesday after Labour Day - statement",
        "url": "https://www.financialjuice.com/News/9732442/Carney-outlined-next-steps-to-protect-Canadian-interests-dollar-for-dollar-counter-tariffs-to-begin-the-Tuesday-after-Labour-Day---statement.aspx?xy=rss",
        "summary": "",
        "published": "23 Aug 2026 02:31 WIB",
        "sentiment": "Bullish",
        "score": 0.557,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Google News Geopolitik",
        "title": "Swiss Franc Slides as Dollar Rebounds; Traders Eye FOMC Minutes - CryptoRank",
        "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOc3BleVNJTk5NRDdQU2pycFZfdERGZGhHeEJ2WGt3S0dJZkdXNTlCdzNUeXZMZ3VmUlZKeWp5Q1AxVmtDT3hMVWU2OEl4cHgtVTMyTTYycHdjVXJScldjcVdTVUZ6S2ZrS29XeHFNcFdJR2Eyal9CazVvTDJ3TDJGLUZJMzk?oc=5",
        "summary": "Swiss Franc Slides as Dollar Rebounds; Traders Eye FOMC Minutes CryptoRank",
        "published": "23 Aug 2026 00:17 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "high"
      },
      {
        "source": "FinancialJuice",
        "title": "Canada's PM Carney: Canada will offer tariff safeguards where relevant for certain industries",
        "url": "https://www.financialjuice.com/News/9732396/Canadas-PM-Carney-Canada-will-offer-tariff-safeguards-where-relevant-for-certain-industries.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 22:36 WIB",
        "sentiment": "Bullish",
        "score": 0.542,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "FinancialJuice",
        "title": "Canada's PM Carney: to unveil details of new tariff measures in coming days",
        "url": "https://www.financialjuice.com/News/9732391/Canadas-PM-Carney-to-unveil-details-of-new-tariff-measures-in-coming-days.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 22:18 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "CNBC World",
        "title": "Ahead of tough new U.S. sanctions, Iran criticizes 'extraterritorial sovereignty'",
        "url": "https://www.cnbc.com/2026/08/22/iran-criticizes-us-sanctions-extraterritorial-sovereignty.html",
        "summary": "U.S. Treasury Secretary Scott Bessent told CNBC on Thursday that the proposed economic measures will likely negate the need for major U.S. military operations.",
        "published": "22 Aug 2026 17:34 WIB",
        "sentiment": "Bearish",
        "score": -0.353,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "FinancialJuice",
        "title": "Senior Trump administration official: Canada sought slightly more Section 232 tariff relief than U.S. was prepared to grant",
        "url": "https://www.financialjuice.com/News/9732200/Senior-Trump-administration-official-Canada-sought-slightly-more-Section-232-tariff-relief-than-US-was-prepared-to-grant.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 10:47 WIB",
        "sentiment": "Bullish",
        "score": 0.758,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "FinancialJuice",
        "title": "Carney: as U.S. imposes 50% tariffs, Canada will match tariffs dollar for dollar to protect workers and businesses",
        "url": "https://www.financialjuice.com/News/9732188/Carney-as-US-imposes-50-tariffs-Canada-will-match-tariffs-dollar-for-dollar-to-protect-workers-and-businesses.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 10:44 WIB",
        "sentiment": "Bullish",
        "score": 0.296,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "FinancialJuice",
        "title": "CAD CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731774/CAD-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:43 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "NZD CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731773/NZD-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:43 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "CHF CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731772/CHF-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:43 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "GBP CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731771/GBP-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:42 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "JPY CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731770/JPY-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:42 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "AUD CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731769/AUD-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:41 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "EUR CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731768/EUR-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:41 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "FinancialJuice",
        "title": "USD CFTC Positions Week August 18th - FJElite",
        "url": "https://www.financialjuice.com/News/9731767/USD-CFTC-Positions-Week-August-18th---FJElite.aspx?xy=rss",
        "summary": "",
        "published": "22 Aug 2026 02:40 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      }
    ]
  },
  "rekomendasi": {
    "generated": "23 Aug 2026 22:01 WIB",
    "pairs": [
      {
        "label": "EUR/JPY",
        "score": 47,
        "direction": "SELL",
        "rsi": 48.5,
        "last_close": "185.594",
        "smma7": "185.657",
        "ema9": "185.651",
        "atr14": "0.137",
        "bars_since_cross": 1,
        "cross_label": "1 candle lalu",
        "freshness_score": 45,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CAD",
        "score": 40,
        "direction": "BUY",
        "rsi": 47.8,
        "last_close": "1.37630",
        "smma7": "1.37612",
        "ema9": "1.37615",
        "atr14": "0.00140",
        "bars_since_cross": 2,
        "cross_label": "2 candle lalu",
        "freshness_score": 40,
        "separation_score": 0,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.25,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.25,
          "quote_score": 0.0,
          "base_count": 6,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CAD",
        "score": 36,
        "direction": "BUY",
        "rsi": 49.8,
        "last_close": "1.87772",
        "smma7": "1.87761",
        "ema9": "1.87767",
        "atr14": "0.00160",
        "bars_since_cross": 3,
        "cross_label": "3 candle lalu",
        "freshness_score": 35,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/USD",
        "score": 33,
        "direction": "BUY",
        "rsi": 53.5,
        "last_close": "1.36480",
        "smma7": "1.36463",
        "ema9": "1.36467",
        "atr14": "0.00118",
        "bars_since_cross": 4,
        "cross_label": "4 candle lalu",
        "freshness_score": 30,
        "separation_score": 1,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.25,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.0,
          "quote_score": -0.25,
          "base_count": 0,
          "quote_count": 6,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/JPY",
        "score": 30,
        "direction": "BUY",
        "rsi": 52.8,
        "last_close": "216.787",
        "smma7": "216.829",
        "ema9": "216.855",
        "atr14": "0.186",
        "bars_since_cross": 5,
        "cross_label": "5 candle lalu",
        "freshness_score": 25,
        "separation_score": 4,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/AUD",
        "score": 30,
        "direction": "SELL",
        "rsi": 22.0,
        "last_close": "1.62799",
        "smma7": "1.63000",
        "ema9": "1.62896",
        "atr14": "0.00166",
        "bars_since_cross": 20,
        "cross_label": "20 candle lalu",
        "freshness_score": 0,
        "separation_score": 16,
        "rsi_score": 14,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 1,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/USD",
        "score": 25,
        "direction": "SELL",
        "rsi": 42.9,
        "last_close": "1.16781",
        "smma7": "1.16859",
        "ema9": "1.16839",
        "atr14": "0.00082",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 6,
        "rsi_score": 4,
        "fundamental": {
          "signal": "BUY",
          "fund_score": 0.27,
          "confidence": "Kuat",
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.02,
          "quote_score": -0.25,
          "base_count": 5,
          "quote_count": 6,
          "base_insufficient": false,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/JPY",
        "score": 24,
        "direction": "BUY",
        "rsi": 69.2,
        "last_close": "113.964",
        "smma7": "113.885",
        "ema9": "113.951",
        "atr14": "0.117",
        "bars_since_cross": 42,
        "cross_label": "42 candle lalu",
        "freshness_score": 0,
        "separation_score": 14,
        "rsi_score": 10,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/AUD",
        "score": 23,
        "direction": "SELL",
        "rsi": 28.4,
        "last_close": "1.90215",
        "smma7": "1.90370",
        "ema9": "1.90279",
        "atr14": "0.00193",
        "bars_since_cross": 19,
        "cross_label": "19 candle lalu",
        "freshness_score": 0,
        "separation_score": 12,
        "rsi_score": 11,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CHF",
        "score": 22,
        "direction": "BUY",
        "rsi": 55.3,
        "last_close": "0.80084",
        "smma7": "0.80047",
        "ema9": "0.80064",
        "atr14": "0.00109",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.25,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.25,
          "quote_score": 0.0,
          "base_count": 6,
          "quote_count": 1,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/USD",
        "score": 21,
        "direction": "BUY",
        "rsi": 66.8,
        "last_close": "0.71746",
        "smma7": "0.71696",
        "ema9": "0.71731",
        "atr14": "0.00066",
        "bars_since_cross": 21,
        "cross_label": "21 candle lalu",
        "freshness_score": 0,
        "separation_score": 13,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.25,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.0,
          "quote_score": -0.25,
          "base_count": 1,
          "quote_count": 6,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/JPY",
        "score": 19,
        "direction": "BUY",
        "rsi": 53.6,
        "last_close": "158.940",
        "smma7": "158.907",
        "ema9": "158.922",
        "atr14": "0.159",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 2,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.25,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bearish",
          "quote_sentiment": "Netral",
          "base_score": -0.25,
          "quote_score": 0.0,
          "base_count": 6,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/GBP",
        "score": 19,
        "direction": "SELL",
        "rsi": 44.5,
        "last_close": "0.85608",
        "smma7": "0.85620",
        "ema9": "0.85606",
        "atr14": "0.00053",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 6,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CHF",
        "score": 15,
        "direction": "BUY",
        "rsi": 65.0,
        "last_close": "0.47876",
        "smma7": "0.47852",
        "ema9": "0.47873",
        "atr14": "0.00077",
        "bars_since_cross": 32,
        "cross_label": "32 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 8,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/JPY",
        "score": 12,
        "direction": "BUY",
        "rsi": 59.8,
        "last_close": "94.985",
        "smma7": "94.988",
        "ema9": "95.014",
        "atr14": "0.093",
        "bars_since_cross": 57,
        "cross_label": "57 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CAD",
        "score": 12,
        "direction": "BUY",
        "rsi": 62.9,
        "last_close": "0.82293",
        "smma7": "0.82262",
        "ema9": "0.82285",
        "atr14": "0.00092",
        "bars_since_cross": 21,
        "cross_label": "21 candle lalu",
        "freshness_score": 0,
        "separation_score": 6,
        "rsi_score": 6,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/NZD",
        "score": 12,
        "direction": "SELL",
        "rsi": 39.2,
        "last_close": "1.95423",
        "smma7": "1.95420",
        "ema9": "1.95372",
        "atr14": "0.00179",
        "bars_since_cross": 24,
        "cross_label": "24 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/CAD",
        "score": 12,
        "direction": "BUY",
        "rsi": 60.9,
        "last_close": "0.98626",
        "smma7": "0.98616",
        "ema9": "0.98663",
        "atr14": "0.00167",
        "bars_since_cross": 20,
        "cross_label": "20 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CAD",
        "score": 8,
        "direction": "SELL",
        "rsi": 42.6,
        "last_close": "1.60724",
        "smma7": "1.60770",
        "ema9": "1.60750",
        "atr14": "0.00136",
        "bars_since_cross": 37,
        "cross_label": "37 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/NZD",
        "score": 8,
        "direction": "BUY",
        "rsi": 55.5,
        "last_close": "1.19883",
        "smma7": "1.19859",
        "ema9": "1.19881",
        "atr14": "0.00120",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/USD",
        "score": 7,
        "direction": "BUY",
        "rsi": 55.1,
        "last_close": "0.59773",
        "smma7": "0.59795",
        "ema9": "0.59805",
        "atr14": "0.00063",
        "bars_since_cross": 23,
        "cross_label": "23 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.25,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bearish",
          "base_score": 0.0,
          "quote_score": -0.25,
          "base_count": 0,
          "quote_count": 6,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CHF",
        "score": 7,
        "direction": "BUY",
        "rsi": 55.3,
        "last_close": "1.09231",
        "smma7": "1.09220",
        "ema9": "1.09241",
        "atr14": "0.00127",
        "bars_since_cross": 31,
        "cross_label": "31 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CHF/JPY",
        "score": 6,
        "direction": "SELL",
        "rsi": 44.5,
        "last_close": "198.378",
        "smma7": "198.468",
        "ema9": "198.446",
        "atr14": "0.183",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/JPY",
        "score": 2,
        "direction": "BUY",
        "rsi": 51.3,
        "last_close": "115.414",
        "smma7": "115.460",
        "ema9": "115.466",
        "atr14": "0.120",
        "bars_since_cross": 44,
        "cross_label": "44 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CHF",
        "score": 1,
        "direction": "BUY",
        "rsi": 50.7,
        "last_close": "0.93506",
        "smma7": "0.93522",
        "ema9": "0.93526",
        "atr14": "0.00103",
        "bars_since_cross": 29,
        "cross_label": "29 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.02,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.02,
          "quote_score": 0.0,
          "base_count": 5,
          "quote_count": 1,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/CHF",
        "score": 1,
        "direction": "BUY",
        "rsi": 49.1,
        "last_close": "0.58116",
        "smma7": "0.58156",
        "ema9": "0.58163",
        "atr14": "0.00125",
        "bars_since_cross": 32,
        "cross_label": "32 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      }
    ],
    "total": 26
  }
};
