// Diperbarui: 26 Jul 2026 22:01 WIB
window.FK_DATA = {
  "generated": "26 Jul 2026 22:01 WIB",
  "kalender": {
    "generated": "26 Jul 2026 22:01 WIB",
    "events": [
      {
        "date": "2026-07-26",
        "day": "Minggu",
        "time_wib": "05:50",
        "currency": "JPY",
        "impact": "low",
        "event": "SPPI y/y",
        "actual": "",
        "forecast": "3.4%",
        "previous": "3.3%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "14:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German ifo Business Climate",
        "actual": "",
        "forecast": "86.1",
        "previous": "85.6"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "M3 Money Supply y/y",
        "actual": "",
        "forecast": "3.2%",
        "previous": "3.2%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Private Loans y/y",
        "actual": "",
        "forecast": "3.1%",
        "previous": "3.1%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "ECOFIN Meetings",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "16:00",
        "currency": "GBP",
        "impact": "low",
        "event": "CBI Realized Sales",
        "actual": "",
        "forecast": "-45",
        "previous": "-54"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "18:30",
        "currency": "USD",
        "impact": "low",
        "event": "Core Durable Goods Orders m/m",
        "actual": "",
        "forecast": "0.9%",
        "previous": "1.4%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Durable Goods Orders m/m",
        "actual": "",
        "forecast": "1.6%",
        "previous": "-4.5%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "05:01",
        "currency": "GBP",
        "impact": "low",
        "event": "BRC Shop Price Index y/y",
        "actual": "",
        "forecast": "1.2%",
        "previous": "1.2%"
      },
      {
        "date": "2026-07-27",
        "day": "Senin",
        "time_wib": "09:05",
        "currency": "AUD",
        "impact": "high",
        "event": "RBA Gov Bullock Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "11:00",
        "currency": "JPY",
        "impact": "low",
        "event": "BOJ Core CPI y/y",
        "actual": "",
        "forecast": "1.4%",
        "previous": "1.4%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "13:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Spanish Unemployment Rate",
        "actual": "",
        "forecast": "10.7%",
        "previous": "10.8%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German Buba Monthly Report",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "18:15",
        "currency": "USD",
        "impact": "low",
        "event": "ADP Weekly Employment Change",
        "actual": "",
        "forecast": "",
        "previous": "16.5K"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "18:30",
        "currency": "USD",
        "impact": "low",
        "event": "Goods Trade Balance",
        "actual": "",
        "forecast": "-98.0B",
        "previous": "-105.8B"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Prelim Wholesale Inventories m/m",
        "actual": "",
        "forecast": "0.2%",
        "previous": "0.1%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "19:00",
        "currency": "USD",
        "impact": "low",
        "event": "HPI m/m",
        "actual": "",
        "forecast": "0.2%",
        "previous": "-0.1%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "S&P/CS Composite-20 HPI y/y",
        "actual": "",
        "forecast": "0.8%",
        "previous": "1.1%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "20:00",
        "currency": "USD",
        "impact": "medium",
        "event": "CB Consumer Confidence",
        "actual": "",
        "forecast": "92.1",
        "previous": "91.2"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Richmond Manufacturing Index",
        "actual": "",
        "forecast": "",
        "previous": "4"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "02:30",
        "currency": "USD",
        "impact": "low",
        "event": "API Weekly Statistical Bulletin",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "07:30",
        "currency": "AUD",
        "impact": "high",
        "event": "CPI m/m",
        "actual": "",
        "forecast": "0.2%",
        "previous": "-0.7%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "08:30",
        "currency": "AUD",
        "impact": "high",
        "event": "CPI y/y",
        "actual": "",
        "forecast": "4.0%",
        "previous": "4.0%"
      },
      {
        "date": "2026-07-28",
        "day": "Selasa",
        "time_wib": "08:30",
        "currency": "AUD",
        "impact": "high",
        "event": "Trimmed Mean CPI m/m",
        "actual": "",
        "forecast": "0.4%",
        "previous": "0.4%"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "12:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German Import Prices m/m",
        "actual": "",
        "forecast": "-0.8%",
        "previous": "0.7%"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "14:00",
        "currency": "CHF",
        "impact": "low",
        "event": "UBS Economic Expectations",
        "actual": "",
        "forecast": "",
        "previous": "-25.0"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "14:30",
        "currency": "GBP",
        "impact": "low",
        "event": "M4 Money Supply m/m",
        "actual": "",
        "forecast": "0.2%",
        "previous": "0.1%"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Mortgage Approvals",
        "actual": "",
        "forecast": "56K",
        "previous": "56K"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Net Lending to Individuals m/m",
        "actual": "",
        "forecast": "5.5B",
        "previous": "4.6B"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "German 10-y Bond Auction",
        "actual": "",
        "forecast": "",
        "previous": "3.09|1.0"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "20:30",
        "currency": "USD",
        "impact": "low",
        "event": "Crude Oil Inventories",
        "actual": "",
        "forecast": "",
        "previous": "2.0M"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "23:30",
        "currency": "CAD",
        "impact": "low",
        "event": "BOC Summary of Deliberations",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "00:00",
        "currency": "USD",
        "impact": "high",
        "event": "Federal Funds Rate",
        "actual": "",
        "forecast": "3.75%",
        "previous": "3.75%"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "high",
        "event": "FOMC Statement",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "00:30",
        "currency": "USD",
        "impact": "high",
        "event": "FOMC Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "04:40",
        "currency": "AUD",
        "impact": "low",
        "event": "RBA Assist Gov Hunter Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "07:00",
        "currency": "NZD",
        "impact": "low",
        "event": "ANZ Business Confidence",
        "actual": "",
        "forecast": "",
        "previous": "36.6"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "07:30",
        "currency": "AUD",
        "impact": "low",
        "event": "Building Approvals m/m",
        "actual": "",
        "forecast": "-0.5%",
        "previous": "-1.1%"
      },
      {
        "date": "2026-07-29",
        "day": "Rabu",
        "time_wib": "08:30",
        "currency": "AUD",
        "impact": "low",
        "event": "Import Prices q/q",
        "actual": "",
        "forecast": "0.0%",
        "previous": "0.1%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "11:00",
        "currency": "JPY",
        "impact": "low",
        "event": "Consumer Confidence",
        "actual": "",
        "forecast": "34.2",
        "previous": "33.8"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "11:30",
        "currency": "EUR",
        "impact": "low",
        "event": "French Consumer Spending m/m",
        "actual": "",
        "forecast": "-0.1%",
        "previous": "0.5%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "French Flash GDP q/q",
        "actual": "",
        "forecast": "0.2%",
        "previous": "-0.1%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "medium",
        "event": "German Prelim CPI m/m",
        "actual": "",
        "forecast": "0.7%",
        "previous": "-0.3%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "12:45",
        "currency": "EUR",
        "impact": "low",
        "event": "French Prelim Private Payrolls q/q",
        "actual": "",
        "forecast": "-0.1%",
        "previous": "-0.1%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "CHF",
        "impact": "low",
        "event": "KOF Economic Barometer",
        "actual": "",
        "forecast": "100.7",
        "previous": "101.2"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Spanish Flash CPI y/y",
        "actual": "",
        "forecast": "3.1%",
        "previous": "3.2%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Spanish Flash GDP q/q",
        "actual": "",
        "forecast": "0.6%",
        "previous": "0.6%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "14:00",
        "currency": "EUR",
        "impact": "medium",
        "event": "German Prelim GDP q/q",
        "actual": "",
        "forecast": "0.1%",
        "previous": "0.3%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Italian Prelim GDP q/q",
        "actual": "",
        "forecast": "0.1%",
        "previous": "0.3%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Italian Monthly Unemployment Rate",
        "actual": "",
        "forecast": "5.1%",
        "previous": "5.0%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Prelim Flash GDP q/q",
        "actual": "",
        "forecast": "0.2%",
        "previous": "-0.2%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Unemployment Rate",
        "actual": "",
        "forecast": "6.2%",
        "previous": "6.2%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Italian 10-y Bond Auction",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "17:00",
        "currency": "GBP",
        "impact": "high",
        "event": "BOE Monetary Policy Report",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "high",
        "event": "Monetary Policy Summary",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "high",
        "event": "MPC Official Bank Rate Votes",
        "actual": "",
        "forecast": "2-0-7",
        "previous": "2-0-7"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "13:00",
        "currency": "GBP",
        "impact": "high",
        "event": "Official Bank Rate",
        "actual": "",
        "forecast": "3.75%",
        "previous": "3.75%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "18:30",
        "currency": "USD",
        "impact": "high",
        "event": "Advance GDP q/q",
        "actual": "",
        "forecast": "2.3%",
        "previous": "2.1%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "high",
        "event": "Core PCE Price Index m/m",
        "actual": "",
        "forecast": "0.1%",
        "previous": "0.3%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Advance GDP Price Index q/q",
        "actual": "",
        "forecast": "3.7%",
        "previous": "3.6%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Unemployment Claims",
        "actual": "",
        "forecast": "206K",
        "previous": "187K"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Personal Income m/m",
        "actual": "",
        "forecast": "0.3%",
        "previous": "0.7%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "low",
        "event": "Personal Spending m/m",
        "actual": "",
        "forecast": "0.4%",
        "previous": "0.7%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "20:30",
        "currency": "USD",
        "impact": "low",
        "event": "Natural Gas Storage",
        "actual": "",
        "forecast": "",
        "previous": "32B"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "05:30",
        "currency": "JPY",
        "impact": "medium",
        "event": "Tokyo Core CPI y/y",
        "actual": "",
        "forecast": "1.8%",
        "previous": "1.6%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Unemployment Rate",
        "actual": "",
        "forecast": "2.5%",
        "previous": "2.5%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "05:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Prelim Industrial Production m/m",
        "actual": "",
        "forecast": "0.7%",
        "previous": "0.1%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "low",
        "event": "Retail Sales y/y",
        "actual": "",
        "forecast": "2.8%",
        "previous": "5.0%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:30",
        "currency": "AUD",
        "impact": "low",
        "event": "PPI q/q",
        "actual": "",
        "forecast": "0.3%",
        "previous": "0.4%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "08:30",
        "currency": "AUD",
        "impact": "low",
        "event": "Private Sector Credit m/m",
        "actual": "",
        "forecast": "0.6%",
        "previous": "0.7%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Manufacturing PMI",
        "actual": "",
        "forecast": "49.9",
        "previous": "50.3"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "09:00",
        "currency": "CNY",
        "impact": "low",
        "event": "Non-Manufacturing PMI",
        "actual": "",
        "forecast": "50.0",
        "previous": "50.2"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "high",
        "event": "BOJ Policy Rate",
        "actual": "",
        "forecast": "<1.00%",
        "previous": "<1.00%"
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "high",
        "event": "Monetary Policy Statement",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-30",
        "day": "Kamis",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "high",
        "event": "BOJ Outlook Report",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "11:00",
        "currency": "JPY",
        "impact": "low",
        "event": "Housing Starts y/y",
        "actual": "",
        "forecast": "13.2%",
        "previous": "33.9%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "07:50",
        "currency": "JPY",
        "impact": "high",
        "event": "BOJ Press Conference",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "12:00",
        "currency": "GBP",
        "impact": "low",
        "event": "Nationwide HPI m/m",
        "actual": "",
        "forecast": "",
        "previous": "0.0%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "12:30",
        "currency": "CHF",
        "impact": "low",
        "event": "Retail Sales y/y",
        "actual": "",
        "forecast": "3.2%",
        "previous": "3.5%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "12:45",
        "currency": "EUR",
        "impact": "low",
        "event": "French Prelim CPI m/m",
        "actual": "",
        "forecast": "0.3%",
        "previous": "-0.3%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "13:55",
        "currency": "EUR",
        "impact": "low",
        "event": "German Unemployment Change",
        "actual": "",
        "forecast": "5K",
        "previous": "-1K"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "medium",
        "event": "Core CPI Flash Estimate y/y",
        "actual": "",
        "forecast": "2.4%",
        "previous": "2.4%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "medium",
        "event": "CPI Flash Estimate y/y",
        "actual": "",
        "forecast": "2.9%",
        "previous": "2.8%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "15:00",
        "currency": "EUR",
        "impact": "low",
        "event": "Italian Prelim CPI m/m",
        "actual": "",
        "forecast": "0.1%",
        "previous": "0.0%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "17:15",
        "currency": "GBP",
        "impact": "low",
        "event": "MPC Member Pill Speaks",
        "actual": "",
        "forecast": "",
        "previous": ""
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "18:30",
        "currency": "CAD",
        "impact": "high",
        "event": "GDP m/m",
        "actual": "",
        "forecast": "0.2%",
        "previous": "0.5%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Employment Cost Index q/q",
        "actual": "",
        "forecast": "0.8%",
        "previous": "0.9%"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "19:45",
        "currency": "USD",
        "impact": "low",
        "event": "Chicago PMI",
        "actual": "",
        "forecast": "57.5",
        "previous": "56.7"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "20:00",
        "currency": "USD",
        "impact": "medium",
        "event": "Revised UoM Consumer Sentiment",
        "actual": "",
        "forecast": "54.2",
        "previous": "54.4"
      },
      {
        "date": "2026-07-31",
        "day": "Jumat",
        "time_wib": "19:30",
        "currency": "USD",
        "impact": "medium",
        "event": "Revised UoM Inflation Expectations",
        "actual": "",
        "forecast": "",
        "previous": "4.2%"
      }
    ]
  },
  "sentimen": {
    "generated": "26 Jul 2026 22:01 WIB",
    "summary": {
      "total": 36,
      "bullish": 12,
      "bearish": 19,
      "netral": 5,
      "avg_score": -0.0812,
      "overall": "Bearish",
      "currency_impact": [
        {
          "currency": "USD",
          "sentiment": "Bullish",
          "score": 0.542,
          "count": 3
        },
        {
          "currency": "EUR",
          "sentiment": "Bearish",
          "score": -0.516,
          "count": 1
        },
        {
          "currency": "JPY",
          "sentiment": "Bullish",
          "score": 0.815,
          "count": 1
        }
      ]
    },
    "items": [
      {
        "source": "ForexLive",
        "title": "Apa itu tradeCompass di investLive.com: Penjelasan metodologi perdagangan dan bagaimana pedagang dapat memanfaatkannya",
        "url": "https://investinglive.com/education/what-is-tradecompass-at-investinglive-com-trading-methodolgy-explained-and-how-traders-can-utilize-it/",
        "summary": "tradeCompass methodology explained: How traders can use the investingLive market map Successful trading does not require predicting every market movement. It requires a clear plan for what to do if buyers take control, what to do if sellers take control, and how to manage the trade after entry. That",
        "published": "26 Jul 2026 21:23 WIB",
        "sentiment": "Bullish",
        "score": 0.813,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Shein mengajukan IPO di Hong Kong karena perubahan tarif membebani pertumbuhan dan keuntungan",
        "url": "https://www.investing.com/news/stock-market-news/shein-files-for-hong-kong-ipo-after-profit-drops-despite-revenue-growth-4812897",
        "summary": "",
        "published": "26 Jul 2026 21:50 WIB",
        "sentiment": "Bullish",
        "score": 0.75,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "Investing.com Forex",
        "title": "Shein mengalami kerugian kuartalan menjelang IPO Hong Kong",
        "url": "https://www.investing.com/news/stock-market-news/shein-reveals-key-financials-ahead-of-hong-kong-ipo-4812893",
        "summary": "",
        "published": "26 Jul 2026 21:36 WIB",
        "sentiment": "Bearish",
        "score": -0.398,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Mengapa ahli strategi ini mengatakan erosi institusional AS terlalu dibesar-besarkan?",
        "url": "https://www.investing.com/news/stock-market-news/why-this-strategist-says-us-institutional-erosion-is-overstated-4812863",
        "summary": "",
        "published": "26 Jul 2026 20:08 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Saham Arab Saudi melemah pada penutupan perdagangan; Tadawul Seluruh Saham turun 0,34%",
        "url": "https://www.investing.com/news/stock-market-news/saudi-arabia-stocks-lower-at-close-of-trade-tadawul-all-share-down-034-4812860",
        "summary": "",
        "published": "26 Jul 2026 19:45 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Perusahaan yang melakukan pembelian kembali secara agresif telah tertinggal dari S&P 500 di era AI",
        "url": "https://www.investing.com/news/stock-market-news/companies-with-aggressive-buybacks-have-lagged-the-sp-500-in-the-ai-era-4812859",
        "summary": "",
        "published": "26 Jul 2026 19:43 WIB",
        "sentiment": "Bearish",
        "score": -0.421,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "CEO UniCredit mengatakan kesepakatan dengan Commerzbank mungkin terjadi saat pembicaraan dilanjutkan",
        "url": "https://www.investing.com/news/stock-market-news/unicredit-ceo-says-deal-with-commerzbank-likely-as-talks-resume-93CH-4812853",
        "summary": "",
        "published": "26 Jul 2026 17:54 WIB",
        "sentiment": "Bullish",
        "score": 0.08,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "5 pergerakan AI analis besar: Beberapa pilihan teratas disebutkan dalam pendapatan Q2",
        "url": "https://www.investing.com/news/stock-market-news/5-big-analyst-ai-moves-several-top-picks-named-into-q2-earnings-4812810",
        "summary": "",
        "published": "26 Jul 2026 16:00 WIB",
        "sentiment": "Bullish",
        "score": 0.202,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Afrika menghadapi pukulan ekonomi senilai $10-$20 miliar akibat El Niño ‘super’, kepala iklim AfDB memperingatkan",
        "url": "https://www.investing.com/news/stock-market-news/africa-facing-1020-billion-economic-hit-from-super-el-nino-afdb-climate-chief-warns-4812843",
        "summary": "",
        "published": "26 Jul 2026 15:36 WIB",
        "sentiment": "Bearish",
        "score": -0.183,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Forex",
        "title": "Bias carry musim panas: Mitos atau kenyataan?",
        "url": "https://www.investing.com/news/stock-market-news/summer-carry-bias-a-myth-or-reality-4812840",
        "summary": "",
        "published": "26 Jul 2026 14:26 WIB",
        "sentiment": "Bearish",
        "score": -0.103,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Investing.com Forex",
        "title": "Premi saham SK Hynix di AS kembali memunculkan peringatan gelembung AI",
        "url": "https://www.investing.com/news/stock-market-news/sk-hynixs-us-share-premium-flashes-another-ai-bubble-warning-4812835",
        "summary": "",
        "published": "26 Jul 2026 12:03 WIB",
        "sentiment": "Bearish",
        "score": -0.132,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Investing.com Economy",
        "title": "Gelombang tarif Trump ini kemungkinan akan terus berlanjut; lebih banyak lagi yang akan datang",
        "url": "https://www.investing.com/news/economic-indicators/this-wave-of-trump-tariffs-is-likely-here-to-stay-more-are-coming-4812764",
        "summary": "",
        "published": "25 Jul 2026 17:12 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Pendapatan Perusahaan Teknologi Besar Menghantam Pasar Karena Pemberontakan Terhadap Pengeluaran AI",
        "url": "https://www.bloomberg.com/news/articles/2026-07-26/big-tech-earnings-slam-into-a-market-in-revolt-over-ai-spending",
        "summary": "For years, US technology giants had a tacit agreement with investors: The companies could spend lavishly on artificial intelligence, and the stock market would reward them long as their revenues were rising. That deal is suddenly breaking down.",
        "published": "26 Jul 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.893,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Perdana Menteri Australia Albanese Akan Menekan Trump tentang Tarif Baru",
        "url": "https://www.bloomberg.com/news/articles/2026-07-26/australian-prime-minister-albanese-to-press-trump-on-new-tariffs",
        "summary": "Australian Prime Minister Anthony Albanese said he will appeal directly to President Donald Trump over new tariffs announced by Washington, describing the levies as unjustified.",
        "published": "26 Jul 2026 07:34 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "Google News Forex",
        "title": "Perkiraan USD/JPY: Melimpahnya Data PDB Jepang Mungkin Membuat Yen Dalam Posisi Kuat Besok - Exchange Rates Org UK",
        "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQUWpEZDV0TnA3Q0ZMbjZ3Q2xka0FMVlJ5eUpKbVIzSnRfVmJuQ1pIamhtcVRNbDJsemZ1NHAwbjJ3dW1iZ3p1RTMtSHF2QVRtWHZFMk1ucXMyTmtvbjNXdi12NEE0QXFKbUp2STNXdU1OLU5JelRvS09rUlczaWhmUlN5VDhYQ2Fkc2JZeDB0T2tBVVRXeDZ0bmZDVGNYUTBMVWlyYmZvSkp1TnFKVzRF?oc=5",
        "summary": "USD/JPY Forecast: Glut Of Japanese GDP Data May Leave Yen In Strong Position Tomorrow Exchange Rates Org UK",
        "published": "25 Jul 2026 14:48 WIB",
        "sentiment": "Bullish",
        "score": 0.815,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "BBC World",
        "title": "Apa yang kita ketahui sejauh ini tentang serangan serudukan Berlin Pride",
        "url": "https://www.bbc.co.uk/news/articles/cevmdxz4872o?at_medium=RSS&at_campaign=rss",
        "summary": "A police manhunt is under way after a suspect rammed a car into a crowd at a Pride event in the German capital on Saturday night.",
        "published": "26 Jul 2026 20:40 WIB",
        "sentiment": "Bearish",
        "score": -0.208,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Pemukim Israel membakar masjid, mobil, dan lahan pertanian di Tepi Barat, kata warga Palestina",
        "url": "https://www.bbc.co.uk/news/articles/cjrv77gl4deo?at_medium=RSS&at_campaign=rss",
        "summary": "The latest attacks come two days after a clash between settlers and Palestinians near the village of Tell, which left four Palestinians and two Israelis dead.",
        "published": "26 Jul 2026 17:26 WIB",
        "sentiment": "Bearish",
        "score": -0.943,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Houthi yang didukung Iran mengklaim serangan rudal ke Arab Saudi",
        "url": "https://www.bbc.co.uk/news/articles/cj9d27v70j1o?at_medium=RSS&at_campaign=rss",
        "summary": "US military says it disabled a tanker that was attempting to evade the American blockade on Iranian ports.",
        "published": "25 Jul 2026 13:34 WIB",
        "sentiment": "Bearish",
        "score": -0.637,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Business",
        "title": "'Taktik supermarket' baru Primark untuk merayu pelanggan dalam perang harga online",
        "url": "https://www.bbc.co.uk/news/articles/c4g3x4j8pgro?at_medium=RSS&at_campaign=rss",
        "summary": "Competition from ultra-cheap Chinese retailers and the cost of living crisis could be putting some people off shopping at the store, analysts say.",
        "published": "26 Jul 2026 07:17 WIB",
        "sentiment": "Bearish",
        "score": -0.87,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Business",
        "title": "Tembakan peringatan atau aksi publisitas - seberapa khawatirkah kita terhadap peretasan OpenAI?",
        "url": "https://www.bbc.co.uk/news/articles/cd9w22n9e4go?at_medium=RSS&at_campaign=rss",
        "summary": "Hugging Face said the hack was done at superhuman speed by an AI with little or no human guidance.",
        "published": "25 Jul 2026 17:14 WIB",
        "sentiment": "Bearish",
        "score": -0.486,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "BBC Top Stories",
        "title": "Andy Burnham mengesampingkan pemilihan awal dalam wawancara eksklusif BBC",
        "url": "https://www.bbc.co.uk/news/videos/c935kzyq6r4o?at_medium=RSS&at_campaign=rss",
        "summary": "The new prime minister told Laura Kuenssberg that people \"voted for a manifesto\" that he would honour, when pressed on whether there will be an early general election.",
        "published": "26 Jul 2026 12:00 WIB",
        "sentiment": "Bullish",
        "score": 0.637,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC Top Stories",
        "title": "Saya pikir pengeboman Lockerbie adalah kasus tertutup sampai saya mulai mengajukan pertanyaan",
        "url": "https://www.bbc.co.uk/news/articles/c2dkx01n0y1o?at_medium=RSS&at_campaign=rss",
        "summary": "Almost four decades on I delved into this complex case with fresh eyes - who really was behind the bombing?",
        "published": "26 Jul 2026 15:48 WIB",
        "sentiment": "Bullish",
        "score": 0.318,
        "emoji": "🟢",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Pizza, pasta, kentang, protein - bagaimana anak-anak Italia menjadi kelebihan berat badan",
        "url": "https://www.bbc.co.uk/news/articles/c33y3151vydo?at_medium=RSS&at_campaign=rss",
        "summary": "The Mediterranean diet was a blueprint for healthy living, yet Italian children are among the most overweight in Europe according to WHO.",
        "published": "26 Jul 2026 06:30 WIB",
        "sentiment": "Bearish",
        "score": -0.516,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Bagaimana saudara perempuan rapper Aitch menginspirasinya untuk mendaki salah satu puncak terberat di dunia",
        "url": "https://www.bbc.co.uk/news/articles/cx2dgl98lxko?at_medium=RSS&at_campaign=rss",
        "summary": "The rapper has been taking on challenges to raise awareness and money for the Down's Syndrome Association.",
        "published": "26 Jul 2026 14:40 WIB",
        "sentiment": "Bullish",
        "score": 0.414,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Faye dari Senegal meluncurkan partai baru, meresmikan perpisahannya dengan Sonko",
        "url": "https://www.aljazeera.com/news/2026/7/26/senegals-faye-launches-a-new-party-formalising-his-split-with-sonko?traffic_source=rss",
        "summary": "Months of tensions between president and ex-ally culminate in split that will reshape Senegal's political landscape.",
        "published": "26 Jul 2026 21:22 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Israel dan paradoks biaya perang Iran",
        "url": "https://www.aljazeera.com/opinions/2026/7/26/israel-and-the-cost-paradox-of-the-iran-war?traffic_source=rss",
        "summary": "Israel instigated the war on Iran and yet it has borne few of its costs.",
        "published": "26 Jul 2026 21:04 WIB",
        "sentiment": "Bearish",
        "score": -0.928,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Presiden Ahmed al-Sharaa: Suriah mencari kesepakatan keamanan dengan Israel",
        "url": "https://www.aljazeera.com/news/2026/7/26/president-ahmed-al-sharaa-syria-seeking-security-deal-with-israel?traffic_source=rss",
        "summary": "Syrian President al-Sharaa tells Al Jazeera Damascus seeks a security deal with Israel, and warns of chaos in Lebanon.",
        "published": "26 Jul 2026 19:34 WIB",
        "sentiment": "Bearish",
        "score": -0.077,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Tentara Iran mengeluarkan peringatan menjelang kunjungan Netanyahu ke AS",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/7/26/irans-army-issues-warning-ahead-of-netanyahus-us-visit?traffic_source=rss",
        "summary": "Iran says it has stopped retaliatory operations in the Gulf, but warns the war could expand if US strikes continue.",
        "published": "26 Jul 2026 18:56 WIB",
        "sentiment": "Bearish",
        "score": -0.935,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "‘Tidak ada pertanggungjawaban atas kejahatan perang pemukim terhadap warga Palestina’",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/7/26/no-accountability-for-settler-war-crimes-against?traffic_source=rss",
        "summary": "‘No accountability for settler war crimes against Palestinians’",
        "published": "26 Jul 2026 18:31 WIB",
        "sentiment": "Bearish",
        "score": -0.832,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Malaysia akan menjadi tuan rumah balapan F1 Grand Prix Bahrain yang dijadwalkan ulang pada bulan Oktober",
        "url": "https://www.aljazeera.com/sports/2026/7/26/malaysia-to-host-rescheduled-bahrain-grand-prix-f1-race-in-october?traffic_source=rss",
        "summary": "The race in Bahrain was rescheduled in April amid the US-Israel war on Iran and will now be held in Malaysia.",
        "published": "26 Jul 2026 18:28 WIB",
        "sentiment": "Bearish",
        "score": -0.306,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Ada 'ancaman rangkap tiga' teknis pada saham, namun ada juga tempat yang bisa disembunyikan oleh investor",
        "url": "https://www.marketwatch.com/story/theres-a-technical-triple-threat-for-stocks-but-also-places-investors-can-hide-59108c6b?mod=mw_rss_topstories",
        "summary": "Treasury yields and oil prices surged, and the dollar confirmed the breakout toward a longer-term uptrend, to push the S&P 500 below key chart support.",
        "published": "26 Jul 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.572,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Pasar Treasury mengirimkan peringatan yang jelas kepada Ketua Fed Kevin Warsh tentang suku bunga",
        "url": "https://www.marketwatch.com/story/the-treasury-market-is-sending-fed-chair-kevin-warsh-a-clear-warning-about-rates-d0026da9?mod=mw_rss_topstories",
        "summary": "Rising Treasury yields show how “enormously worried” the market is about inflation — and whether the Fed will back up its tough talk with action",
        "published": "26 Jul 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.238,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC Forex",
        "title": "Buffett menyukai pajak properti, namun seperti semua miliarder lainnya, dia tidak akan membayarnya",
        "url": "https://www.cnbc.com/2026/07/25/buffett-favors-an-estate-tax-but-like-virtually-all-billionaires-he-wont-be-paying-it.html",
        "summary": "Warren Buffett believes he and other very wealthy Americans are under-taxed but by giving his fortune to charity, he won't be paying billions in potential levies to the government.",
        "published": "25 Jul 2026 19:28 WIB",
        "sentiment": "Bullish",
        "score": 0.855,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Ukraina menyerang kapal Iran di Laut Kaspia, Teheran menuduh Kyiv melakukan 'tindakan bermusuhan dan kriminal'",
        "url": "https://www.cnbc.com/2026/07/26/ukraine-strikes-iranian-vessels-tehran-accuses-kyiv-of-hostile-act.html",
        "summary": "The latest attacks by Ukraine, combined with Saudi military strikes on Iran-backed Houthi targets in Yemen, represent a widening of the Middle East conflict.",
        "published": "26 Jul 2026 21:50 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Harga kakao melemah. Lalu mengapa coklat masih begitu mahal?",
        "url": "https://www.cnbc.com/2026/07/26/cocoa-prices-chocolate-lindt-barry-callebaut-nestle.html",
        "summary": "Chocolate firms look to win shoppers back with premium products and social media trends after poor weather conditions, tariffs, and the Iran war hit sales.",
        "published": "26 Jul 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.456,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Trump menggugat beberapa jam setelah tarif baru diberlakukan, karena para ahli mengatakan tarif tersebut mungkin tidak akan bertahan lama",
        "url": "https://www.cnbc.com/2026/07/24/trump-tariffs-lawsuit-301-ieepa.html",
        "summary": "President Donald Trump has renewed a flurry of tariffs, including slapping 25% duties on Brazilian imports and vowing 50% tariffs on goods from Canada.",
        "published": "25 Jul 2026 21:23 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "high"
      }
    ]
  },
  "geopolitik": {
    "generated": "26 Jul 2026 22:01 WIB",
    "risk_level": "TINGGI",
    "risk_color": "#ef4444",
    "risk_emoji": "🔴",
    "pairs_affected": [
      {
        "pair": "USD/JPY",
        "direction": "Tekanan Turun ▼",
        "score": -0.188,
        "count": 14
      },
      {
        "pair": "XAU/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.167,
        "count": 13
      },
      {
        "pair": "USD/CHF",
        "direction": "Tekanan Turun ▼",
        "score": -0.129,
        "count": 12
      },
      {
        "pair": "EUR/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.164,
        "count": 5
      },
      {
        "pair": "AUD/USD",
        "direction": "Tekanan Turun ▼",
        "score": -0.152,
        "count": 3
      },
      {
        "pair": "USD/CNY",
        "direction": "Tekanan Turun ▼",
        "score": -0.152,
        "count": 3
      },
      {
        "pair": "GBP/USD",
        "direction": "Tekanan Naik ▲",
        "score": 0.637,
        "count": 1
      },
      {
        "pair": "CAD/JPY",
        "direction": "Tekanan Naik ▲",
        "score": 0.572,
        "count": 1
      }
    ],
    "items": [
      {
        "source": "Bloomberg Markets",
        "title": "Pendapatan Perusahaan Teknologi Besar Menghantam Pasar Karena Pemberontakan Terhadap Pengeluaran AI",
        "url": "https://www.bloomberg.com/news/articles/2026-07-26/big-tech-earnings-slam-into-a-market-in-revolt-over-ai-spending",
        "summary": "For years, US technology giants had a tacit agreement with investors: The companies could spend lavishly on artificial intelligence, and the stock market would reward them long as their revenues were rising. That deal is suddenly breaking down.",
        "published": "26 Jul 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.893,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Bloomberg Markets",
        "title": "Perdana Menteri Australia Albanese Akan Menekan Trump tentang Tarif Baru",
        "url": "https://www.bloomberg.com/news/articles/2026-07-26/australian-prime-minister-albanese-to-press-trump-on-new-tariffs",
        "summary": "Australian Prime Minister Anthony Albanese said he will appeal directly to President Donald Trump over new tariffs announced by Washington, describing the levies as unjustified.",
        "published": "26 Jul 2026 07:34 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "medium"
      },
      {
        "source": "BBC World",
        "title": "Pemukim Israel membakar masjid, mobil, dan lahan pertanian di Tepi Barat, kata warga Palestina",
        "url": "https://www.bbc.co.uk/news/articles/cjrv77gl4deo?at_medium=RSS&at_campaign=rss",
        "summary": "The latest attacks come two days after a clash between settlers and Palestinians near the village of Tell, which left four Palestinians and two Israelis dead.",
        "published": "26 Jul 2026 17:26 WIB",
        "sentiment": "Bearish",
        "score": -0.943,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC World",
        "title": "Houthi yang didukung Iran mengklaim serangan rudal ke Arab Saudi",
        "url": "https://www.bbc.co.uk/news/articles/cj9d27v70j1o?at_medium=RSS&at_campaign=rss",
        "summary": "US military says it disabled a tanker that was attempting to evade the American blockade on Iranian ports.",
        "published": "25 Jul 2026 13:34 WIB",
        "sentiment": "Bearish",
        "score": -0.637,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "BBC Top Stories",
        "title": "Andy Burnham mengesampingkan pemilihan awal dalam wawancara eksklusif BBC",
        "url": "https://www.bbc.co.uk/news/videos/c935kzyq6r4o?at_medium=RSS&at_campaign=rss",
        "summary": "The new prime minister told Laura Kuenssberg that people \"voted for a manifesto\" that he would honour, when pressed on whether there will be an early general election.",
        "published": "26 Jul 2026 12:00 WIB",
        "sentiment": "Bullish",
        "score": 0.637,
        "emoji": "🟢",
        "impact": "medium"
      },
      {
        "source": "BBC Top Stories",
        "title": "Bagaimana saudara perempuan rapper Aitch menginspirasinya untuk mendaki salah satu puncak terberat di dunia",
        "url": "https://www.bbc.co.uk/news/articles/cx2dgl98lxko?at_medium=RSS&at_campaign=rss",
        "summary": "The rapper has been taking on challenges to raise awareness and money for the Down's Syndrome Association.",
        "published": "26 Jul 2026 14:40 WIB",
        "sentiment": "Bullish",
        "score": 0.414,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Faye dari Senegal meluncurkan partai baru, meresmikan perpisahannya dengan Sonko",
        "url": "https://www.aljazeera.com/news/2026/7/26/senegals-faye-launches-a-new-party-formalising-his-split-with-sonko?traffic_source=rss",
        "summary": "Months of tensions between president and ex-ally culminate in split that will reshape Senegal's political landscape.",
        "published": "26 Jul 2026 21:22 WIB",
        "sentiment": "Bearish",
        "score": -0.08,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "Al Jazeera",
        "title": "Israel dan paradoks biaya perang Iran",
        "url": "https://www.aljazeera.com/opinions/2026/7/26/israel-and-the-cost-paradox-of-the-iran-war?traffic_source=rss",
        "summary": "Israel instigated the war on Iran and yet it has borne few of its costs.",
        "published": "26 Jul 2026 21:04 WIB",
        "sentiment": "Bearish",
        "score": -0.928,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Presiden Ahmed al-Sharaa: Suriah mencari kesepakatan keamanan dengan Israel",
        "url": "https://www.aljazeera.com/news/2026/7/26/president-ahmed-al-sharaa-syria-seeking-security-deal-with-israel?traffic_source=rss",
        "summary": "Syrian President al-Sharaa tells Al Jazeera Damascus seeks a security deal with Israel, and warns of chaos in Lebanon.",
        "published": "26 Jul 2026 19:34 WIB",
        "sentiment": "Bearish",
        "score": -0.077,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Tentara Iran mengeluarkan peringatan menjelang kunjungan Netanyahu ke AS",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/7/26/irans-army-issues-warning-ahead-of-netanyahus-us-visit?traffic_source=rss",
        "summary": "Iran says it has stopped retaliatory operations in the Gulf, but warns the war could expand if US strikes continue.",
        "published": "26 Jul 2026 18:56 WIB",
        "sentiment": "Bearish",
        "score": -0.935,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "‘Tidak ada pertanggungjawaban atas kejahatan perang pemukim terhadap warga Palestina’",
        "url": "https://www.aljazeera.com/video/newsfeed/2026/7/26/no-accountability-for-settler-war-crimes-against?traffic_source=rss",
        "summary": "‘No accountability for settler war crimes against Palestinians’",
        "published": "26 Jul 2026 18:31 WIB",
        "sentiment": "Bearish",
        "score": -0.832,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "Al Jazeera",
        "title": "Malaysia akan menjadi tuan rumah balapan F1 Grand Prix Bahrain yang dijadwalkan ulang pada bulan Oktober",
        "url": "https://www.aljazeera.com/sports/2026/7/26/malaysia-to-host-rescheduled-bahrain-grand-prix-f1-race-in-october?traffic_source=rss",
        "summary": "The race in Bahrain was rescheduled in April amid the US-Israel war on Iran and will now be held in Malaysia.",
        "published": "26 Jul 2026 18:28 WIB",
        "sentiment": "Bearish",
        "score": -0.306,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Ada 'ancaman rangkap tiga' teknis pada saham, namun ada juga tempat yang bisa disembunyikan oleh investor",
        "url": "https://www.marketwatch.com/story/theres-a-technical-triple-threat-for-stocks-but-also-places-investors-can-hide-59108c6b?mod=mw_rss_topstories",
        "summary": "Treasury yields and oil prices surged, and the dollar confirmed the breakout toward a longer-term uptrend, to push the S&P 500 below key chart support.",
        "published": "26 Jul 2026 20:00 WIB",
        "sentiment": "Bullish",
        "score": 0.572,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "MarketWatch",
        "title": "Pasar Treasury mengirimkan peringatan yang jelas kepada Ketua Fed Kevin Warsh tentang suku bunga",
        "url": "https://www.marketwatch.com/story/the-treasury-market-is-sending-fed-chair-kevin-warsh-a-clear-warning-about-rates-d0026da9?mod=mw_rss_topstories",
        "summary": "Rising Treasury yields show how “enormously worried” the market is about inflation — and whether the Fed will back up its tough talk with action",
        "published": "26 Jul 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.193,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC Forex",
        "title": "Buffett menyukai pajak properti, namun seperti semua miliarder lainnya, dia tidak akan membayarnya",
        "url": "https://www.cnbc.com/2026/07/25/buffett-favors-an-estate-tax-but-like-virtually-all-billionaires-he-wont-be-paying-it.html",
        "summary": "Warren Buffett believes he and other very wealthy Americans are under-taxed but by giving his fortune to charity, he won't be paying billions in potential levies to the government.",
        "published": "25 Jul 2026 19:28 WIB",
        "sentiment": "Bullish",
        "score": 0.855,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Ukraina menyerang kapal Iran di Laut Kaspia, Teheran menuduh Kyiv melakukan 'tindakan bermusuhan dan kriminal'",
        "url": "https://www.cnbc.com/2026/07/26/ukraine-strikes-iranian-vessels-tehran-accuses-kyiv-of-hostile-act.html",
        "summary": "The latest attacks by Ukraine, combined with Saudi military strikes on Iran-backed Houthi targets in Yemen, represent a widening of the Middle East conflict.",
        "published": "26 Jul 2026 21:50 WIB",
        "sentiment": "Bearish",
        "score": -1.0,
        "emoji": "🔴",
        "impact": "low"
      },
      {
        "source": "CNBC World",
        "title": "Harga kakao melemah. Lalu mengapa coklat masih begitu mahal?",
        "url": "https://www.cnbc.com/2026/07/26/cocoa-prices-chocolate-lindt-barry-callebaut-nestle.html",
        "summary": "Chocolate firms look to win shoppers back with premium products and social media trends after poor weather conditions, tariffs, and the Iran war hit sales.",
        "published": "26 Jul 2026 12:00 WIB",
        "sentiment": "Bearish",
        "score": -0.456,
        "emoji": "🔴",
        "impact": "high"
      },
      {
        "source": "CNBC World",
        "title": "Trump menggugat beberapa jam setelah tarif baru diberlakukan, karena para ahli mengatakan tarif tersebut mungkin tidak akan bertahan lama",
        "url": "https://www.cnbc.com/2026/07/24/trump-tariffs-lawsuit-301-ieepa.html",
        "summary": "President Donald Trump has renewed a flurry of tariffs, including slapping 25% duties on Brazilian imports and vowing 50% tariffs on goods from Canada.",
        "published": "25 Jul 2026 21:23 WIB",
        "sentiment": "Netral",
        "score": 0.0,
        "emoji": "⚪",
        "impact": "high"
      }
    ]
  },
  "fj_live": {
    "generated": "26 Jul 2026 22:01 WIB",
    "summary": {
      "total": 2,
      "bullish": 2,
      "bearish": 0,
      "netral": 0,
      "avg_score": 0.375,
      "overall": "Bullish"
    },
    "items": [
      {
        "source": "MarketWatch",
        "title": "Pasar Treasury mengirimkan peringatan yang jelas kepada Ketua Fed Kevin Warsh tentang suku bunga",
        "url": "https://www.marketwatch.com/story/the-treasury-market-is-sending-fed-chair-kevin-warsh-a-clear-warning-about-rates-d0026da9?mod=mw_rss_topstories",
        "summary": "Rising Treasury yields show how “enormously worried” the market is about inflation — and whether the Fed will back up its tough talk with action",
        "published": "26 Jul 2026 19:30 WIB",
        "sentiment": "Bullish",
        "score": 0.193,
        "emoji": "🟢",
        "impact": "high"
      },
      {
        "source": "Google News Forex",
        "title": "Perkiraan USD/JPY: Melimpahnya Data PDB Jepang Mungkin Membuat Yen Dalam Posisi Kuat Besok - Exchange Rates Org UK",
        "url": "https://news.google.com/rss/articles/CBMirwFBVV95cUxQUWpEZDV0TnA3Q0ZMbjZ3Q2xka0FMVlJ5eUpKbVIzSnRfVmJuQ1pIamhtcVRNbDJsemZ1NHAwbjJ3dW1iZ3p1RTMtSHF2QVRtWHZFMk1ucXMyTmtvbjNXdi12NEE0QXFKbUp2STNXdU1OLU5JelRvS09rUlczaWhmUlN5VDhYQ2Fkc2JZeDB0T2tBVVRXeDZ0bmZDVGNYUTBMVWlyYmZvSkp1TnFKVzRF?oc=5",
        "summary": "USD/JPY Forecast: Glut Of Japanese GDP Data May Leave Yen In Strong Position Tomorrow Exchange Rates Org UK",
        "published": "25 Jul 2026 14:48 WIB",
        "sentiment": "Bullish",
        "score": 0.557,
        "emoji": "🟢",
        "impact": "high"
      }
    ]
  },
  "rekomendasi": {
    "generated": "26 Jul 2026 22:01 WIB",
    "pairs": [
      {
        "label": "EUR/CAD",
        "score": 55,
        "direction": "SELL",
        "rsi": 42.4,
        "last_close": "1.60175",
        "smma7": "1.60258",
        "ema9": "1.60254",
        "atr14": "0.00138",
        "bars_since_cross": 0,
        "cross_label": "Baru saja",
        "freshness_score": 50,
        "separation_score": 1,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/USD",
        "score": 53,
        "direction": "SELL",
        "rsi": 44.3,
        "last_close": "1.33186",
        "smma7": "1.33244",
        "ema9": "1.33242",
        "atr14": "0.00110",
        "bars_since_cross": 0,
        "cross_label": "Baru saja",
        "freshness_score": 50,
        "separation_score": 0,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.441,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.441,
          "base_count": 0,
          "quote_count": 3,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/AUD",
        "score": 51,
        "direction": "BUY",
        "rsi": 51.1,
        "last_close": "1.90849",
        "smma7": "1.90786",
        "ema9": "1.90787",
        "atr14": "0.00191",
        "bars_since_cross": 0,
        "cross_label": "Baru saja",
        "freshness_score": 50,
        "separation_score": 0,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/CHF",
        "score": 47,
        "direction": "SELL",
        "rsi": 47.9,
        "last_close": "0.57978",
        "smma7": "0.58006",
        "ema9": "0.58004",
        "atr14": "0.00114",
        "bars_since_cross": 1,
        "cross_label": "1 candle lalu",
        "freshness_score": 45,
        "separation_score": 1,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/JPY",
        "score": 34,
        "direction": "BUY",
        "rsi": 54.6,
        "last_close": "163.791",
        "smma7": "163.791",
        "ema9": "163.798",
        "atr14": "0.101",
        "bars_since_cross": 4,
        "cross_label": "4 candle lalu",
        "freshness_score": 30,
        "separation_score": 2,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.441,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "JPY",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.441,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 1,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/NZD",
        "score": 21,
        "direction": "SELL",
        "rsi": 45.3,
        "last_close": "1.20577",
        "smma7": "1.20617",
        "ema9": "1.20597",
        "atr14": "0.00125",
        "bars_since_cross": 7,
        "cross_label": "7 candle lalu",
        "freshness_score": 15,
        "separation_score": 4,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/GBP",
        "score": 15,
        "direction": "SELL",
        "rsi": 41.2,
        "last_close": "0.85317",
        "smma7": "0.85358",
        "ema9": "0.85345",
        "atr14": "0.00055",
        "bars_since_cross": 9,
        "cross_label": "9 candle lalu",
        "freshness_score": 5,
        "separation_score": 6,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "GBP",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/JPY",
        "score": 13,
        "direction": "BUY",
        "rsi": 52.8,
        "last_close": "218.291",
        "smma7": "218.253",
        "ema9": "218.267",
        "atr14": "0.183",
        "bars_since_cross": 8,
        "cross_label": "8 candle lalu",
        "freshness_score": 10,
        "separation_score": 2,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/NZD",
        "score": 12,
        "direction": "SELL",
        "rsi": 40.4,
        "last_close": "1.96373",
        "smma7": "1.96471",
        "ema9": "1.96415",
        "atr14": "0.00203",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 7,
        "rsi_score": 5,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "NZD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CHF",
        "score": 9,
        "direction": "BUY",
        "rsi": 58.1,
        "last_close": "0.47329",
        "smma7": "0.47320",
        "ema9": "0.47335",
        "atr14": "0.00070",
        "bars_since_cross": 17,
        "cross_label": "17 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/USD",
        "score": 9,
        "direction": "SELL",
        "rsi": 42.1,
        "last_close": "1.13753",
        "smma7": "1.13783",
        "ema9": "1.13769",
        "atr14": "0.00077",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.441,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.441,
          "base_count": 1,
          "quote_count": 3,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "CHF/JPY",
        "score": 9,
        "direction": "SELL",
        "rsi": 42.2,
        "last_close": "200.233",
        "smma7": "200.301",
        "ema9": "200.270",
        "atr14": "0.160",
        "bars_since_cross": 12,
        "cross_label": "12 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CHF",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CHF",
        "score": 8,
        "direction": "BUY",
        "rsi": 57.5,
        "last_close": "1.08970",
        "smma7": "1.08937",
        "ema9": "1.08957",
        "atr14": "0.00118",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/AUD",
        "score": 8,
        "direction": "SELL",
        "rsi": 41.5,
        "last_close": "1.62785",
        "smma7": "1.62860",
        "ema9": "1.62833",
        "atr14": "0.00170",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 4,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "AUD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CHF",
        "score": 7,
        "direction": "BUY",
        "rsi": 56.1,
        "last_close": "0.81770",
        "smma7": "0.81760",
        "ema9": "0.81774",
        "atr14": "0.00081",
        "bars_since_cross": 39,
        "cross_label": "39 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.441,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CHF",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.441,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/CAD",
        "score": 7,
        "direction": "BUY",
        "rsi": 53.0,
        "last_close": "0.81546",
        "smma7": "0.81547",
        "ema9": "0.81566",
        "atr14": "0.00102",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 5,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/JPY",
        "score": 6,
        "direction": "BUY",
        "rsi": 53.9,
        "last_close": "94.815",
        "smma7": "94.806",
        "ema9": "94.822",
        "atr14": "0.097",
        "bars_since_cross": 15,
        "cross_label": "15 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/JPY",
        "score": 6,
        "direction": "SELL",
        "rsi": 43.4,
        "last_close": "186.245",
        "smma7": "186.315",
        "ema9": "186.298",
        "atr14": "0.120",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 3,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "USD/CAD",
        "score": 5,
        "direction": "BUY",
        "rsi": 54.0,
        "last_close": "1.40920",
        "smma7": "1.40897",
        "ema9": "1.40913",
        "atr14": "0.00135",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 2,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.441,
          "confidence": "Lemah",
          "base": "USD",
          "quote": "CAD",
          "base_sentiment": "Bullish",
          "quote_sentiment": "Netral",
          "base_score": 0.441,
          "quote_score": 0.0,
          "base_count": 3,
          "quote_count": 0,
          "base_insufficient": false,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "GBP/CAD",
        "score": 5,
        "direction": "BUY",
        "rsi": 52.6,
        "last_close": "1.87770",
        "smma7": "1.87736",
        "ema9": "1.87761",
        "atr14": "0.00159",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "GBP",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "NZD/USD",
        "score": 4,
        "direction": "BUY",
        "rsi": 49.6,
        "last_close": "0.57890",
        "smma7": "0.57901",
        "ema9": "0.57910",
        "atr14": "0.00060",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 4,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.441,
          "confidence": "Lemah",
          "base": "NZD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.441,
          "base_count": 0,
          "quote_count": 3,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      },
      {
        "label": "CAD/JPY",
        "score": 4,
        "direction": "SELL",
        "rsi": 48.2,
        "last_close": "116.217",
        "smma7": "116.240",
        "ema9": "116.230",
        "atr14": "0.098",
        "bars_since_cross": 10,
        "cross_label": "10 candle lalu",
        "freshness_score": 0,
        "separation_score": 3,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "CAD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "EUR/CHF",
        "score": 1,
        "direction": "BUY",
        "rsi": 47.8,
        "last_close": "0.92965",
        "smma7": "0.93000",
        "ema9": "0.93004",
        "atr14": "0.00088",
        "bars_since_cross": 20,
        "cross_label": "20 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "EUR",
          "quote": "CHF",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 1,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/JPY",
        "score": 1,
        "direction": "BUY",
        "rsi": 52.1,
        "last_close": "114.373",
        "smma7": "114.369",
        "ema9": "114.371",
        "atr14": "0.120",
        "bars_since_cross": 17,
        "cross_label": "17 candle lalu",
        "freshness_score": 0,
        "separation_score": 0,
        "rsi_score": 1,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "JPY",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 1,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/CAD",
        "score": 1,
        "direction": "BUY",
        "rsi": 44.9,
        "last_close": "0.98297",
        "smma7": "0.98371",
        "ema9": "0.98376",
        "atr14": "0.00152",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 1,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": 0.0,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "CAD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Netral",
          "base_score": 0.0,
          "quote_score": 0.0,
          "base_count": 0,
          "quote_count": 0,
          "base_insufficient": true,
          "quote_insufficient": true,
          "calendar_warning": []
        }
      },
      {
        "label": "AUD/USD",
        "score": 0,
        "direction": "BUY",
        "rsi": 47.6,
        "last_close": "0.69832",
        "smma7": "0.69858",
        "ema9": "0.69859",
        "atr14": "0.00063",
        "bars_since_cross": 14,
        "cross_label": "14 candle lalu",
        "freshness_score": 0,
        "separation_score": 0,
        "rsi_score": 0,
        "fundamental": {
          "signal": "Netral",
          "fund_score": -0.441,
          "confidence": "Lemah",
          "base": "AUD",
          "quote": "USD",
          "base_sentiment": "Netral",
          "quote_sentiment": "Bullish",
          "base_score": 0.0,
          "quote_score": 0.441,
          "base_count": 0,
          "quote_count": 3,
          "base_insufficient": true,
          "quote_insufficient": false,
          "calendar_warning": []
        }
      }
    ],
    "total": 26
  }
};
